### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by needleworm** [BioinformaticsFMRP/TCGAbiolinks#10]
Hi. I'm having problem installing TCGAbiolinks packages.
 

> Warning messages:
1: running command '"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\...\Documents\R\win-library\3.3" C:\Users\...AppData\Local\Temp\RtmpULAp33/downloaded_packages/TCGAbiolinks_2.0.0.tar.gz' had status 1 
2: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘TCGAbiolinks’ had non-zero exit status

I tried to install it from gz file but it also shows messege like this:

> ERROR: dependencies 'survival', 'limma' are not available for package 'TCGAbiolinks'
* removing 'C:/Users/.../Documents/R/win-library/3.3/TCGAbiolinks'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\...\Documents\R\win-library\3.3" "C://users/.../documents/TCGAbiolinks_2.0.0.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘C://users/.../documents/TCGAbiolinks_2.0.0.tar.gz’ had non-zero exit status

Do you have any idea what I should do?

**Comment by needleworm** [comment]
+
I had problem on windows 10.
But I tested on mac and didn't find that error.

**Comment by tiagochst** [comment]
I was able to install on windows today. Could you test it again ?

**Comment by needleworm** [comment]
It didn't work again, so I removed R environment on my computer and made an reinstall.
Now it's working.
