### ISSUE TITLE
Comparing dataset across platforms

### ISSUE THREAD

**Issue by blyoung** [BioinformaticsFMRP/TCGAbiolinks#102]
[Good Day_comparing datasets.docx](https://github.com/BioinformaticsFMRP/TCGAbiolinks/files/1075361/Good.Day_comparing.datasets.docx)

**Comment by tiagochst** [comment]
Hello,

There are two cbioportals:
* one with the new pipelines for data harmonization (data aligned to hg38) [GDC cbioportal](https://cbioportal.gdc.cancer.gov/cbioportal/index.do) which will be replaced by https://gdc-portal-staging.datacommons.io/
* one with data from several studies and data aligned to hg19 [Cbioportal](http://www.cbioportal.org/).

Your URL says it is the old version, if you are using `GDCquery_maf` you should compare with the first option. The maf files are very different. [Related discussion/question](https://support.bioconductor.org/p/92605/)

I checked and there are 5 mutation within those 11 patients. I'm not sure the cbioportal is being updated as it will be moved to DAVE.

But here is the cbioportal oncoprint.
<img width="1251" alt="screen shot 2017-06-14 at 11 13 44 am" src="https://user-images.githubusercontent.com/145529/27149855-d74ade12-50f9-11e7-99ce-72d03bca64ea.png">

Here are the 5 cases from the table:

<img width="1492" alt="screen shot 2017-06-14 at 12 06 53 pm" src="https://user-images.githubusercontent.com/145529/27149889-ff36edc6-50f9-11e7-991f-baa2eac4db55.png">

**Comment by blyoung** [comment]
Thanks

**Comment by blyoung** [comment]
Hi Again,
I am trying to install the TCGA/biolinks GUI and I get the following message below. Any advice on how I might fix this?

Thanks, 

Warning messages:
1: package ‘TCGAbiolinksGUI’ is not available (for R version 3.3.2) 
2: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘RSQLite’ had non-zero exit status
>
