### ISSUE TITLE
error with GDCprepare

### ISSUE THREAD

**Issue by kdpreter** [BioinformaticsFMRP/TCGAbiolinks#108]
When I run following script, in the end I get the error message below. How can I solve this problem?
Kind regards,

Katleen

query <- GDCquery(project = "TARGET-NBL",
                  data.category = "Transcriptome Profiling",
                  data.type = "Gene Expression Quantification",
                  workflow.type = "HTSeq - Counts",
                  legacy=T)
GDCdownload(query, method = "api", chunks.per.download = 10)
count_data <- GDCprepare(query)

Starting to add information to samples
Adding description to TARGET samples
 => Add clinical information to samples
Error in `$<-.data.frame`(`*tmp*`, "sample.aux", value = character(0)) : 
  replacement has 0 rows, data has 2

**Comment by tiagochst** [comment]
Hello,

HTSeq - Counts is not available in [legacy database](https://portal.gdc.cancer.gov/legacy-archive/search/f?filters=%7B%22op%22:%22and%22,%22content%22:%5B%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22cases.project.program.name%22,%22value%22:%5B%22TARGET%22%5D%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22cases.project.project_id%22,%22value%22:%5B%22TARGET-NBL%22%5D%7D%7D%5D%7D). Due to that, the first step (GDCquery) should give you an error.

This should work.
```
query <- GDCquery(project = "TARGET-NBL",
                  data.category = "Transcriptome Profiling",
                  data.type = "Gene Expression Quantification",
                  workflow.type = "HTSeq - Counts")
GDCdownload(query, method = "api", chunks.per.download = 10)
count_data <- GDCprepare(query)
```

**Comment by kdpreter** [comment]
Thanks a lot for your reply.
Unfortunately, with the script below I still get the error message:

Starting to add information to samples
Adding description to TARGET samples
 => Add clinical information to samples
Error in `$<-.data.frame`(`*tmp*`, "sample.aux", value = character(0)) :
  replacement has 0 rows, data has 169

Kind regards,

Katleen



On 29 Jun 2017, at 01:00, Tiago Chedraoui Silva <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

HTSeq - Counts is not available in legacy database<https://portal.gdc.cancer.gov/legacy-archive/search/f?filters=%7B%22op%22:%22and%22,%22content%22:%5B%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22cases.project.program.name%22,%22value%22:%5B%22TARGET%22%5D%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22cases.project.project_id%22,%22value%22:%5B%22TARGET-NBL%22%5D%7D%7D%5D%7D>. Due to that, the first step (GDCquery) should give you an error.

This should work.

query <- GDCquery(project = "TARGET-NBL",
                  data.category = "Transcriptome Profiling",
                  data.type = "Gene Expression Quantification",
                  workflow.type = "HTSeq - Counts")
GDCdownload(query, method = "api", chunks.per.download = 10)
count_data <- GDCprepare(query)
