### ISSUE TITLE
Error in TCGAvisualize_oncoprint()

### ISSUE THREAD

**Issue by ikramu** [BioinformaticsFMRP/TCGAbiolinks#11]
Hi,

While running TCGAvisualize_oncoprint() function for visualizing oncoprint, as given in the tutorial at https://bioconductor.org/packages/devel/bioc/vignettes/TCGAbiolinks/inst/doc/tcgaBiolinks.html#installation, the following error is given

TCGAvisualize_oncoprint(mut = mut, genes = mut$Hugo_Symbol[1:20],
filename = NULL, annotation = clin,
color=c("background"="#CCCCCC","DEL"="purple","INS"="yellow","SNP"="brown"),
rows.font.size=10, heatmap.legend.side = "right", dist.col = 0, label.font.size = 10)

Aggregate function missing, defaulting to 'length'
Error in names(column_order) = as.character(column_order) : 
  attempt to set an attribute on NULL

**Comment by tiagochst** [comment]
Hi,

 the code is working for me.

Please, which OS are you using? Windows, mac or linux? 
If it was windows, TCGAquery_Maf was not working, I fixed it today. Could you please, try it again?

Also, the ComplexHeatmap library I'm using is version 1.10.2. Please, which version are you using?

**Comment by ikramu** [comment]
Dear Tiago,

I updated ComplexHeatmap to the latest version (1.11.4), via devtools::install_github('Bioconductor-mirror/ComplexHeatmap') and it solved the problem.

Thanks a lot!
Ikram
