### ISSUE TITLE
GDC update caused issues

### ISSUE THREAD

**Issue by joemsong** [BioinformaticsFMRP/TCGAbiolinks#111]
Today GDC made a new data release. Then my previous code to download expression data via TCGAbiolinks no longer fully works. It works for some but not others. When I tried to re-download every file, the download also had problem in some files.

I have the latest version 2.5.4 of TCGAbiolinks installed on iMac.

> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.5

> query <- GDCquery(project="TCGA-PAAD",
+                   data.category = "Transcriptome Profiling",
+                   data.type = "Gene Expression Quantification",
+                   workflow.type = "HTSeq - FPKM-UQ")
--------------------------------------
o GDCquery: Searching in GDC database
--------------------------------------
Warning: 39 parsing failures.
row # A tibble: 5 x 5 col     row   col  expected    actual
                                            file expected   <int>
<chr>     <chr>     <chr>
         <chr> actual 1     1  <NA> 7 columns 8 columns
'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv' file 2
2  <NA> 7 columns 8 columns
'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv' row 3
3  <NA> 7 columns 8 columns
'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv' col 4
4  <NA> 7 columns 8 columns
'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv' expected 5
    5  <NA> 7 columns 8 columns
'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv'
... ................. ...
.............................................................................................
........ .............................................................................................
...... ........................... [... truncated]
--------------------------------------------
oo Accessing GDC. This might take a while...
--------------------------------------------
ooo Project: TCGA-PAAD
--------------------
oo Filtering results
--------------------
ooo By data.type
ooo By workflow.type
----------------
oo Checking data
----------------
ooo Check if there are duplicated cases
ooo Check if there results for the query
-------------------
o Preparing output
-------------------
Warning messages:
1: Unnamed `col_types` should have the same length as `col_names`.
Using smaller of the two.
2: In rbind(names(probs), probs_f) :
  number of columns of result is not a multiple of vector length (arg 1)

**Comment by samkleeman1** [comment]
I have the same problem

**Comment by ksenia1602** [comment]
Actually, I have the same problem with PRAD data
clinical <- GDCquery_clinic(project = "TCGA-PRAD", type = "clinical")

##########
Warning: 39 parsing failures.
row # A tibble: 5 x 5 col     row   col  expected    actual expected   <int> <chr>     <chr>     <chr> actual 1     1  <NA> 7 columns 8 columns file 2     2  <NA> 7 columns 8 columns row 3     3  <NA> 7 columns 8 columns col 4     4  <NA> 7 columns 8 columns expected 5     5  <NA> 7 columns 8 columns actual # ... with 1 more variables: file <chr>
... ................. ... ................................. ........ ................................. ...... ................................. .... ................................. ... ................................. ... ................................. ........ ................................. ...... .......................................
See problems(...) for more details.

Warning messages:
1: Unnamed `col_types` should have the same length as `col_names`. Using smaller of the two.
2: In rbind(names(probs), probs_f) :
  number of columns of result is not a multiple of vector length (arg 1)
################

And another example

query <- GDCquery(project = "TCGA-PRAD",
                  data.category = "Gene expression", 
                  data.type = "Gene expression quantification", 
                  legacy = TRUE,
                  sample.type = "Primary solid Tumor",
                  experimental.strategy = "RNA-Seq",
                  workflow.type = "HTSeq - FPKM-UQ"
)
 and error
############
--------------------------------------
o GDCquery: Searching in GDC database
--------------------------------------
Warning: 39 parsing failures.
row # A tibble: 5 x 5 col     row   col  expected    actual expected   <int> <chr>     <chr>     <chr> actual 1     1  <NA> 7 columns 8 columns file 2     2  <NA> 7 columns 8 columns row 3     3  <NA> 7 columns 8 columns col 4     4  <NA> 7 columns 8 columns expected 5     5  <NA> 7 columns 8 columns actual # ... with 1 more variables: file <chr>
... ................. ... ................................. ........ ................................. ...... ................................. .... ................................. ... ................................. ... ................................. ........ ................................. ...... .......................................
See problems(...) for more details.

--------------------------------------------
oo Accessing GDC. This might take a while...
--------------------------------------------
ooo Project: TCGA-PRAD
--------------------
oo Filtering results
--------------------
ooo By experimental.strategy
ooo By data.type
Error in GDCquery(project = "TCGA-PRAD", data.category = "Gene expression",  :
  Please set a valid workflow.type argument from the list below:
  =>
In addition: Warning messages:
1: Unnamed `col_types` should have the same length as `col_names`. Using smaller of the two.
2: In rbind(names(probs), probs_f) :
  number of columns of result is not a multiple of vector length (arg 1)

########################
