### ISSUE TITLE
MAF Query Failing

### ISSUE THREAD

**Issue by DarioS** [BioinformaticsFMRP/TCGAbiolinks#112]
It claims to complete the download, then to have missing files.

```
mutations <- GDCquery_Maf("SKCM", pipelines = "muse", directory = "/nb/dario/misc/")
Downloading data for project TCGA-SKCM
GDCdownload will download: 72.908209 MB
Download completed
Error in GDCprepare(query, directory = directory) : 
  I couldn't find all the files from the query. Please check if the directory parameter right or GDCdownload downloaded the samples.

> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

other attached packages:
[1] TCGAbiolinks_2.4.3
```

It seems that the file is not in the directory I specified.

```
$ find /nb/dario/misc/* -name \*somatic\*
$ 
$ ls /nb/dario/misc/
TCGA-SKCM
$ ls /nb/dario/misc/TCGA-SKCM/ # many more sub-directories below harmonized
harmonized
```

**Comment by tiagochst** [comment]
Could you please check the permissions of the directory?
I tried some examples here and it is working. Either the download was corrupted and it wrongly said it was completed or it could not write the file.

**Comment by DarioS** [comment]
The permissions are suitable. It only works if I don't specify any directory.

    $ whoami
    dario
    $ ls -l /nb/dario/ | grep misc
    drwxr-x---  4 dario stgrad      4096 Jul  7 16:46 misc

It doesn't even work with `/tmp/`.

    mutations <- GDCquery_Maf("SKCM", pipelines = "muse", directory = "/tmp/")
    Download completed
    Error in GDCprepare(query, directory = directory) : 
      I couldn't find all the files from the query. Please check if the directory parameter right or GDCdownload downloaded the samples.

**Comment by tiagochst** [comment]
It was working only on macOS, linux wasn't. Thank you for reporting the bug.
