### ISSUE TITLE
Samples Missing from MAF Import

### ISSUE THREAD

**Issue by DarioS** [BioinformaticsFMRP/TCGAbiolinks#113]
A small number of samples are missing. For example,

```
mutations <- GDCquery_Maf("SKCM", pipelines = "muse")
> grep("TCGA-EE-A2GK", unique(unlist(mutations[, "Tumor_Sample_Barcode"])))
integer(0)
```

On the GDC Portal homepage, pasting TCGA-EE-A2GK into the search box shows some files, once of which is a MuSE-processed mutation file, so this sample does indeed have such files available for download.

There are some warnings during the data preparation stage, which might give a hint about the cause.

```
Warning messages:
1: Unnamed `col_types` should have the same length as `col_names`. Using smaller of the two. 
2: In rbind(names(probs), probs_f) :
  number of columns of result is not a multiple of vector length (arg 1)
```

**Comment by tiagochst** [comment]
If you open the muse MAF file you cannot find TCGA-EE-A2GK.

<img width="2299" alt="screen shot 2017-07-07 at 11 05 31 am" src="https://user-images.githubusercontent.com/145529/27970582-426d123e-6304-11e7-84fe-1077922c4707.png">

But you can find it in mutect2 MAF file.
<img width="2299" alt="screen shot 2017-07-07 at 11 08 08 am" src="https://user-images.githubusercontent.com/145529/27970684-a3a0a354-6304-11e7-979f-1999024f4a0b.png">

I'm not sure how GDC is mapping the MAF files to the patients, but the file should not appear in the list of files for that user. I believe it is better to send an email to GDC support team.

**Comment by DarioS** [comment]
Enquiries with Genome Data Commons revealed that the samples missing were because of some MuSE filtering criteria and the missingness is intentional and not to be changed.
