### ISSUE TITLE
Problems with downloading data 

### ISSUE THREAD

**Issue by ksenia1602** [BioinformaticsFMRP/TCGAbiolinks#116]
I have the same problem  https://github.com/BioinformaticsFMRP/TCGAbiolinks/issues/111
 with PRAD data

clinical <- GDCquery_clinic(project = "TCGA-PRAD", type = "clinical")

##########
Warning: 39 parsing failures.
row # A tibble: 5 x 5 col row col expected actual expected actual 1 1 7 columns 8 columns file 2 2 7 columns 8 columns row 3 3 7 columns 8 columns col 4 4 7 columns 8 columns expected 5 5 7 columns 8 columns actual # ... with 1 more variables: file 
... ................. ... ................................. ........ ................................. ...... ................................. .... ................................. ... ................................. ... ................................. ........ ................................. ...... .......................................
See problems(...) for more details.

Warning messages:
1: Unnamed col_types should have the same length as col_names. Using smaller of the two.
2: In rbind(names(probs), probs_f) :
number of columns of result is not a multiple of vector length (arg 1)
################

And another example

query <- GDCquery(project = "TCGA-PRAD",
data.category = "Gene expression",
data.type = "Gene expression quantification",
legacy = TRUE,
sample.type = "Primary solid Tumor",
experimental.strategy = "RNA-Seq",
workflow.type = "HTSeq - FPKM-UQ"
)
and error
############

o GDCquery: Searching in GDC database

Warning: 39 parsing failures.
row # A tibble: 5 x 5 col row col expected actual expected actual 1 1 7 columns 8 columns file 2 2 7 columns 8 columns row 3 3 7 columns 8 columns col 4 4 7 columns 8 columns expected 5 5 7 columns 8 columns actual # ... with 1 more variables: file 
... ................. ... ................................. ........ ................................. ...... ................................. .... ................................. ... ................................. ... ................................. ........ ................................. ...... .......................................
See problems(...) for more details.

oo Accessing GDC. This might take a while...

ooo Project: TCGA-PRAD

oo Filtering results

ooo By experimental.strategy
ooo By data.type
Error in GDCquery(project = "TCGA-PRAD", data.category = "Gene expression", :
Please set a valid workflow.type argument from the list below:
=>
In addition: Warning messages:
1: Unnamed col_types should have the same length as col_names. Using smaller of the two.
2: In rbind(names(probs), probs_f) :
number of columns of result is not a multiple of vector length (arg 1)

########################

**Comment by tiagochst** [comment]
These are warnings, the update in GDC database added new columns. 
I don't get those using the last version. Could you please try the last version?
`devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")`

**Comment by ksenia1602** [comment]
Thanks) it works))
