### ISSUE TITLE
DMRs analysis error: GUI suddently closed 

### ISSUE THREAD

**Issue by bububeo** [BioinformaticsFMRP/TCGAbiolinks#118]
Hi there,

I am new to bioconductor and it's nice to have such a good GUI like this.

I am running Differential methylation analysis. 450k or 27K data was downloaded from GDC smoothly. However, DMR analysis couldn't be completed. 

- With 27K data, the GUI browser was suddenly closed and the error (attached image) shown in Rstudio console.
- With 450K data, GUI force-closed, rstudio still keep running and seems to get finished. No error message shown. But there is no result file created.

I am using the latest version of R, bioconductor, and TCGAbiolinksGUI.

Is there anything I can do to get over this?
Many thanks

<a href="https://ibb.co/kdqCza"><img src="https://preview.ibb.co/i5Feea/DMRs_27_K_error.jpg" alt="DMRs_27_K_error" border="0"></a>

**Comment by bububeo** [comment]
When I run the input file provided as demonstration, DMR analysis completed smoothly.

<img src="https://preview.ibb.co/dT5bsv/mmmm.jpg" border="0">

**Comment by bububeo** [comment]
After further tests, I realized that DMR analysis works well with legacy database but can not work with harmonized database

**Comment by tiagochst** [comment]
The bug was fished. But I'll leave it open as I believe the starburst plot will have the same problem for hg38.
