### ISSUE TITLE
Error report - GDCdownload

### ISSUE THREAD

**Issue by needleworm** [BioinformaticsFMRP/TCGAbiolinks#12]
Hello.

I've met some errors using GDCdownload function.

`GDCdownload(basalQuery)
  basalData <- GDCprepare(basalQuery)`

> Downloading as: Tue_Aug_02_17_11_55_2016.tar.gz
curl: (1) Protocol "'https" not supported or disabled in libcurl
Error in gzfile(path.expand(tarfile), "rb") : cannot open the connection
In addition: Warning messages:
1: running command 'curl -o Tue_Aug_02_17_11_55_2016.tar.gz --remote-header-name --request POST 'https://gdc-api.nci.nih.gov/legacy/data' --data @Payload' had status 1 
2: In gzfile(path.expand(tarfile), "rb") :
  cannot open compressed file 'Tue_Aug_02_17_11_55_2016.tar.gz', probable reason 'No such file or directory'

I fixed this error with

`trace("GDCdownload", edit = T)`

chaning 
`'https://gdc-api.nci.nih.gov/legacy/data' 
into 
`\"https://gdc-api.nci.nih.gov/legacy/data\"

fixed this issue.

However, another error came.

> GDCdownload(luminalQuery)
Downloading as: Tue_Aug_02_17_25_03_2016.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23563  100    44  100 23519     23  12443  0:00:01  0:00:01 --:--:-- 12443
Error in untar2(tarfile, files, list, exdir) : incomplete block on file

I tried several times. The name of .tar.gz file changes whenever I try, but same error message comes on my IDE.

I need someone's help.

**Comment by needleworm** [comment]
I found following error on Mac.


> Downloading

 as: Tue_Aug__2_18_10_18_2016.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100  7915  100    44  100  7871     25   4573  0:00:01  0:00:01 --:--:--  4576
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
[1] 1
Error in GDCdownload(basalQuery) : 
  There was an error in the download process, please execute it again
추가정보: 경고메시지(들): 
In untar(name) :
  ‘/usr/bin/tar -xf 'Tue_Aug__2_18_10_18_2016.tar.gz'’ returned error code 1

**Comment by mikeaalv** [comment]
It seems that this problem could be solved by setting GDCdownload(method="client"), but the program tends to install the "gdc-client" even though I have installed it.

**Comment by tiagochst** [comment]
As you said setting method to client will install the gdc-client. This is slower, but the download will work. 
Setting the method to "API"  will use POST method, which is faster, but is not 100% reliable,  If the tar.gz downloaded is corrupted it will ask to download again. I made some updated yesterday to use the httr libraries, I believe the API method is better now.
