### ISSUE TITLE
Mutation Summary Convenience Function

### ISSUE THREAD

**Issue by DarioS** [BioinformaticsFMRP/TCGAbiolinks#122]
It would be convenient to include a function in the package that can easily transform the downloaded MAF table into a matrix, with the rows being genes, the columns being samples, and the entries being the number of non-synonymous mutations counted for a particular gene of a particular sample.

**Comment by tiagochst** [comment]
I believe you can use the maftools package for MAF files analysis. They are doing a really good job. 

https://bioconductor.org/packages/devel/bioc/vignettes/maftools/inst/doc/maftools.html

You can import it into their format with:
```
library(TCGAbiolinks)
library(magrittr)
library(maftools)
maf <- GDCquery_Maf("SKCM", pipelines = "muse") %>% read.maf(removeSilent = TRUE, useAll = FALSE)
```

**Comment by DarioS** [comment]
Thank you for the good advice. I will request a function be added to the maftools developer. It seems like the most appropriate package for it.

**Comment by DarioS** [comment]
maftools has added the function `mutCountMatrix` which makes this task easy to do.
