### ISSUE TITLE
Function to Determine Data Release Version

### ISSUE THREAD

**Issue by DarioS** [BioinformaticsFMRP/TCGAbiolinks#125]
When making an R Markdown file that other people will reads in the months and years ahead, it would be good to be able to show the release version of Genomic Data Commons Data Portal, currently 7.0. There's no R function in the package that allows this to be queried. Sometimes, in the Release Notes, there are sample ID switches mentioned, so the release version would be useful to record.

**Comment by tiagochst** [comment]
You will be able to get that information with getGDCInfo()$data_relase which is the same information here: https://api.gdc.cancer.gov/status

**Comment by tiagochst** [comment]
## To do
- [x]  Create function to access data release information 
- [ ]  Add data relase information into the Summarized Experiment along with genome of reference.
