### ISSUE TITLE
GDCprepare() load data unsuccessful

### ISSUE THREAD

**Issue by ShixiangWang** [BioinformaticsFMRP/TCGAbiolinks#129]
I follow the http://www.bioconductor.org/packages/release/bioc/vignettes/TCGAbiolinks/inst/doc/tcgaBiolinks.html#gdcdownload:_downloading_gdc_data try to do some analysis.

```
# load packages, query and download data
require(TCGAbiolinks)
query.exp.hg19 <- GDCquery(project = c("TCGA-LUAD", "TCGA-LUSC"),
                           data.category = "Gene expression",
                           data.type = "Gene expression quantification",
                           platform = "Illumina HiSeq", 
                           file.type  = "normalized_results",
                           sample.type = c("Primary solid Tumor","Solid Tissue Normal"),
                           experimental.strategy = "RNA-Seq",
                           legacy = TRUE,
                           access = "open")
GDCdownload(query.exp.hg19)
exp.data <- GDCprepare(query.exp.hg19) 
```
Some error happened:
```
> exp.data <- GDCprepare(query.exp.hg19)
  |========================================================================================================| 100%
Downloading genome information (try:0) Using: Homo sapiens genes (GRCh37.p13)
Loading from disk
Starting to add information to samples
 => Add clinical information to samples
Error in rbindlist(l, use.names, fill, idcol) : 
  Item 2 has 51 columns, inconsistent with item 1 which has 25 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.
此外: There were 22 warnings (use warnings() to see them)
```
It remind me to set `fill` to `TRUE`, I try
```
> exp.data <- GDCprepare(query.exp.hg19, fill=TRUE)
Error in GDCprepare(query.exp.hg19, fill = TRUE) : 
  参数没有用(fill = TRUE)
```

The function has no argument `fill`, how can I fix this problem? Do I need to load project data one by one?

**Comment by thecourseraway** [comment]
Bioconductor version 3.8 (BiocManager 1.30.4), R version 3.5.3
I am facing the same issue with the following:
query <- GDCquery(project = "TCGA-ESCA",
                  data.category = "Transcriptome Profiling",
                  data.type = "Gene Expression Quantification", 
                  workflow.type = "HTSeq - Counts", sample.type = c("Primary solid Tumor"))
GDCdownload(query)
data <- GDCprepare(query)
Starting to add information to samples
 => Add clinical information to samples
Error in rbindlist(l, use.names, fill, idcol) : 
  Item 2 has 58 columns, inconsistent with item 1 which has 59 columns. To fill missing columns use fill=TRUE.

**Comment by tiagochst** [comment]
@thecourseraway GDC made an update in the API, one of the samples TCGA-IC-A6RF is not returning days_to_death. I just fixed. Can you install using github? 

`devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")`

**Comment by thecourseraway** [comment]
Thanks. but when I try installing using github, I get the following error:
Error in lazyLoadDBinsertVariable(vars[i], from, datafile, ascii, compress,  : 
  (converted from warning) internal error 10 in R_compress3
ERROR: unable to build sysdata DB for package 'TCGAbiolinks'

**Comment by thecourseraway** [comment]
update: it worked with R version update.
Thanks!

**Comment by JonatanFernandez** [comment]
After installing the new version from the repo, it still returns an rbindlist error. My query is on the TCGA-PCPG data. The code worked just fine a few weeks ago but now I cannot reproduce it.

`> RNAseq_data <- GDCprepare(RNAseq_query, summarizedExperiment = TRUE)
  |=============================================================================================================================| 100%Accessing grch37.ensembl.org to get gene information
Downloading genome information (try:0) Using: Human genes (GRCh37.p13)
Loading from disk
Starting to add information to samples
 => Add clinical information to samples
Error in rbindlist(l, use.names, fill, idcol) : 
  Item 2 has 58 columns, inconsistent with item 1 which has 57 columns. To fill missing columns use fill=TRUE.`
