### ISSUE TITLE
Function suggestion - Ability to download data without project

### ISSUE THREAD

**Issue by SCP-028** [BioinformaticsFMRP/TCGAbiolinks#13]
For example, [this](https://gdc-portal.nci.nih.gov/legacy-archive/files/3d23bf42-1761-42b9-b5e1-fa9bbd0b47f0) has everything else but a project, and you can neither query nor download it due to that reason.

Thanks.

**Comment by tiagochst** [comment]
Hi, 
that is quite strange, but That sample should belong to TCGA-BRCA. I verified and that is true. 
The sample has no project. 

I will see how I can improve query, the next days. I'll take into account that exception.
Have you asked GDC if this sample shouldn't have a project?

**Comment by SCP-028** [comment]
Hi tiagochst,

I think the samples actually *do* have projects, but GDC didn't show the property. The names of the files contain the projects they are in.

**Comment by tiagochst** [comment]
I sent the problem to GDC they openned a ticket. So I agree, they have
project.
I'll remove for the moment that requirement (to have a project) a ser if
with the file name we can get those samples. I'll do it very soon.

Em 5 de ago de 2016 1:32 PM, "SCP-028" <notifications@github.com> escreveu:

**Comment by SCP-028** [comment]
Great. Thanks a lot!
