### ISSUE TITLE
Mutation Count

### ISSUE THREAD

**Issue by citifun** [BioinformaticsFMRP/TCGAbiolinks#145]
Is there a problem with extracting mutation data? 
For example C3 in Ovarian Carcinoma gives far more mutations than given in cBioportal

> table(samples.information[, "mut_hg38_C3" ])

FALSE  TRUE 
  202   177 

whereas in cBioportal there are only 3 missense mutations documented for the C3 gene.

Are you extracting all genes with "C3" in their name?
e.g.
TACC3
PSMC3
PABPC3
SLC39A12
C3ORF20
C3ORF22
STAC3
MC3R
TUSC3
BIRC3
C3ORF30

**Comment by tiagochst** [comment]
Yes, I'm sorry there was the exactly bug you described.
