### ISSUE TITLE
TCGAanalyze_SurvivalKM : negative subscripts error

### ISSUE THREAD

**Issue by citifun** [BioinformaticsFMRP/TCGAbiolinks#146]
Hi
I have this error:
TCGAanalyze_SurvivalKM(clinical_patient, dataGE, Genelist, Survresult,
+                        ThreshTop = 0.67, ThreshDown = 0.33, p.cut = 0.05, group1, group2)
710.
**Error in mRNAselected_values_ordered[1:(lastelementTOP - 1)] : 
  only 0's may be mixed with negative subscripts**

Error occurs at  line 59
"  57          lastelementTOP <- round(numberOfSamples/3)
   58         firstelementDOWN <- numberOfSamples - lastelementTOP
   59        samples_top_mRNA_selected <- colnames(as.matrix(mRNAselected_values_ordered[1:(lastelementTOP - 1)]))"_

(lastelementTOP - 1)  generates "-1"

Thanks for your help!

**Comment by citifun** [comment]
I think you need to transpose the results of "as.matrix" in the following sections (edits already made) or change  'colnames to rownames'  and 'rownames to colnames' 

            numberOfSamples <- ncol(**t**(as.matrix(mRNAselected_values_ordered)))
            lastelementTOP <- round(numberOfSamples/3)
            firstelementDOWN <- numberOfSamples - lastelementTOP
            samples_top_mRNA_selected <- colnames(**t**(as.matrix(mRNAselected_values_ordered[1:(lastelementTOP - 
                1)])))
            samples_down_mRNA_selected <- colnames(**t**(as.matrix(mRNAselected_values_ordered[(firstelementDOWN + 
                1):numberOfSamples])))
            samples_UNCHANGED_mRNA_selected <- rownames(**t**(as.matrix(which((mRNAselected_values_newvector) > 
                mRNAselected_values_ordered_down & mRNAselected_values_newvector < 
                mRNAselected_values_ordered_top))))

**Comment by tiagochst** [comment]
I'm sorry for the delay, @torongs82 Created that function, I was expecting he was going to fix it.
It seems this line of the code was wrong
```
samples_UNCHANGED_mRNA_selected <- rownames(as.matrix(which((mRNAselected_values_newvector) > 
            mRNAselected_values_ordered_down & mRNAselected_values_newvector < 
            mRNAselected_values_ordered_top))) 
```
Since it was trying to get the index of samples in the intermediate group and getting their rownames.
@torongs82 Could you review this function please?
