### ISSUE TITLE
download WGS data from GDC

### ISSUE THREAD

**Issue by jiajiayb** [BioinformaticsFMRP/TCGAbiolinks#149]
Hi, I am trying to download some WGS data from GDC using TCGAbiolinks. The command I am using is: 
query <- GDCquery(project = project, data.category='Raw Sequencing Data', experimental.strategy='WGS', barcode=filebarcodes)
GDCdownload(query, token.file=token.file, method='client')

The error I got is:
Accessing GDC. This might take a while...
The argument experimental_strategy does not match any of the results.
Possible values:RNA-Seq
=>WXS
=>miRNA-Seq

I just wonder what is the right command to download WGS. Thanks a lot!

**Comment by tiagochst** [comment]
Hello,

I was only able to find WGS in the legacy archive. 

## Legacy Archive
<img width="358" alt="screen shot 2017-09-28 at 12 13 26 am" src="https://user-images.githubusercontent.com/145529/30947827-5bf47fca-a3e2-11e7-8121-f33117b090b0.png">

## Harmonized
<img width="363" alt="screen shot 2017-09-28 at 12 13 15 am" src="https://user-images.githubusercontent.com/145529/30947828-5c5481a4-a3e2-11e7-920f-05910de868e6.png">


For that case the code for the query is below.

```
library(TCGAbiolinks)
query <- GDCquery(project = "TCGA-BRCA", 
                  data.category = 'Raw sequencing data', 
                  experimental.strategy = 'WGS', 
                  legacy = T,
                  barcode = c("TCGA-A7-A0D9-01A", "TCGA-B6-A0RT"))

getResults(query)

```
