### ISSUE TITLE
Problem Parsing Patient info

### ISSUE THREAD

**Issue by kvougas** [BioinformaticsFMRP/TCGAbiolinks#15]
I ran the following commands:

`query <- GDCquery(project = "TCGA-BLCA", data.category = "Clinical")
GDCdownload(query,directory = "~/Projects/GDC/Clinical")
clinical <- GDCprepare_clinic(query,"patient",directory = "~/Projects/GDC/Clinical")`

and I get the following error:

Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match

**Comment by tiagochst** [comment]
Could you install and try it again , some files have an extra empty column.
```
devtools::install_github(repo = "BioinformaticsFMRP/TCGAbiolinks")
library(TCGAbiolinks)
query <- GDCquery(project = "TCGA-BLCA", data.category = "Clinical") 
GDCdownload(query,directory = "~/Projects/GDC/Clinical") 
clinical <- GDCprepare_clinic(query,"patient",directory = "~/Projects/GDC/Clinical")
```

**Comment by kvougas** [comment]
Thanks, it worked like a charm!!
