### ISSUE TITLE
TCGAbiolinks installation

### ISSUE THREAD

**Issue by ghost187r** [BioinformaticsFMRP/TCGAbiolinks#150]
I am a complete new fellow in R software and language. My major is oncology, therefore I hope to install the TCGAbiolinks and TCGAbiolinksGUI for mining TCGA data. While during installation, problems appeared.
`> library(TCGAbiolinks)
Error: package or namespace load failed for ‘TCGAbiolinks’:
 object ‘rbind.gtable’ is not exported by 'namespace:gridExtra' `
`> library(TCGAbiolinks)
Error: package or namespace load failed for ‘TCGAbiolinks’:
 object ‘rbind.gtable’ is not exported by 'namespace:gridExtra' 
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1`

##Someone tell me that the TCGAbiolinks in Bioconductor dose not work anymore and suggest me to try a dev version of TCGAbiolinks in Github. But things are not going right.

`> install_github(repo = "BioinformaticsFMRP/TCGAbiolinks")
Installation failed: SSL certificate problem: unable to get local issuer certificate
` 
Now really apprietiate to have your suggestions in dealing this problem. THX.

**Comment by tiagochst** [comment]
The package was update in Biocondutor, it should be working. Please, which version do you have installed?

**Comment by ghost187r** [comment]
Oh, thanks very much for **tiagochst**'s response. Your team really did a great job. We are looking forward to see detailed paper of your TCGAbiolinksGUI. 
The newest version now TCGAbiolinks_2.5.9.zip for windows
`> utils:::menuInstallLocal()
package ‘TCGAbiolinks’ successfully unpacked and MD5 sums checked
Warning: unable to move temporary installation ‘C:\R\R-3.4.1\library\filecec124358d4\TCGAbiolinks’ to ‘C:\R\R-3.4.1\library\TCGAbiolinks’
> library(TCGAbiolinks)
Error in library(TCGAbiolinks) : 
  there is no package called ‘TCGAbiolinks’
`
Looking forward to your response. And best wishes.

**Comment by ghost187r** [comment]
Oh, tiagochst, thanks very much for your group and your exellent job, which means great to me. 
Looking forward to see your newest paper on TCGAbiolinksGUI.
After downloarding the newest version of TCGAbiolinks_2.5.9, the problem solved unexpectedly. 
Thanks and best wishes!

**Comment by ghost187r** [comment]
Now there is another question appeared during installation of TCGAbiolinksGUI.
The firewall or antivirus has already been turned off.
`library(TCGAbiolinksGUI)` ##works good. BUT
`TCGAbiolinksGUI()` ##calls for a package called "Homo.sapiens"
I downloard the "Homo.sapiens_1.3.1.tar.gz" from bioconductor, and 
` install.packages("Homo.sapiens_1.3.1.tar.gz")`
###BUT problem appeared again
`inferring 'repos = NULL' from 'pkgs'
ERROR: dependency 'TxDb.Hsapiens.UCSC.hg19.knownGene' is not available for package 'Homo.sapiens'
* removing 'C:/R/R-3.4.1/library/Homo.sapiens'
Warning messages:
1: running command '"C:/R/R-3.4.1/bin/x64/R" CMD INSTALL -l "C:\R\R-3.4.1\library" "Homo.sapiens_1.3.1.tar.gz"' had status 1 
2: In install.packages("Homo.sapiens_1.3.1.tar.gz") :
  installation of package ‘Homo.sapiens_1.3.1.tar.gz’ had non-zero exit status`

How can we deal with this problem. Looking forward to your response.
