### ISSUE TITLE
Download is not successfull; I am getting warning

### ISSUE THREAD

**Issue by AswathyPaul** [BioinformaticsFMRP/TCGAbiolinks#155]
I am trying to download the rsem values of normal samples.
I tried with sample ids and also I tried using the command;
```
query.exp <- GDCquery(project = "TCGA-BRCA", 
                      legacy = TRUE,
                      data.category = "Gene expression",
                      data.type = "Gene expression quantification",
                      platform = "Illumina HiSeq", 
                      file.type = "results",
                      experimental.strategy = "RNA-Seq",
                      sample.type = c("Primary solid Tumor","Solid Tissue Normal"))

```
But I am getting warnings. I don't have any source to map what are ids that are download because I didn't used UUIDS

<simpleWarning in file.copy(from = from, to = todir, recursive = TRUE): problem copying .\d2942788-87ff-44b4-944b-7d671607117d\logs\unc.edu.a521a6fa-da2b-48ef-94e8-3307030427b6.1174802.rsem.genes.results.parcel to GDCdata\TCGA-BRCA\legacy\Gene_expression\Gene_expression_quantification\d2942788-87ff-44b4-944b-7d671607117d\logs\unc.edu.a521a6fa-da2b-48ef-94e8-3307030427b6.1174802.rsem.genes.results.parcel: No such file or directory>

What can be the possible error ?? 
All the folders are empty , I mean the subfolders inside GDCdata
[code_r.txt](https://github.com/BioinformaticsFMRP/TCGAbiolinks/files/1374917/code_r.txt)

**Comment by tiagochst** [comment]
Please, which version of the package are you using.
And which is the methods used to download: API or client?

**Comment by AswathyPaul** [comment]
TCGAbIolinks 2.5.9

I tried to download using client method

**Comment by atakanekiz** [comment]
I have this warning message as well. But in my case, the download is successful. I wonder why this warning is prompted.
