### ISSUE TITLE
data download by TCGAbiolink library

### ISSUE THREAD

**Issue by mahtab96** [BioinformaticsFMRP/TCGAbiolinks#160]
hi
query is not found by this library. what do i do??
help me please.
what does mean of this error?
Error in checkProjectInput(project) : 
  Please set a valid project argument from the column id above. Project TCGA-BRCA was not found.
In addition: Warning messages:
1: Unnamed `col_types` should have the same length as `col_names`. Using smaller of the two. 
2: In rbind(names(probs), probs_f) :
  number of columns of result is not a multiple of vector length (arg 1)
3: Unknown or uninitialised column: 'project_id'. 
4: Unknown or uninitialised column: 'project_id'.

**Comment by tiagochst** [comment]
Please, do you have the last version installed ?

It can be installed with:
`devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")`

The following code is working for me:

```
query.exp.hg38 <- GDCquery(project = "TCGA-BRCA", 
                           data.category = "Transcriptome Profiling", 
                           data.type = "Gene Expression Quantification", 
                           workflow.type = "HTSeq - FPKM")

```

**Comment by k8hertweck** [comment]
I had the same problem with the install available through Bioconductor, but the GitHub install fixed it. Thanks for the work on this project; it's a great research and training tool!

**Comment by eshelden** [comment]
I also encountered this problem, and the solution mentioned by k8hertweck worked for me too.
