### ISSUE TITLE
gdc data download

### ISSUE THREAD

**Issue by mahtab96** [BioinformaticsFMRP/TCGAbiolinks#167]
hi
i want to download CNV and RNAseq data but i receive this error and download is incomplete.
please help me.
```

> query.cnv.BRCA <- GDCquery(project = "TCGA-BRCA",
+                            legacy = TRUE,
+                            data.category = "Copy number variation",
+                            platform="Affymetrix SNP Array 6.0",
+                            file.type="nocnv_hg19.seg",
+                            sample.type = "Primary solid Tumor")
--------------------------------------
o GDCquery: Searching in GDC database
--------------------------------------
Genome of reference: hg19
--------------------------------------------
oo Accessing GDC. This might take a while...
--------------------------------------------
ooo Project: TCGA-BRCA
--------------------
oo Filtering results
--------------------
ooo By platform
ooo By file.type
ooo By sample.type
----------------
oo Checking data
----------------
ooo Check if there are duplicated cases
ooo Check if there results for the query
-------------------
o Preparing output
-------------------
> GDCdownload(query.cnv.BRCA)
Downloading data for project TCGA-BRCA
GDCdownload will download 1099 files. A total of 22.308816 MB
Downloading as: Tue_Nov_21_21_05_53_2017.tar.gz
Downloading: 4.3 MB     
> query.cnv.BRCA <- GDCprepare(query = query.cnv.BRCA,
+                              save = TRUE,
+                              save.filename = "query.cnv.BRCA",
+                              summarizedExperiment = TRUE)
Reading copy number variation files
  |===========================================================================| 100%
Saving file:query.cnv.BRCA
File saved
> save(query.cnv.BRCA,file="query.cnv.BRCA.RData")
> cnv=assay(query.cnv.BRCA)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘assay’ for signature ‘"tbl_df", "missing"
```

**Comment by tiagochst** [comment]
Hello, which TCGAbiolinks version are you using?
I was able to run the code with version 2.7.4.

```
query.cnv.BRCA <- GDCquery(project = "TCGA-BRCA",
                           legacy = TRUE,
                           data.category = "Copy number variation",
                           platform="Affymetrix SNP Array 6.0",
                           file.type="nocnv_hg19.seg",
                           sample.type = "Primary solid Tumor")

GDCdownload(query.cnv.BRCA)
query.cnv.BRCA <- GDCprepare(query = query.cnv.BRCA,
                             save = TRUE,
                             save.filename = "query.cnv.BRCA.rda",
                             summarizedExperiment = TRUE)
```
<img width="695" alt="screen shot 2017-11-21 at 5 19 23 pm" src="https://user-images.githubusercontent.com/145529/33092088-3fb19450-cee0-11e7-8a33-249e855ca73d.png">

**Comment by mahtab96** [comment]
in your run download is incomplete too.
from 22 MB it has just 4.3 MB downloaded and in comprising array we face with error
please look at my error again.
thanks

**Comment by tiagochst** [comment]
The 4.3 MB is the compressed while the 22MB is the uncompressed one. The api method downloads the files compressed and using the gdc client it Will download uncompressed

**Comment by mahtab96** [comment]
thanks for your answer.
do you know whats the mining this error??
> save(query.cnv.BRCA,file="query.cnv.BRCA.RData")
> cnv=assay(query.cnv.BRCA)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘assay’ for signature ‘"tbl_df", "missing"’

**Comment by torongs82** [comment]
Hi @mahtab96 if you tell us which version of TCGAbiolinks are you using this can help, and also please can you provide your sessionInfo() ?

For that error can you try 

require(SummarizedExperiment)

and if you didn't installed it you can find here 

source("https://bioconductor.org/biocLite.R")
biocLite("SummarizedExperiment")

thanks
Antonio.

**Comment by mahtab96** [comment]
hi thanks for your answer
i have installed this version TCGAbiolinks_2.6.1.
how can i install a higher version???

**Comment by tiagochst** [comment]
Tou can install from GitHub 


devtools::install_github(repo = "BioinformaticsFMRP/TCGAbiolinks")

**Comment by mahtab96** [comment]
hi
i upgraded my TCGABiolinks and unfortunately i got this error again :-(
save(query.cnv.BRCA,file="query.cnv.BRCA.RData")
> cnv=assay(query.cnv.BRCA)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘assay’ for signature ‘"tbl_df", "missing"’

**Comment by mahtab96** [comment]
can you please execute these codes and send me their outputs???
thanks
# Getting Expression data
query.exp.BRCA <- GDCquery(project = "TCGA-BRCA",
                           legacy = TRUE,
                           data.category = "Gene expression",
                           data.type="Gene expression quantification",
                           file.type="normalized_results",
                           platform = "Illumina HiSeq",
                           sample.type = "Primary solid Tumor")
GDCdownload(query.exp.BRCA)
query.exp.BRCA <- GDCprepare(query = query.exp.BRCA,
                             save = TRUE,
                             save.filename = "query.exp.BRCA" ,
                             summarizedExperiment = TRUE)
expr=assay(query.exp.BRCA)
save(expr,file = "expr.RData")
#geting CNV data
query.cnv.BRCA <- GDCquery(project = "TCGA-BRCA",
                           legacy = TRUE,
                           data.category = "Copy number variation",
                           platform="Affymetrix SNP Array 6.0",
                           file.type="nocnv_hg19.seg",
                           sample.type = "Primary solid Tumor")
GDCdownload(query.cnv.BRCA)
query.cnv.BRCA <- GDCprepare(query = query.cnv.BRCA,
                             save = TRUE,
                             save.filename = "query.cnv.BRCA",
                             summarizedExperiment = TRUE)
save(query.cnv.BRCA,file="query.cnv.BRCA.RData")
cnv=assay(query.cnv.BRCA)
save(cnv,file = "cnv.RData")

**Comment by tiagochst** [comment]
The CNV output is a dataframe. We don't prepare it as a summarized Experiment.


<img width="566" alt="screen shot 2017-11-25 at 9 58 27 am" src="https://user-images.githubusercontent.com/145529/33230283-6043eada-d1c7-11e7-8584-45af0194dd01.png">

```
library(TCGAbiolinks)
library(SummarizedExperiment)
query.exp.BRCA <- GDCquery(project = "TCGA-BRCA",
                           legacy = TRUE,
                           data.category = "Gene expression",
                           data.type="Gene expression quantification",
                           file.type="normalized_results",
                           platform = "Illumina HiSeq",
                           sample.type = "Primary solid Tumor")
GDCdownload(query.exp.BRCA, files.per.chunk = 20)
query.exp.BRCA <- GDCprepare(query = query.exp.BRCA,
                             save = TRUE,
                             save.filename = "query.exp.BRCA" ,
                             summarizedExperiment = TRUE)
expr=assay(query.exp.BRCA)
save(expr,file = "expr.RData")

# geting CNV data
query.cnv.BRCA <- GDCquery(project = "TCGA-BRCA",
                           legacy = TRUE,
                           data.category = "Copy number variation",
                           platform="Affymetrix SNP Array 6.0",
                           file.type="nocnv_hg19.seg",
                           sample.type = "Primary solid Tumor")
GDCdownload(query.cnv.BRCA, files.per.chunk = 20)
query.cnv.BRCA <- GDCprepare(query = query.cnv.BRCA,
                             save = TRUE,
                             save.filename = "cnv.BRCA.RData",
                             summarizedExperiment = TRUE)
save(query.cnv.BRCA,file="query.cnv.BRCA.RData")
```

**Comment by mahtab96** [comment]
and what about expression data??
gig you get its output???

**Comment by tiagochst** [comment]
You forget to set the  experimental.strategy. 

```
library(TCGAbiolinks)
library(SummarizedExperiment)
query.exp.BRCA <- GDCquery(project = "TCGA-BRCA",
                           legacy = TRUE,
                           data.category = "Gene expression",
                           data.type="Gene expression quantification",
                           experimental.strategy = "RNA-Seq",
                           file.type="normalized_results",
                           platform = "Illumina HiSeq",
                           sample.type = "Primary solid Tumor")
GDCdownload(query.exp.BRCA, files.per.chunk = 20)
query.exp.BRCA <- GDCprepare(query = query.exp.BRCA,
                             save = TRUE,
                             save.filename = "query.exp.BRCA" ,
                             summarizedExperiment = TRUE)
expr=assay(query.exp.BRCA)
save(expr,file = "expr.RData")
```

<img width="1043" alt="screen shot 2017-11-26 at 8 42 22 pm" src="https://user-images.githubusercontent.com/145529/33245105-576f4098-d2ea-11e7-9870-8d4ee65b28c8.png">
