### ISSUE TITLE
Error report - GDCprepare

### ISSUE THREAD

**Issue by Wanvdphelys** [BioinformaticsFMRP/TCGAbiolinks#17]
Hi,
 I've encountered with some error when using GDCprepare function.

```
library(TCGAbiolinks)

query = GDCquery(project = 'TCGA-HNSC',
                 data.category = 'Transcriptome Profiling',
                 data.type = 'Gene Expression Quantification',
                 workflow.type = 'HTSeq - FPKM'
                 )

GDCdownload(query, method = "client", directory = 'GDCdata')

HNSCdata = GDCprepare(query)
```

And the error came:

> Starting to add information to samples
 => Add clinical information to samples
 => Adding subtype information to samples
Subtype information from:doi:10.1038/nature14129
Extra content at the end of the document
Error: 1: Extra content at the end of the document

traceback:

> 10: stop(e)
9: (function (msg, ...) 
   {
       if (length(grep("\\\n$", msg)) == 0) 
           paste(msg, "\n", sep = "")
       if (immediate) 
           cat(msg)
       if (length(msg) == 0) {
           e = simpleError(paste(1:length(messages), messages, sep = ": ", 
               collapse = ""))
           class(e) = c(class, class(e))
           stop(e)
       }
       messages <<- c(messages, msg)
   })(character(0))
8: .Call("RS_XML_ParseTree", as.character(file), handlers, as.logical(ignoreBlanks), 
       as.logical(replaceEntities), as.logical(asText), as.logical(trim), 
       as.logical(validate), as.logical(getDTD), as.logical(isURL), 
       as.logical(addAttributeNamespaces), as.logical(useInternalNodes), 
       as.logical(isHTML), as.logical(isSchema), as.logical(fullNamespaceInfo), 
       as.character(encoding), as.logical(useDotNames), xinclude, 
       error, addFinalizer, as.integer(options), as.logical(parentFirst), 
       PACKAGE = "XML")
7: xmlTreeParse(registry, asText = TRUE)
6: listMarts(host = host, path = path, port = port, includeHosts = TRUE, 
       archive = archive, ssl.verifypeer = ssl.verifypeer)
5: useMart("ensembl", dataset = "hsapiens_gene_ensembl")
4: get.GRCh.bioMart("hg38")
3: makeSEfromTranscriptomeProfiling(df, cases, workflow.type)
2: readTranscriptomeProfiling(files = files, data.type = query$data.type, 
       workflow.type = unique(query$results[[1]]$analysis$workflow_type), 
       cases = query$results[[1]]$cases, summarizedExperiment)
1: GDCprepare(query)

have little knowledge about coding, need help.

**Comment by tiagochst** [comment]
Hi,

This is an error in the biomart package.

```
> library(biomaRt)
> ensembl <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")
Extra content at the end of the document
Error: 1: Extra content at the end of the document
```

The bug was reported [here](https://support.bioconductor.org/p/86554/)

**Comment by Wanvdphelys** [comment]
Thanks you very much.
Turns out that the error is caused by Ensembl server maintenance.

> Due to essential Data Centre maintenance, the Ensembl web service will be unavailable from 14:00 BST on Friday 26th August 2016 BST until 11:00 BST on Tuesday 30th August 2016.
