### ISSUE TITLE
error with data download

### ISSUE THREAD

**Issue by nightmoonshen** [BioinformaticsFMRP/TCGAbiolinks#175]
I got an error when downloading data by biolinks.

Code:   query.met <- GDCquery(project = "TCGA-GBM",legacy = TRUE,
                      data.category = "DNA methylation",
                      platform = "Illumina Human Methylation 450")

 Error:       Error in checkProjectInput(project) : 
         Please set a valid project argument from the column id above. Project TCGA-GBM was not found.
       In addition: Warning messages:
      1: Unnamed `col_types` should have the same length as `col_names`. Using smaller of the two. 
      2: In rbind(names(probs), probs_f) :
      number of columns of result is not a multiple of vector length (arg 1)
      3: Unknown or uninitialised column: 'project_id'. 
      4: Unknown or uninitialised column: 'project_id'. 

I was confused by this error because it occured after i copied the code from Reference Manual.

**Comment by tiagochst** [comment]
Which version do you have installed? I believe this is an old version.
Could you try installing the last version from github:
`devtools::install_github('BioinformaticsFMRP/TCGAbiolinks')`

**Comment by nightmoonshen** [comment]
I followed your instructions and tried again but it seemed no advance. I found the warnings like:
--------------------------------------
o GDCquery: Searching in GDC database
--------------------------------------
Genome of reference: hg19
Warning: 40 parsing failures.
row # A tibble: 5 x 5 col     row   col  expected     actual                                                        file expected   <int> <chr>     <chr>      <chr>                                                       <chr> actual 1     1  <NA> 8 columns 71 columns 'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv' file 2     2  <NA> 8 columns 71 columns 'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv' row 3     3  <NA> 8 columns 71 columns 'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv' col 4     4  <NA> 8 columns 71 columns 'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv' expected 5     5  <NA> 8 columns 71 columns 'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv'
... ................. ... .............................................................................................. ........ .............................................................................................. ...... .................. [... truncated]

**Comment by tiagochst** [comment]
What is the output from:
`package.version("TCGAbiolinks")`

**Comment by nightmoonshen** [comment]
Error in package.version("TCGAbiolinks") : 
  could not find function "package.version"

**Comment by tiagochst** [comment]
One of these two works? 
`Biobase::package.version("TCGAbiolinks") `
or 
`packageVersion("TCGAbiolinks")`

**Comment by nightmoonshen** [comment]
library(TCGAbiolinks)
> Biobase::package.version("TCGAbiolinks")
 "2.7.5"
> packageVersion("TCGAbiolinks")
‘2.7.5’

**Comment by tiagochst** [comment]
The version is right, but I don't have this bug. Did you restart R after installing the last version?

**Comment by nightmoonshen** [comment]
Yes, that's the reason！ Thank you very much for solving my problem
