### ISSUE TITLE
Error with GDCquery_Maf

### ISSUE THREAD

**Issue by gaiusjaugustus** [BioinformaticsFMRP/TCGAbiolinks#176]
Sadly, since the move to GDC, I haven't had much luck with the TCGAbiolinks package.  Mostly user error, I assumed.  But this one I'm hoping you can help me with.  Here's my latest issue:

Tried running:
`GDCquery_Maf("READ", pipelines = "mutect2") `

Also tried running for COAD, both gave similar errors:
--------------------------------------
o GDCquery: Searching in GDC database
--------------------------------------
Warning: 40 parsing failures.
row # A tibble: 5 x 4 col     row   col  expected     actual expected   <int> <chr>     <chr>      <chr> actual 1     1  <NA> 7 columns 71 columns row 2     2  <NA> 7 columns 71 columns col 3     3  <NA> 7 columns 71 columns expected 4     4  <NA> 7 columns 71 columns actual 5     5  <NA> 7 columns 71 columns
... ................. ... .................................. ........ .................................. ...... .................................. ... .................................. ... .................................. ........ .................................. ...... ..................................
See problems(...) for more details.

Error in UseMethod("conditionMessage") : 
  no applicable method for 'conditionMessage' applied to an object of class "data.frame"
In addition: Warning messages:
1: Unnamed `col_types` should have the same length as `col_names`. Using smaller of the two. 
2: Unknown or uninitialised column: 'project_id'. 
3: Unknown or uninitialised column: 'project_id'.

Additionally, running "COAD", gave me this message:
trying URL 'https://gdc-api.nci.nih.gov/data//bf1c53dc-79bb-43ae-88e4-23758853e5c6'
trying URL 'https://gdc-api.nci.nih.gov/data//bf1c53dc-79bb-43ae-88e4-23758853e5c6'
The data downloaded might be corrupted. We will download it again

Over and over again until I had to force stop the console.

Thanks in advance for any help.
Gaius

R 3.3.2
TCGAbiolinks_2.2.10

**Comment by tiagochst** [comment]
Hello,
The version you have is old and probably does not have the fix for this problem.

Please, could you update either using the Bioconductor version or the github:
`devtools::install_github('BioinformaticsFMRP/TCGAbiolinks')`

This should solve the problem.

Best regards, 
Tiago

**Comment by gaiusjaugustus** [comment]
Updating via devtools solved the problem.  Thanks.

Gaius
