### ISSUE TITLE
Parsing failures error

### ISSUE THREAD

**Issue by yesitsjess** [BioinformaticsFMRP/TCGAbiolinks#178]
Hello, just trying to access some mutation and RNA-seq data, but my old scripts are failing to even get project IDs.

`projects <- getGDCprojects()$project_id`
`Warning: 40 parsing failures.
row # A tibble: 5 x 5 col     row   col  expected     actual                                                        file expected   <int> <chr>     <chr>      <chr>                                                       <chr> actual 1     1  <NA> 7 columns 71 columns 'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv' file 2     2  <NA> 7 columns 71 columns 'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv' row 3     3  <NA> 7 columns 71 columns 'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv' col 4     4  <NA> 7 columns 71 columns 'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv' expected 5     5  <NA> 7 columns 71 columns 'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv'
... ................. ... .............................................................................................. ........ .............................................................................................. ...... .................. [... truncated]
Warning messages:
1: Unnamed `col_types` should have the same length as `col_names`. Using smaller of the two. 
2: In rbind(names(probs), probs_f) :
  number of columns of result is not a multiple of vector length (arg 1)
3: Unknown or uninitialised column: 'project_id'. 
4: Unknown or uninitialised column: 'project_id'. `

Other steps such as `maf <- GDCquery_Maf("LUAD", pipelines="muse")` also fail.

**Comment by tiagochst** [comment]
Hello, 
Could you please update the package with the following command

`devtools::install_github('BioinformaticsFMRP/TCGAbiolinks')`

**Comment by yesitsjess** [comment]
Has RMySQL always been required? I definitely managed to use this package in the past, it was very useful, but now installation fails since "libmysqlclient" isn't found. I'm not an administrator so there's not much I can do about that.

**Comment by tiagochst** [comment]
[GenomicFeatures](https://bioconductor.org/packages/release/bioc/html/GenomicFeatures.html) package is requiring RMySQL and is imported by several Bioconductor packages.
