### ISSUE TITLE
Extra content at the end of the document Error: 1: Extra content at the end of the document

### ISSUE THREAD

**Issue by chen1111111** [BioinformaticsFMRP/TCGAbiolinks#18]
I've encountered with some error when using GDCprepare function.

query.exp <- GDCquery(project = "TCGA-HNSC", 
legacy = TRUE,
data.category = "Gene expression",    
data.type = "Gene expression quantification",
file.type = "results",
platform = "Illumina HiSeq",
barcode = listSamples)

GDCdownload(query.exp)

hnsc.exp <- GDCprepare(query = query.exp, save = TRUE, save.filename = "Laryn.exp.rda")

The error
xtra content at the end of the document
Error: 1: Extra content at the end of the document
but
library(biomaRt)
ensembl <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")
There were no errors

**Comment by tiagochst** [comment]
Same as #17, it should be working now. The update was supposed to be over yesterday.

**Comment by chen1111111** [comment]
Thanks
