### ISSUE TITLE
GDCprepare() failure on TCGA-CHOL and TCGA-SARC

### ISSUE THREAD

**Issue by FarzanT** [BioinformaticsFMRP/TCGAbiolinks#185]
Hello,
I am trying to download and prepare "Gene Expression Quantification" using the following script:
```r
projects <- c("TCGA-SARC", "TCGA-CHOL")
plyr::alply(projects, 1, function(proj) {
    query <- GDCquery(
        project = proj,
        data.category = "Transcriptome Profiling",
        data.type = "Gene Expression Quantification",
        workflow.type = "HTSeq - Counts"
    )
    GDCdownload(query, files.per.chunk = 20)
    GDCprepare(
        query,
        save = T,
        save.filename = paste0("SummarizedExperiments/mRNA/", proj, "_GeneExpression.rdata")
    )
})
```
But I get the following error, which I think stems from the `GDCprepare` function as the files seem to download normally:
```r
 Error in fix.by(by.y, y) : 'by' must specify a uniquely valid column 
```
Is there any way to fix this issue? I have downloaded and prepared other projects such as "TCGA-ACC" etc. without issues but these two remain.
Thank you!

**Comment by tiagochst** [comment]
There was a problem in the subtype data.
