### ISSUE TITLE
Strange output in new_tumor_events column, table "follow_up"

### ISSUE THREAD

**Issue by lbeltrame** [BioinformaticsFMRP/TCGAbiolinks#188]
Example with the latest (from Bioconductor) TCGAbiolinks code:

```r
library(TCGAbiolinks)
query <- GDCquery(project = "TCGA-OV", data.category="Clinical", barcode=c("TCGA-13-0761"))
tmp <- GDCprepare_clinic(query2, clinical.info = "follow_up")
tmp$new_tumor_events
[1] "424RecurrenceImaging StudyNOYES" "YES424"
```
That `"YES424"` (and even more `"424RecurrenceImaging StudyNOYES"`) looks suspicious to me, looks like a parsing error of some sort (those combinations attached aren't in the XML file). This makes filtering for new tumor events complicated (because it's hard to tell what those mixed strings mean).

**Comment by tiagochst** [comment]
Each follow up can have more than one new turmos events. For that reason it is a list. You can retrive it using clinical.info = "new_tumor_event".

Unless we  replace tmp$new_tumor_events by another value, that's the weird output will happen.

```
library(TCGAbiolinks)
query <- GDCquery(project = "TCGA-OV", data.category="Clinical", barcode=c("TCGA-13-0761"))
GDCdownload(query)
tmp <- GDCprepare_clinic(query, clinical.info = "follow_up")
tmp$new_tumor_events
tmp2 <- GDCprepare_clinic(query, clinical.info = "new_tumor_event")
tmp2$new_tumor_events

```

![selection_016](https://user-images.githubusercontent.com/145529/35621367-3ddcf256-066b-11e8-9758-53dd9582d02a.png)

**Comment by lbeltrame** [comment]
The reason was to have a quick way to filter which barcodes have tumor events and which don't. Unfortunately the patient data is inconsistent with the follow up, so some barcodes with "NO" tumor events have in fact one (or more than one).

**Comment by tiagochst** [comment]
I'll check

**Comment by tiagochst** [comment]
OK, these clinical data are quite messy.

A NTE(new tumor event) can be added either in the follow ups sections(which can have several versions) or in the main patient section.

<img width="374" alt="screen shot 2018-02-02 at 11 01 22 am" src="https://user-images.githubusercontent.com/145529/35735662-b7544024-080c-11e8-93a7-7d555ffa2511.png">

For the moment, to get the barcodes you will have to consider the patient and follow up tables:

```
library(TCGAbiolinks)
query <- GDCquery(project = "TCGA-OV", data.category="Clinical")
GDCdownload(query)
patient <- GDCprepare_clinic(query, clinical.info = "patient")
# table(patient$has_new_tumor_events_information)
# > table(patient$has_new_tumor_events_information)
# NO   YES 
# 578   4
barcode_with_nte <- patient$bcr_patient_barcode[patient$has_new_tumor_events_information == "YES"]

followup <- GDCprepare_clinic(query, clinical.info = "follow_up")
followup$new_tumor_events
nte <- GDCprepare_clinic(query, clinical.info = "new_tumor_event")
barcodes_with_nte_in_followup <- followup$bcr_patient_barcode[!followup$new_tumor_events %in% c("NO","")]

barcode <- unique(c(barcodes_with_nte_in_followup,barcode_with_nte))

length(unique(nte$bcr_patient_barcode))
# 369

length(unique(barcode))
# 369

```

**Comment by tiagochst** [comment]
I improved the code to consider the follow up nte information. You will be able to do:

```
library(TCGAbiolinks)

query <- GDCquery(project = "TCGA-OV", data.category="Clinical")
GDCdownload(query)
patient <- GDCprepare_clinic(query, clinical.info = "patient")
# table(patient$has_new_tumor_events_information)
# > table(patient$has_new_tumor_events_information)
#  NO YES 
# 218 369 
barcode_with_nte <- patient$bcr_patient_barcode[patient$has_new_tumor_events_information == "YES"]

length(unique(nte$bcr_patient_barcode))
# 369

length(unique(barcode_with_nte))
# 369
```
