### ISSUE TITLE
new to TCGAbiolinks

### ISSUE THREAD

**Issue by arrayprofile** [BioinformaticsFMRP/TCGAbiolinks#189]
Hi, I am new to TCGAbiolinks, just installed the Development version of the package.

I am wondering how to know what are the possibles values for the arguments of GDCquery()? for example, I understand values for "project" can be obtained from getGDCprojects(); values for "data.category" can be obtained from getDataCategorySummary(). But what about "data.type", "workflow.type", "platform", "file.type", "sample.type", "experimental.strategy"? Where can I find information on the possible values for these arguments?

Also, is there a vignette for this package? and some example workflow of using this package? The original NAR pub has a supplemental materials with very good example workflow scripts, but they were already outdated.

Thank you very much!

**Comment by tiagochst** [comment]
Hello,

The most updated vignette can be found at: https://bioconductor.org/packages/devel/bioc/vignettes/TCGAbiolinks/inst/doc/query.html

There are some table with the possible values. 

In case you have any questions, do not hesitate to ask questions.

**Comment by arrayprofile** [comment]
Thank you.
