### ISSUE TITLE
Where could find geneInfo

### ISSUE THREAD

**Issue by huwenhuo** [BioinformaticsFMRP/TCGAbiolinks#19]
For example here:
dataNorm <- TCGAanalyze_Normalization(tabDF = dataBRCA, geneInfo =  geneInfo)

I just cann't where is the geneInfo come from. Thanks.

**Comment by torongs82** [comment]
Hi @huwenhuo thank you writing and @tiagochst pointing out.
We created geneInfo to use with TCGAanalyze_Normalization and allowing user to normalize mRNA transcripts and miRNA, using EDASeq package. You can take a look in our vignette. In particular you can run this example to update it:

require(biomaRt)
require(EDASeq)
data <- useMart(biomart="ensembl", dataset="hsapiens_gene_ensembl")
ensemblids <- getBM(attributes=c("ensembl_gene_id"), mart=data)
dataGene <- getGeneLengthAndGCContent(id=ensemblids$ensembl_gene_id[1:5], org="hsa")

Best,
Antonio.

**Comment by Heissluft** [comment]
hi, What to use in geneInfo for miRNAs ? Thanks @tiagochst
