### ISSUE TITLE
Display enriched genes in the clustered tabs

### ISSUE THREAD

**Issue by qalid7** [BioinformaticsFMRP/TCGAbiolinks#192]
Hi all

Simple question, but I failed to get a straight forward answer... 

How to access the genes (top hits) that are displayed under a process/tab in the output of TCGAvisualize_EAbarplot? 

From the example below, I see the output of TCGAanalyze_EAcomplete is a list for each ontology GO: category with multiple hits, however this doesn't really show the actual genes, rather the GO terms FDR etc... 

It does tell you ncommon=xx which makes me wonder that it should be straight forward to access those important genes under each GO term/tab, e.g. what are the 3 enriched 'sensory perception of chemical stimulus' genes here?
http://bioinformaticsfmrp.github.io/TCGAbiolinks/casestudy.html 
![image](https://user-images.githubusercontent.com/35524818/35969807-fa44a484-0cbf-11e8-9ec0-9fa1b0c8ef01.png)

Thanks a lot!

**Comment by qalid7** [comment]
I'm still looking for an answer, other R packages don't provide a good alternative!

**Comment by ehcw111** [comment]
I would like to know how to do this as well.
Thanks

**Comment by torongs82** [comment]
Dear @qalid7 and @ehcw111 thank you for your interest using TCGAbiolinks.

I have committed an update version of the TCGAvisualize_EA function to return a table with genes (top hits) in common with each GO or pathway. For example you now can run the following code:

```
library(devtools)
install_github("BioinformaticsFMRP/TCGAbiolinks/")

require(TCGAbiolinks)
dataDEGsFiltLevel <- TCGAbiolinks::dataDEGsFiltLevel
EAGenes <- get("EAGenes")
DAVID_BP_matrix <- TCGAbiolinks:::DAVID_BP_matrix
RegulonList <- rownames(dataDEGsFiltLevel)
ResBP <- TCGAbiolinks:::TCGAanalyze_EA(GeneName="DEA genes Normal Vs Tumor",
                                       RegulonList = RegulonList,
                                       TableEnrichment = DAVID_BP_matrix,
                                       EAGenes = EAGenes,
                                       GOtype = "DavidBP",
                                       FDRThresh = 0.01,
                                       GeneSymbolsTable = TRUE)

kable(ResBP[1:3,])
```

|    |Pathway                                            | GenesInPathway| Pvalue| FDR| CommonGenesPathway| PercentPathway| PercentRegulon|CommonGeneSymbols                                                                                        |
|:---|:--------------------------------------------------|--------------:|------:|---:|------------------:|--------------:|--------------:|:--------------------------------------------------------------------------------------------------------|
|634 |GO:0007606~sensory perception of chemical stimulus |            380|      0|   0|                  2|      0.5263158|      0.0548095|NCAM2;PDE1C                                                                                              |
|635 |GO:0007608~sensory perception of smell             |            377|      0|   0|                  2|      0.5305040|      0.0548095|NCAM2;PDE1C                                                                                              |
|631 |GO:0007600~sensory perception                      |            487|      0|   0|                 19|      3.9014374|      0.5206906|NPY1R;NR2F6;RBP4;RGS16;NDN;MYO9A;NCAM2;NPHP3;NMU;RDH5;NDP;MERTK;PAX2;RAB3A;MYO3B;PDE1C;PRR4;PENK;MYCBPAP |




Please let me know if this worked for you, and if you need anything else you can write us back here or open another issue.

Hoping this helped.
Best,

Antonio.

**Comment by qalid7** [comment]
@torongs82 wonderful work thank you so much!

**Comment by beyondpie** [comment]
Hi there!  
how the DAVID_BP_matrix is generated?  I see this is from sysdata in the package, but in this way, does this mean that the GO analysis might be old since the data would be old? 
Thanks!
