### ISSUE TITLE
error in loading library

### ISSUE THREAD

**Issue by kkleinoros** [BioinformaticsFMRP/TCGAbiolinks#20]
> library(TCGAbiolinks)
Error in namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,  : 
  lazy-load database 'C:/Program Files/R/R-3.3.1/library/stringr/R/stringr.rdb' is corrupt
In addition: Warning messages:
1: In namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,  :
  restarting interrupted promise evaluation
2: In namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,  :
  internal error -3 in R_decompress1
Error: package or namespace load failed for ‘TCGAbiolinks’

**Comment by tiagochst** [comment]
Please reinstall stringr package. It is corrupted.
`install.packages("stringr")` might solve your problem
