### ISSUE TITLE
prediction by neural network

### ISSUE THREAD

**Issue by mahtab96** [BioinformaticsFMRP/TCGAbiolinks#201]
hi everybody
i want to know if there is a good package in R for neural network for prediction.
please guide me
thanks

**Comment by tiagochst** [comment]
I read a blog recently with a post for several R packages, but I could not find the link. I would take a look at KERAS (https://keras.rstudio.com/index.html)

A book that uses it was recently published https://www.manning.com/books/deep-learning-with-r There are some HTML notebooks at https://github.com/jjallaire/deep-learning-with-r-notebooks
