### ISSUE TITLE
Released version (Using TCGAbiolinks 2.5.9.) GDCquery not working => always use dev version?

### ISSUE THREAD

**Issue by Heydt** [BioinformaticsFMRP/TCGAbiolinks#206]
Hi

I recently discovered TCGAbiolinks and gave it a try. Installed version 2.5.9 using bioclite on R 3.4.3, and the GDCquery examples from the help page throw up this error:

```
Error in checkProjectInput(project) : Please set a valid project argument from the column id above. Project TCGA-BRCA was not found.
In addition: Warning messages:
1: Unnamed col_types should have the same length as `col_names`. Using smaller of the two.
2: In rbind(names(probs), probs_f) : number of columns of result is not a multiple of vector length (arg 1)
3: Unknown or uninitialised column: 'project_id'.
4: Unknown or uninitialised column: 'project_id'.
```
I found this post with the same issue: https://support.bioconductor.org/p/102119/

As in the accepted answer, I was able to fix the problem by installing the developer version.

However, I'm not well versed in versions and environments, and i'd like to install TCGAbiolinks on a server, making sure it works just like I expect it does, based on how it works on my own pc.
I've got version 2.7.21 right now. Can I make sure to install the same version on the server? 

Is it also recommended to use the developer version? I see no other way since the released version is throwing errors, but I thought it was a bit strange, never had to do this before.

**Comment by tiagochst** [comment]
Hello, 

Sorry I missed this issue. Is it also recommended to use the developer version? Yes, unfortunately the Bioconductor version sometimes is not the most updated even though we push the changes often.
Normally the github version is supposed to have more bug fixes.

You can install an specific commited version using the commit SHA-1 checksum.

devtools::install_github("BioinformaticsFMRP/TCGAbiolinks",ref = "541e842335456e026d1eeffcf4bca0e18a750223")

You can get the SHA-1 checksum from the history.
https://github.com/BioinformaticsFMRP/TCGAbiolinks/commits/master
