### ISSUE TITLE
Cannot move raw methylation idat files to local folder

### ISSUE THREAD

**Issue by brnhuang** [BioinformaticsFMRP/TCGAbiolinks#207]
Hello,

I am using TCGAbiolinks version 2.7.21 to download raw methylation idat files. I have been running the following code (using the guide from https://bioconductor.org/packages/3.7/bioc/vignettes/TCGAbiolinks/inst/doc/download_prepare.html) to download some sample data, but am having issues with the final line that moves the individual idat files to my local folder. It is saying that 'move' is not an exported object in TCGAbiolinks. See code below:

````
query.met <- GDCquery(project = "TCGA-PAAD",
                  data.category = "Raw microarray data",
                  data.type = "Raw intensities", 
                  experimental.strategy = "Methylation array", 
                  legacy = TRUE,
                  file.type = ".idat",
                  platform = "Illumina Human Methylation 450",
                  barcode = c("TCGA-2J-AAB1","TCGA-2J-AAB4","TCGA-2J-AAB6"))
match.file.cases <- getResults(query.met,cols=c("cases","file_name"))
head(match.file.cases)
tryCatch(GDCdownload(query.met, method = "api",chunks.per.download = 20),
         error = function(e) GDCdownload(query.met, method = "client"))

# This will create a map between idat file name, cases and project
readr::write_tsv(match.file.cases, path =  "idat_filename_case.txt")

# code to move all files to local folder
for(file in dir(".",pattern = ".idat", recursive = T)){
  TCGAbiolinks::move(file,basename(file))
}
Error: 'move' is not an exported object from 'namespace:TCGAbiolinks'
````

Any help would be appreciated. Thank you!

**Comment by tiagochst** [comment]
Hello, 

the move function is internal.  you can access internal functions with tree : `TCGAbiolinks:::move(file,basename(file))`

Sorry for the delay.

**Comment by brnhuang** [comment]
Thanks so much for your help. The code works now but I am now encountering another error:

````
Error in TCGAbiolinks:::move(file, basename(file)) : 
  I could not find the file: GDCdata/TCGA-PAAD/legacy/Raw_microarray_data/Raw_intensities/12b66271-905e-4b58-b450-6bb3e8fd4449/logs/9993943049_R03C02_Grn.idat.parcel
````
It looks like the code moves the first .idat file to the local folder and then immediately deletes the original folder ("12b66271-905e-4b58-b450-6bb3e8fd4449") holding that .idat file before moving the respective .idat.parcel file in the "logs" folder. I believe the "logs" folder with the .idat.parcel file is something created by TCGAbiolinks, right? When I download raw files directly from the GDC legacy data archive, it doesn't come with a "logs" folder.

In any case, I just modified the code so that it only pulls the .idat files, which prevents the error of looking for .idat.parcel files that are subsequently deleted after pulling the .idat file.
````
idat.files.all  <- list.files(path=".", pattern=".idat", recursive=T)
idat.files.no  <- list.files(path=".", pattern=".idat.parcel", recursive=T)

#get list of files that does not include the ".idat.parcel" files
idat.files.yes <- setdiff(dat.files.all, dat.files.no)

for(file in idat.files.yes){
  TCGAbiolinks:::move(file,basename(file))
}
````

**Comment by tiagochst** [comment]
The "logs" folder with the .idat.parcel file is not created by TCGAbiolinks. 
I'm trying to remember how you can get that data from GDC website, but I cannot remember. 
Also I believe  updated TCGAbiolinks to remove those files.

This is how I was moving the data in the GUI: https://github.com/BioinformaticsFMRP/TCGAbiolinksGUI/blob/2d4e1e93c5bcfd8ee98ef7757f19887996c38112/inst/app/server/getmolecular.R#L306-L312

But I'm quite sure it does not considere the idat.parcel files and the should not be erased after the download.

**Comment by hcy987** [comment]
It seems that TCGAbiolinks downloads both .idat and .idat.pracel files at the same time. So I deleted .pracel files at first, then run the "move" command.
