### ISSUE TITLE
Getting list of cases

### ISSUE THREAD

**Issue by nservant** [BioinformaticsFMRP/TCGAbiolinks#210]
Hi,
I have a simple question regarding the list of available cases for a tumor type.
I'm looking at SKCM data, both expression and mutation. 
According to CBioPortal, 287 samples have both information.

However, using TCGAbiolinks, I have much more mutation profiles.
How is it possible ? Thanks for your help.
Nicolas
```

query.exp.hg38 <- GDCquery(project="TCGA-SKCM", data.category="Transcriptome Profiling",
                           data.type="Gene Expression Quantification", workflow.type="HTSeq - Counts")
GDCdownload(query.exp.hg38)
exprs.cases <- substr(getResults(query.exp.hg38, cols = "cases"), 1, 12)
length(exprs.cases)
##472 as expected

## Get mutation data                                                                                    
query.mut.hg38 <- GDCquery("TCGA-SKCM", data.category = "Simple Nucleotide Variation",
                  data.type = "Masked Somatic Mutation", workflow.type = "MuTect2 Variant Aggregation a\
nd Masking")
GDCdownload(query.mut.hg38)
mut.cases <- substr(unlist(strsplit(unlist(getResults(query.mut.hg38, cols = "cases")), ",")), 1, 12)
length(mut.cases)
##942 - I guess there are also the normal samples ?

length(intersect(exprs.cases, mut.cases))
##468

```

**Comment by tiagochst** [comment]
Both the GDC and Cbioportal seem to have the same data for gene expression 472 samples, but the difference are in the MAF file (GDC has 470 samples vs 368 samples in cBioportal). Unfortunately, I'm not sure how the MAF files from Cbioportal were processed. 


<img width="954" alt="screen shot 2018-04-19 at 5 26 39 pm" src="https://user-images.githubusercontent.com/145529/39001567-dd1ac71c-43f6-11e8-9963-0300923af721.png">
<img width="854" alt="screen shot 2018-04-19 at 5 26 45 pm" src="https://user-images.githubusercontent.com/145529/39001566-dcc8e488-43f6-11e8-877c-6a8b74b407a7.png">
<img width="981" alt="screen shot 2018-04-19 at 5 26 08 pm" src="https://user-images.githubusercontent.com/145529/39001568-dd47bd44-43f6-11e8-8ce8-0042a92af791.png">

**Comment by nservant** [comment]
Thanks for your feedback.
Anything I can check ? or people I can contact on the TCGA side ?

**Comment by nservant** [comment]
One more question.
When I do

`mut.cases <- substr(unlist(strsplit(unlist(getResults(query.mut.hg38, cols = "cases")), ",")), 1, 12)`
I have 962 cases. How can I get the 368 expected cases ?
Thanks

**Comment by tiagochst** [comment]
```
query.mut.hg38 <- GDCquery("TCGA-SKCM", data.category = "Simple Nucleotide Variation",
                           data.type = "Masked Somatic Mutation", workflow.type = "MuTect2 Variant Aggregation and Masking")

mut.cases <- unique(substr(unlist(strsplit(unlist(getResults(query.mut.hg38, cols = "cases")), ",")), 1, 12))
```
                           
If you get only the unique values you will have 470

**Comment by asmagen** [comment]
How do you get the mutated genes per sample?
