### ISSUE TITLE
Error running GDCquery manual BRCA example

### ISSUE THREAD

**Issue by asmagen** [BioinformaticsFMRP/TCGAbiolinks#219]
I get the following error 'Error: Invalid column index: 8' and there's no GDC maintenance going on now as far as I see.

Is there another possible cause for this error?

Thanks

`--------------------------------------
o GDCquery: Searching in GDC database
--------------------------------------
Warning: 40 parsing failures.
row col  expected     actual                                                        file
  1  -- 7 columns 71 columns 'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv'
  2  -- 7 columns 71 columns 'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv'
  3  -- 7 columns 71 columns 'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv'
  4  -- 7 columns 71 columns 'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv'
  5  -- 7 columns 71 columns 'https://gdc-api.nci.nih.gov/projects?size=1000&format=tsv'
... ... ......... .......... ...........................................................
See problems(...) for more details.

Error: Invalid column index: 8
In addition: Warning messages:
1: Unnamed `col_types` should have the same length as `col_names`. Using smaller of the two. 
2: Unknown or uninitialised column: 'project_id'. 
3: Unknown or uninitialised column: 'project_id'. `

**Comment by tiagochst** [comment]
Please,  could you update to the last version of the package?
`devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")`
