### ISSUE TITLE
miRNA DEA

### ISSUE THREAD

**Issue by chen1111111** [BioinformaticsFMRP/TCGAbiolinks#22]
How to perform miRNA differential expression analysis ，
Please help and give an example，

Thanks very much.****

**Comment by claudiacava** [comment]
Hi Chen, 
could you test if it works for miRNA differential expression analysis?

tumour<-c("TCGA-BH-A0DL-01A-11R-A115-07","TCGA-AO-A03P-01A-11R-A00Z-07")
normal<-c("TCGA-BH-A209-11A-42R-A157-07","TCGA-E9-A1N4-11A-33R-A14M-07") 

data.type <- c("miRNA Expression Quantification")
for(i in data.type){
  print(i)
  query <- GDCquery(project = "TCGA-BRCA",
                    data.category = "Transcriptome Profiling",
                    data.type = i,
                    workflow.type = "BCGSC miRNA Profiling",
                    barcode = c(tumour,normal))
  GDCdownload(query)
  dataAssy <- GDCprepare(query)}

dataFilt <- TCGAanalyze_Filtering(tabDF = dataAssy,
                                  method = "quantile", 
                                  qnt.cut =  0.25)  
colnames(dataFilt) <- gsub("normalized_count_","",colnames(dataFilt))
dataDEGs <- TCGAanalyze_DEA(mat1 = dataFilt[,normal], 
                            mat2 = dataFilt[,tumour], 
                            Cond1type = "Normal",
                            Cond2type = "Tumor",logFC.cut=1,fdr.cut = 0.01) 


Thanks.

**Comment by YangZX88** [comment]
Hi, question with using packagesTCGAbiolinks, error like this:
1) when I use function GDCquery_Maf(), it appears: cannot open URL 'https://gdc-api.nci.nih.gov/data//abbe72a5-cb39-48e4-8df5-5fd2349f2bb2'
2) using TCGAquery_investigate(): could not find function "TCGAquery_investigate"
I install the packages with order: biocLite("TCGAbiolinks"), is there any other packages need to install?

very thanks !
Yang

**Comment by YangZX88** [comment]
Sorry, I paste the issue in the wrong page.

**Comment by tiagochst** [comment]
Hi,

TCGAquery_investigate was removed from the package.
GDCquery_Maf was updated. It should be working now.

Best regards,
Tiago
