### ISSUE TITLE
Urgent: issue with GDCprepare_clinic

### ISSUE THREAD

**Issue by adilosadilos** [BioinformaticsFMRP/TCGAbiolinks#229]
(TCGAbiolinks version 2.9.1).
When I run the code below I got an error.  Please see the code bellow

query_ =
    GDCquery(
      project       = "TCGA-GBM", 
      data.category = "Clinical"
    )
  
  GDCdownload(
    query           = query_, 
    method          = "api", 
    files.per.chunk = 5
  )
  output1 = GDCprepare_clinic(query = query_, clinical.info = "patient")
  
 |==============================                                                |  39%
 Error in doc_parse_file(con, encoding = encoding, as_html = as_html, options = options) : 
  Start tag expected, '<' not found [4]

**Comment by tiagochst** [comment]
Hello, 

could you please update the package with the last version from github? This was fixed some days ago.
You can do it with the following R command.
`devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")`

Thanks!

**Comment by guozihuaa** [comment]
hi dear @tiagochst 

I got the same problem when use the last version

 clinical <- GDCprepare_clinic(query, clinical.info = "patient")
  |===============                                                                |  19%Error in doc_parse_file(con, encoding = encoding, as_html = as_html, options = options) : 
  Start tag expected, '<' not found [4]

> packageVersion(pkg = "TCGAbiolinks", lib.loc="~/R/win-library/3.5")
[1] ‘2.9.2’
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

**Comment by adilosadilos** [comment]
Add file.type = 'xml'

**Comment by guozihuaa** [comment]
@adilosadilos  thanks it works
