### ISSUE TITLE
Clinical data download issue: Peer's Certificate has expired.

### ISSUE THREAD

**Issue by asmagen** [BioinformaticsFMRP/TCGAbiolinks#230]
Hello,

What's to do with:
dataClin <- GDCquery_clinic(project = "TCGA-BRCA","clinical") 
Error in curl::curl_fetch_memory(url, handle = handle) : 

Error message
  Peer's Certificate has expired.

Thanks

**Comment by tiagochst** [comment]
Please, could you update the package with the last github version ? I was able to run the code with the last version. GDC changed all urls the last week and it broke the access.

You can update with the following R command:
`devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")`

**Comment by asmagen** [comment]
It works now. Thanks
