### ISSUE TITLE
Error opening archive: Unrecognized archive format

### ISSUE THREAD

**Issue by samyyhe** [BioinformaticsFMRP/TCGAbiolinks#232]
**My query was:**
expre <- GDCquery(project = "TCGA-GBM",
                  legacy = TRUE,
                  data.category = "Gene expression",
                  data.type = "Gene expression quantification",
                  platform = c("AgilentG4502A_07_2" , "AgilentG4502A_07_1" ),
                  sample.type = c("Primary solid Tumor","Solid Tissue Normal")
)
GDCdownload(expre)
rawData_1=GDCprepare(expre, 
                save.filename = "Brain_GBM_&NL_Exp.rda",summarizedExperiment=TRUE)

**The output and error information was:**
--------------------------------------
o GDCquery: Searching in GDC database
--------------------------------------
Genome of reference: hg19
--------------------------------------------
oo Accessing GDC. This might take a while...
--------------------------------------------
ooo Project: TCGA-GBM
--------------------
oo Filtering results
--------------------
ooo By platform
ooo By sample.type
----------------
oo Checking data
----------------
ooo Check if there are duplicated cases
ooo Check if there results for the query
-------------------
o Preparing output
-------------------
> GDCdownload(expre)
Downloading data for project TCGA-GBM
GDCdownload will download 605 files. A total of 190.691852 MB
Downloading as: Tue_Jun_19_20_39_17_2018.tar.gz
  |=======================================================================================================================| 100%
tar.exe: Error opening archive: Unrecognized archive format
Download completed
> rawData_1=GDCprepare(expre, 
+                      save.filename = "Brain_GBM_&NL_Exp.rda",summarizedExperiment=TRUE)
Error in GDCprepare(expre, save.filename = "Brain_GBM_&NL_Exp.rda", summarizedExperiment = TRUE) : 
  I couldn't find all the files from the query. Please check if the directory parameter right or GDCdownload downloaded the samples.

**Comment by tiagochst** [comment]
I need to check the prepare code for these platforms, it is not working.
Meanwhile, I would say the file downloaded was corrupted. Could you rerun GDCdownload with files.per.chunk argument set.` GDCdownload(expre,files.per.chunk = 50)`

<img width="797" alt="screen shot 2018-06-20 at 8 39 27 am" src="https://user-images.githubusercontent.com/145529/41656174-785ea376-7465-11e8-9c28-0c1c89a7c1af.png">

**Comment by samyyhe** [comment]
Hi, 
I rerun the GDCdownload code as you suggested. The output was like:

![jnuozm p ny1elqg avbk_p](https://user-images.githubusercontent.com/13511411/41678144-e910f9fa-748f-11e8-9a1a-73a5909dbe1a.png)

**Comment by samyyhe** [comment]
I figured it out: I should add the argument "data.type = "Gene expression quantification"" in the GDCquery.
![x1e20df x4ll2 4svo9k_ c](https://user-images.githubusercontent.com/13511411/41680107-f22e3a92-7495-11e8-8ca4-f2ba1520056a.png)
