### ISSUE TITLE
Errors for downloading RNA-Seq HTSeq count tables

### ISSUE THREAD

**Issue by jiajiayb** [BioinformaticsFMRP/TCGAbiolinks#235]
Hi, I am trying to download many HTSeq count tables from various tumor type. By doing so in TCGAbiolinks, some of the files can be downloaded successfully, but many more encounter the following errors, for example:
2018-06-22 06:30:39,068: ERROR: Unable to download 52b73cc5-ea14-441f-90f0-311dc1903e28: Unable to connect to API: ([Errno bad handshake] (104, 'ECONNRESET')). Is this url correct: 'https://gdc-api.nci.nih.gov/data/'? Is there a connection to the API? Is the server running?
2018-06-22 06:30:41,181: ERROR: Max retries exceeded.

Do you by chance to know what are the issues here? Thanks a lot!

**Comment by tiagochst** [comment]
Could you update the package with github last version. GDC updated their API recently.
Command: `devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")`

**Comment by jiajiayb** [comment]
Thank you for your reply. Actually I first updated the package yesterday and then start the downloading. When I try to update the package again, it says: 
Skipping install of 'TCGAbiolinks' from a github remote, the SHA1 (df5fe17a) has not changed since last install.
  Use `force = TRUE` to force installation
So I think I am using the latest version. Any other clue? Thanks a lot!

**Comment by tiagochst** [comment]
Could you send me the code?

**Comment by jiajiayb** [comment]
Sure!
The R code is **download_gdc_htseqcount.R**:
.libPaths('~/R/x86_64-pc-linux-gnu-library/3.3')
args<-commandArgs(T)
project<-as.character(args[1]) #TCGA-BRCA
library(TCGAbiolinks)
query <- GDCquery(project = project,
                  data.category = "Transcriptome Profiling",
                  data.type = "Gene Expression Quantification", 
                  workflow.type = "HTSeq - Counts")
query$results[[1]]<-subset(query$results[[1]], tissue.definition=='Primary solid Tumor')
GDCdownload(query, method='client')
results<-query$results[[1]]
output<-results[, c('file_name', 'file_id','cases')]
write.table(output, paste(project, '.HTSeqCount.convertor.txt', sep=''), quote=F, row.names=F, sep='\t')

The bash script for submitting this R code is: 
for i in $(cat TCGA_CancerID.txt); do Rscript download_gdc_htseqcount.R $i; done
in which TCGA_CancerID.txt list several cancer project id, like TCGA-BRCA and many more.

**Comment by jiajiayb** [comment]
I am trying to download all available htseq counts for each selected cancer type.

**Comment by tiagochst** [comment]
The 'https://gdc-api.nci.nih.gov/data/' is old. it moved to https://api.gdc.cancer.gov/data. I'll check your code.

**Comment by tiagochst** [comment]
could you test to download the data like this:
library(TCGAbiolinks)
```
query <- GDCquery(project = "TCGA-ACC",
                  data.category = "Transcriptome Profiling",
                  sample.type = 'Primary solid Tumor',
                  data.type = "Gene Expression Quantification",
                  workflow.type = "HTSeq - Counts")
GDCdownload(query, method='api',files.per.chunk = 10)

```

**Comment by tiagochst** [comment]
Also, I saw you are using client methods. Can you erase the gdc-client file in the same folder?
I should have been updated after the API was changed.

**Comment by jiajiayb** [comment]
Since gdc-client was installed in our cluster root directory (python2.7.3) not in the same folder, could I ask what should I change here for not using the client? Thanks!

**Comment by jiajiayb** [comment]
Thanks! I am using your revised code and see if there is any error. I will be away for a few hours and get back to you later. Thank you so much for your help 👍

**Comment by jiajiayb** [comment]
just checked, so far is perfect :) Thanks a lot!
