### ISSUE TITLE
SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by ycl6** [BioinformaticsFMRP/TCGAbiolinks#239]
Hi, I encountered SSL certificate problem when executing `GDCquery_clinic()`

``` 
GDCquery_clinic("TCGA-BRCA", "clinical", save.csv = FALSE)
```

> Error in curl::curl_fetch_memory(url, handle = handle) :
>   SSL certificate problem: certificate has expired

**Comment by tiagochst** [comment]
Hello, 

GDC changed their API last week. Could you update the package with the last version.
This should solve the problem.
You can install the package from gitHub with:
`devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")`

**Comment by ConnorJPSmith** [comment]
@tiagochst Do you know if this build is able to download files? I keep getting the following error when I try to download a file:

`<simpleWarning in file.create(to[okay]): cannot create file 'GDCdata/TCGA-LAML/harmonized/Simple_Nucleotide_Variation/Masked_Somatic_Mutation/27f42413-6d8f-401f-9d07-d019def8939e/TCGA.LAML.mutect.27f42413-6d8f-401f-9d07-d019def8939e.DR-10.0.somatic.maf.gz', reason 'No such file or directory'>`

**Comment by tiagochst** [comment]
@ConnorJPSmith Are you using Windows ? If so, there is a limit of character (256) for file paths.
I believe that is the reason.

**Comment by ConnorJPSmith** [comment]
Yes, that was it. Thanks!

**Comment by ycl6** [comment]
@tiagochst Thanks, after updating to the latest version the problem is now solved.
