### ISSUE TITLE
How to find patient sample.type in TCGA-PRAD  clinical data?

### ISSUE THREAD

**Issue by Heissluft** [BioinformaticsFMRP/TCGAbiolinks#241]
@tiagochst @torongs82 
Hi, I downloaded clinical- patient data for TCGA-PRAD. 
PROBLEM The bcr_patient_barcode contains sample identifier as "TCGA-HC-A6AP", while in miRNA data contains "TCGA-HC-A6AP**-01A**" The last 3 digits indicates sample.type which is missing in clinical data. How to know the sample type in "cli_patient" file as below
For example: 01 - Primary Solid Tumor - TP
WHY? I would like to link patient metadata with miRNA seq data to feed into edgeR.

**Comment by tiagochst** [comment]
In GDC  we have these two types of data:

**Clinical data:** Available clinical information for each participant (may include demographic information, treatment information, survival data, etc)
**Biospecimen data:** Information on how samples from each participant were processed by the Biospecimen Core Resource Center (BCR)

The clinical data is always linked to the participant (patient identifier) which are represented by the first 12 character (i.e. "TCGA-HC-A6AP" ), which means the clinical data is the same for all the patient samples  (TCGA-HC-A6AP-01, TCGA-HC-A6AP-02, etc). Of course this clinical data is updated over the time, the patient might have new treatments etc, which events can be found in several XML files.
Normally GDC has the "indexed version" which is an updated version of the clinical data.

Briefly, you can use the TCGA-HC-A6AP clinical data to TCGA-HC-A6AP-01 sample.
