### ISSUE TITLE
Add option to skip files with md5sum error

### ISSUE THREAD

**Issue by averissimo** [BioinformaticsFMRP/TCGAbiolinks#246]
Some data from TCGA is corrupt, for example the xml in [029adc7c-ebb9-401a-8262-21a0c68d2bf4](https://portal.gdc.cancer.gov/files/029adc7c-ebb9-401a-8262-21a0c68d2bf4) is not complete.

Would be nice to skip these files, giving a warning.

**Comment by tiagochst** [comment]
@averissimo Sorry, I personally don't like the idea to let users download corrupted data. If the data is corrupted in the database it should be fixed there.

But, if you download the XML file, it actually not corrupted. So I believe when you say corrupted it actually means the GDC parsing was not correct and the indexed clinical data is not the one in the XML files.

I reported the case to GDC, I believe this should be fixed soon. Also, there are some inconsistencies in the Clinical data compared to the XML. It might be worthy they check it.

```
query <- GDCquery(project = "TCGA-BRCA", 
                  data.category = "Clinical", 
                  file.type = "xml")
GDCdownload(query)
clinical <- GDCprepare_clinic(query, clinical.info = "patient")
```

<img width="1335" alt="screen shot 2018-07-18 at 10 19 27 am" src="https://user-images.githubusercontent.com/145529/42884186-14ac8f3a-8a74-11e8-83f1-adbdc31b7c08.png">

**Comment by averissimo** [comment]
I understand your reluctance and as such I'm closing the issue, I'm retrieving the data from the legacy, as that was the option that GDC gave me after aknowledging that the XML was corrupted. *(opened a ticket there before this issue, as GDC is the source of the problem, not TCGAbiolinks)*.

When I mean it is corrupted is that it is cut short, and therefore an invalid XML that TCGAbiolinks fails to parse.

The code to replicate fail is the following:

```
  library(TCGAbiolinks)
  project <- 'TCGA-BRCA'
  
  query <- list()

  # Prepare R object with data
  gdc <- list()

  #
  query$biospecimen <- GDCquery(project       = project,
                                data.category = "Biospecimen",
                                data.type     = 'Biospecimen Supplement',
                                file.type     = "xml")
  #
  GDCdownload(query$biospecimen, method = 'api')
  #
  gdc$bio.protocol  <- GDCprepare_clinic(query$biospecimen, clinical.info = 'protocol')
```

![image](https://user-images.githubusercontent.com/211358/42977433-0c6d19d8-8bbf-11e8-982c-8d79c2ad7798.png)
