### ISSUE TITLE
GDCprepare ERROR: Error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by AteeqMKhaliq** [BioinformaticsFMRP/TCGAbiolinks#250]
Hi Tiago,

While downloading Raw counts of PAAD from TCGA i am finding error in GDCprepare step. 
I have updated the package as well but the error crops up,
`devtools::install_github("Bioconductor-mirror/biomaRt")
devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")`
and the error is 
`exp.hg38 <- GDCprepare(query = query, save = TRUE, save.filename = "STAD_PAAD.rda")`

```
> |=====================================================================================| 100%
> Starting to add information to samples
>  => Add clinical information to samples
> Add FFPE information. More information at: 
> => https://cancergenome.nih.gov/cancersselected/biospeccriteria 
> => http://gdac.broadinstitute.org/runs/sampleReports/latest/FPPP_FFPE_Cases.html
>  => Adding subtype information to samples
> paad subtype information from:doi:10.1016/j.ccell.2017.07.007
> Error: $ operator is invalid for atomic vectors
```
`> sessio`nInfo() R version 3.5.0 (2018-04-23) Platform: x86_64-redhat-linux-gnu (64-bit) Running under: CentOS Linux 7 (Core)  Matrix products: default BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so  locale:  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8         [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8     [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               [10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C         attached base packages: [1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base       other attached packages:  [1] TCGAbiolinks_2.9.3         SummarizedExperiment_1.6.5 DelayedArray_0.2.7          [4] matrixStats_0.53.1         Biobase_2.36.2             GenomicRanges_1.28.6        [7] GenomeInfoDb_1.12.3        IRanges_2.10.5             S4Vectors_0.14.7           [10] BiocGenerics_0.22.1         loaded via a namespace (and not attached):   [1] backports_1.1.2             circlize_0.4.4              aroma.light_3.6.0             [4] plyr_1.8.4                  selectr_0.4-1               ConsensusClusterPlus_1.40.0   [7] lazyeval_0.2.1              splines_3.5.0               BiocParallel_1.10.1          [10] ggplot2_3.0.0               sva_3.24.4                  digest_0.6.15                [13] foreach_1.4.4               BiocInstaller_1.26.1        viridis_0.5.1                [16] magrittr_1.5                memoise_1.1.0               cluster_2.0.7-1              [19] doParallel_1.0.11           limma_3.32.10               ComplexHeatmap_1.14.0        [22] Biostrings_2.44.2           readr_1.1.1                 annotate_1.54.0              [25] R.utils_2.6.0               colorspace_1.3-2            blob_1.1.1                   [28] rvest_0.3.2                 ggrepel_0.8.0               dplyr_0.7.6                  [31] RCurl_1.95-4.10             jsonlite_1.5                genefilter_1.58.1            [34] bindr_0.1.1                 survival_2.42-4             zoo_1.8-3                    [37] iterators_1.0.9             glue_1.2.0                  survminer_0.4.3              [40] gtable_0.2.0                zlibbioc_1.22.0             XVector_0.16.0               [43] GetoptLong_0.1.7            kernlab_0.9-26              shape_1.4.4                  [46] prabclus_2.2-6              DEoptimR_1.0-8              scales_0.5.0                 [49] DESeq_1.28.0                mvtnorm_1.0-8               DBI_1.0.0                    [52] edgeR_3.18.1                ggthemes_4.0.0              Rcpp_0.12.17                 [55] viridisLite_0.3.0           xtable_1.8-2                cmprsk_2.2-7                 [58] bit_1.1-14                  matlab_1.0.2                mclust_5.4.1                 [61] km.ci_0.5-2                 httr_1.3.1                  RColorBrewer_1.1-2           [64] fpc_2.1-11                  modeltools_0.2-21           pkgconfig_2.0.1              [67] XML_3.98-1.13               R.methodsS3_1.7.1           flexmix_2.3-14               [70] nnet_7.3-12                 locfit_1.5-9.1              tidyselect_0.2.4             [73] rlang_0.2.1                 AnnotationDbi_1.38.2        munsell_0.5.0                [76] tools_3.5.0                 downloader_0.4              RSQLite_2.1.1                [79] devtools_1.13.6             broom_0.5.0                 stringr_1.3.1                [82] yaml_2.1.19                 knitr_1.20                  bit64_0.9-7                  [85] robustbase_0.93-1           survMisc_0.5.5              purrr_0.2.5                  [88] dendextend_1.8.0            bindrcpp_0.2.2              EDASeq_2.10.0                [91] nlme_3.1-137                whisker_0.3-2               R.oo_1.22.0                  [94] xml2_1.2.0                  biomaRt_2.32.1              compiler_3.5.0               [97] curl_3.2                    tibble_1.4.2                geneplotter_1.54.0          [100] stringi_1.2.3               GenomicFeatures_1.28.5      lattice_0.20-35             [103] trimcluster_0.1-2           Matrix_1.2-14               KMsurv_0.1-5                [106] pillar_1.2.3                GlobalOptions_0.1.0         data.table_1.11.4           [109] bitops_1.0-6                rtracklayer_1.36.6          R6_2.2.2                    [112] latticeExtra_0.6-28         hwriter_1.3.2               ShortRead_1.34.2            [115] gridExtra_2.3               codetools_0.2-15            MASS_7.3-50                 [118] assertthat_0.2.0            rjson_0.2.20                withr_2.1.2                 [121] GenomicAlignments_1.12.2    Rsamtools_1.28.0            GenomeInfoDbData_0.99.0     [124] diptest_0.75-7              mgcv_1.8-24                 hms_0.4.2                   [127] grid_3.5.0                  tidyr_0.8.1                 class_7.3-14                [130] git2r_0.21.0                ggpubr_0.1.7``

Thanks a lot,
Ateeq Khaliq

**Comment by tiagochst** [comment]
The last biomart version is 2.37.4 (https://github.com/grimbough/biomaRt) the one you have is old (biomaRt_2.32.1)

Please, could you install the last version ?
`devtools::install_github("grimbough/biomaRt") `

The error is in the part of the code we access ensembl database to get the last genome of reference data.

**Comment by FanqianYin** [comment]
I met the same problem despite I have biomaRt_2.4.

**Comment by tiagochst** [comment]
Hello,

The last biomaRt version is 2.41.4. Please, could you install from github
with devtools::install_github("grimbough/biomaRt") and try again ?

Best regards,
Tiago Chedraoui Silva

**Comment by FanqianYin** [comment]
Thank you, Tiago. But after I updated to 2.41.4, I still  encounter the same problem:

Starting to add information to samples
 => Add clinical information to samples
Add FFPE information. More information at: 
=> https://cancergenome.nih.gov/cancersselected/biospeccriteria 
=> http://gdac.broadinstitute.org/runs/sampleReports/latest/FPPP_FFPE_Cases.html
 => Adding subtype information to samples
chol subtype information from:doi:10.1016/j.celrep.2017.02.033
Accessing www.ensembl.org to get gene information
**Error: $ operator is invalid for atomic vectors**

It is weird that I had successfully run GDCprepare()  twice before, then it just didn't work.

**Comment by diceofeugene** [comment]
I have the same problem with biomaRt 2.41.4 and TCGAbiolinks 2.13.2.

**Comment by ilirsheraj** [comment]
The package seems to have a weird problem: Sometimes it works sometimes it doesnt. 
It worked with PRAD but now its not working with BRCA

**Comment by tiagochst** [comment]
I believe there is a problem with the access of the ensembl database using biomaRt. It seems it is working for grch37.ensembl.org  but I am also getting the same problem with www.ensembl.org.
I'll work on the problem today.

**Comment by tiagochst** [comment]
The mirrors are working well. I'll change the code to add a time limit to access www.ensembl.org.

**Comment by ilirsheraj** [comment]
Once you have done so, can you let us know, and also whether we should use the bioconductor or the github version of the package. Thank you

**Comment by tiagochst** [comment]
I changed the mirror in the github version. It should work if you update it:
`BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")`

**Comment by ilirsheraj** [comment]
Now it works perfectly! Thanks a lot.

**Comment by FanqianYin** [comment]
Sadly this mirror does not work in China. It just keeps loading like below:

=> Adding subtype information to samples
esca subtype information from:doi:10.1038/nature20805
Accessing www.ensembl.org (mirror useast)

never stop...

**Comment by debbie28** [comment]
Hi,

I update the TCGAbiolinks, and also biomart, still having the same issue!

**Comment by onlyyouonlyyou** [comment]
yes，I have  the same problem.

Starting to add information to samples
 => Add clinical information to samples
Add FFPE information. More information at: 
=> https://cancergenome.nih.gov/cancersselected/biospeccriteria 
=> http://gdac.broadinstitute.org/runs/sampleReports/latest/FPPP_FFPE_Cases.html
 => Adding subtype information to samples
chol subtype information from:doi:10.1016/j.celrep.2017.02.033
Accessing www.ensembl.org to get gene information
Downloading genome information (try:0) Using: Human genes (GRCh38.p12)
Error: $ operator is invalid for atomic vectors
maybe God can sovle this trouble.

**Comment by hwanho633** [comment]
I am experiencing this issue as well.

> TCGA_READ_data <- GDCprepare(query)
|=======================================================================================================|100%                      Completed after 21 s 
Starting to add information to samples
 => Add clinical information to samples
Add FFPE information. More information at: 
=> https://cancergenome.nih.gov/cancersselected/biospeccriteria 
=> http://gdac.broadinstitute.org/runs/sampleReports/latest/FPPP_FFPE_Cases.html
 => Adding subtype information to samples
read subtype information from:doi:10.1038/nature11252
Accessing www.ensembl.org to get gene information
Downloading genome information (try:0) Using: Human genes (GRCh38.p12)
Error: $ operator is invalid for atomic vectors

Running with
R version 3.6.0 (2019-04-26)
Windows 7 64-bit

I have updated all required packages

**Comment by AimSchina** [comment]
Same Issue for me, working on a HPC. Have also tried the suggested update of the packages.
Platform: x86_64-pc-linux-gnu
R.version: 3.5

`Starting to add information to samples
 => Add clinical information to samples
Add FFPE information. More information at:
=> https://cancergenome.nih.gov/cancersselected/biospeccriteria
=> http://gdac.broadinstitute.org/runs/sampleReports/latest/FPPP_FFPE_Cases.html
 => Adding subtype information to samples
hnsc subtype information from:doi:10.1038/nature14129
Accessing www.ensembl.org to get gene information
Downloading genome information (try:0) Using: Human genes (GRCh38.p12)
Error: $ operator is invalid for atomic vectors
`

**Comment by dmoaks** [comment]
I have the same issue, even after updating both packages.

- Session info -------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/New_York            
 date     2019-07-09                  

- Packages -----------------------------------------------------------------------------------------
 ! package              * version   date       lib source                                          
   annotate               1.62.0    2019-05-02 [1] Bioconductor                                    
   AnnotationDbi          1.46.0    2019-05-02 [1] Bioconductor                                    
   aroma.light            3.14.0    2019-05-02 [1] Bioconductor                                    
   askpass                1.1       2019-01-13 [1] CRAN (R 3.6.0)                                  
   assertthat             0.2.1     2019-03-21 [1] CRAN (R 3.6.0)                                  
   backports              1.1.4     2019-04-10 [1] CRAN (R 3.6.0)                                  
   Biobase              * 2.44.0    2019-05-02 [1] Bioconductor                                    
   BiocFileCache          1.8.0     2019-05-02 [1] Bioconductor                                    
   BiocGenerics         * 0.30.0    2019-05-02 [1] Bioconductor                                    
   BiocParallel         * 1.18.0    2019-05-03 [1] Bioconductor                                    
   biomaRt                2.41.6    2019-07-08 [1] Github (grimbough/biomaRt@919717e)              
   Biostrings             2.52.0    2019-05-02 [1] Bioconductor                                    
   bit                    1.1-14    2018-05-29 [1] CRAN (R 3.6.0)                                  
   bit64                  0.9-7     2017-05-08 [1] CRAN (R 3.6.0)                                  
   bitops                 1.0-6     2013-08-17 [1] CRAN (R 3.6.0)                                  
 V blob                   1.1.1     2019-07-09 [1] CRAN (R 3.6.0)                                  
   broom                  0.5.2     2019-04-07 [1] CRAN (R 3.6.0)                                  
   callr                  3.2.0     2019-03-15 [1] CRAN (R 3.6.0)                                  
   circlize               0.4.6     2019-04-03 [1] CRAN (R 3.6.0)                                  
   cli                    1.1.0     2019-03-19 [1] CRAN (R 3.6.0)                                  
   clue                   0.3-57    2019-02-25 [1] CRAN (R 3.6.0)                                  
   cluster                2.0.9     2019-05-01 [2] CRAN (R 3.6.0)                                  
   cmprsk                 2.2-8     2019-05-27 [1] CRAN (R 3.6.0)                                  
   codetools              0.2-16    2018-12-24 [2] CRAN (R 3.6.0)                                  
   colorspace             1.4-1     2019-03-18 [1] CRAN (R 3.6.0)                                  
   ComplexHeatmap         2.0.0     2019-05-02 [1] Bioconductor                                    
   ConsensusClusterPlus   1.48.0    2019-05-02 [1] Bioconductor                                    
   crayon                 1.3.4     2017-09-16 [1] CRAN (R 3.6.0)                                  
   curl                   3.3       2019-01-10 [1] CRAN (R 3.6.0)                                  
   data.table             1.12.2    2019-04-07 [1] CRAN (R 3.6.0)                                  
   DBI                    1.0.0     2018-05-02 [1] CRAN (R 3.6.0)                                  
   dbplyr                 1.4.2     2019-06-17 [1] CRAN (R 3.6.0)                                  
   DelayedArray         * 0.10.0    2019-05-02 [1] Bioconductor                                    
   desc                   1.2.0     2018-05-01 [1] CRAN (R 3.6.0)                                  
   DESeq                  1.36.0    2019-05-02 [1] Bioconductor                                    
   devtools             * 2.0.2     2019-04-08 [1] CRAN (R 3.6.0)                                  
   digest                 0.6.20    2019-07-04 [1] CRAN (R 3.6.1)                                  
   doParallel             1.0.14    2018-09-24 [1] CRAN (R 3.6.0)                                  
   downloader             0.4       2015-07-09 [1] CRAN (R 3.6.0)                                  
   dplyr                  0.8.3     2019-07-04 [1] CRAN (R 3.6.1)                                  
   EDASeq                 2.18.0    2019-05-02 [1] Bioconductor                                    
   edgeR                * 3.26.5    2019-06-21 [1] Bioconductor                                    
   fdrtool              * 1.2.15    2015-07-08 [1] CRAN (R 3.6.0)                                  
   foreach                1.4.4     2017-12-12 [1] CRAN (R 3.6.0)                                  
   fs                     1.3.1     2019-05-06 [1] CRAN (R 3.6.0)                                  
   genefilter             1.66.0    2019-05-02 [1] Bioconductor                                    
   geneplotter            1.62.0    2019-05-02 [1] Bioconductor                                    
   generics               0.0.2     2018-11-29 [1] CRAN (R 3.6.0)                                  
   GenomeInfoDb         * 1.20.0    2019-05-02 [1] Bioconductor                                    
   GenomeInfoDbData       1.2.1     2019-06-26 [1] Bioconductor                                    
   GenomicAlignments      1.20.1    2019-06-18 [1] Bioconductor                                    
   GenomicFeatures        1.36.3    2019-06-23 [1] Bioconductor                                    
   GenomicRanges        * 1.36.0    2019-05-02 [1] Bioconductor                                    
   GetoptLong             0.1.7     2018-06-10 [1] CRAN (R 3.6.0)                                  
   ggplot2                3.2.0     2019-06-16 [1] CRAN (R 3.6.0)                                  
   ggpubr                 0.2.1     2019-06-23 [1] CRAN (R 3.6.0)                                  
   ggrepel                0.8.1     2019-05-07 [1] CRAN (R 3.6.0)                                  
   ggsignif               0.5.0     2019-02-20 [1] CRAN (R 3.6.0)                                  
   ggthemes               4.2.0     2019-05-13 [1] CRAN (R 3.6.0)                                  
   GlobalOptions          0.1.0     2018-06-09 [1] CRAN (R 3.6.0)                                  
   glue                   1.3.1     2019-03-12 [1] CRAN (R 3.6.0)                                  
   gridExtra              2.3       2017-09-09 [1] CRAN (R 3.6.0)                                  
   gtable                 0.3.0     2019-03-25 [1] CRAN (R 3.6.0)                                  
 V hms                    0.4.2     2019-07-09 [1] CRAN (R 3.6.0)                                  
   httr                   1.4.0     2018-12-11 [1] CRAN (R 3.6.0)                                  
   hwriter                1.3.2     2014-09-10 [1] CRAN (R 3.6.0)                                  
   IRanges              * 2.18.1    2019-05-31 [1] Bioconductor                                    
   iterators              1.0.10    2018-07-13 [1] CRAN (R 3.6.0)                                  
   jsonlite               1.6       2018-12-07 [1] CRAN (R 3.6.0)                                  
   km.ci                  0.5-2     2009-08-30 [1] CRAN (R 3.6.0)                                  
   KMsurv                 0.1-5     2012-12-03 [1] CRAN (R 3.6.0)                                  
   knitr                  1.23      2019-05-18 [1] CRAN (R 3.6.0)                                  
   lattice                0.20-38   2018-11-04 [2] CRAN (R 3.6.0)                                  
   latticeExtra           0.6-28    2016-02-09 [1] CRAN (R 3.6.0)                                  
   lazyeval               0.2.2     2019-03-15 [1] CRAN (R 3.6.0)                                  
   limma                * 3.40.2    2019-05-17 [1] Bioconductor                                    
   locfit                 1.5-9.1   2013-04-20 [1] CRAN (R 3.6.0)                                  
   magrittr               1.5       2014-11-22 [1] CRAN (R 3.6.0)                                  
   matlab                 1.0.2     2014-06-24 [1] CRAN (R 3.6.0)                                  
   Matrix                 1.2-17    2019-03-22 [2] CRAN (R 3.6.0)                                  
   matrixStats          * 0.54.0    2018-07-23 [1] CRAN (R 3.6.0)                                  
   memoise                1.1.0     2017-04-21 [1] CRAN (R 3.6.0)                                  
   mgcv                   1.8-28    2019-03-21 [2] CRAN (R 3.6.0)                                  
   munsell                0.5.0     2018-06-12 [1] CRAN (R 3.6.0)                                  
   nlme                   3.1-140   2019-05-12 [1] CRAN (R 3.6.0)                                  
   openssl                1.4       2019-05-31 [1] CRAN (R 3.6.0)                                  
   pillar                 1.4.2     2019-06-29 [1] CRAN (R 3.6.0)                                  
   pkgbuild               1.0.3     2019-03-20 [1] CRAN (R 3.6.0)                                  
   pkgconfig              2.0.2     2018-08-16 [1] CRAN (R 3.6.0)                                  
   pkgload                1.0.2     2018-10-29 [1] CRAN (R 3.6.0)                                  
   plyr                   1.8.4     2016-06-08 [1] CRAN (R 3.6.0)                                  
   png                    0.1-7     2013-12-03 [1] CRAN (R 3.6.0)                                  
   prettyunits            1.0.2     2015-07-13 [1] CRAN (R 3.6.0)                                  
   processx               3.3.1     2019-05-08 [1] CRAN (R 3.6.0)                                  
   progress               1.2.2     2019-05-16 [1] CRAN (R 3.6.0)                                  
   ps                     1.3.0     2018-12-21 [1] CRAN (R 3.6.0)                                  
   purrr                  0.3.2     2019-03-15 [1] CRAN (R 3.6.0)                                  
   R.methodsS3            1.7.1     2016-02-16 [1] CRAN (R 3.6.0)                                  
   R.oo                   1.22.0    2018-04-22 [1] CRAN (R 3.6.0)                                  
   R.utils                2.9.0     2019-06-13 [1] CRAN (R 3.6.0)                                  
   R6                     2.4.0     2019-02-14 [1] CRAN (R 3.6.0)                                  
   rappdirs               0.3.1     2016-03-28 [1] CRAN (R 3.6.0)                                  
   RColorBrewer           1.1-2     2014-12-07 [1] CRAN (R 3.6.0)                                  
   Rcpp                   1.0.1     2019-03-17 [1] CRAN (R 3.6.0)                                  
   RCurl                  1.95-4.12 2019-03-04 [1] CRAN (R 3.6.0)                                  
   readr                  1.3.1     2018-12-21 [1] CRAN (R 3.6.0)                                  
   remotes                2.1.0     2019-06-24 [1] CRAN (R 3.6.0)                                  
   rjson                  0.2.20    2018-06-08 [1] CRAN (R 3.6.0)                                  
   rlang                  0.4.0     2019-06-25 [1] CRAN (R 3.6.0)                                  
   rprojroot              1.3-2     2018-01-03 [1] CRAN (R 3.6.0)                                  
   Rsamtools              2.0.0     2019-05-02 [1] Bioconductor                                    
   RSQLite                2.1.1     2018-05-06 [1] CRAN (R 3.6.0)                                  
   rstudioapi             0.10      2019-03-19 [1] CRAN (R 3.6.0)                                  
   rtracklayer            1.44.0    2019-05-02 [1] Bioconductor                                    
   rvest                  0.3.4     2019-05-15 [1] CRAN (R 3.6.0)                                  
   S4Vectors            * 0.22.0    2019-05-02 [1] Bioconductor                                    
   scales                 1.0.0     2018-08-09 [1] CRAN (R 3.6.0)                                  
   selectr                0.4-1     2018-04-06 [1] CRAN (R 3.6.0)                                  
   sessioninfo            1.1.1     2018-11-05 [1] CRAN (R 3.6.0)                                  
   shape                  1.4.4     2018-02-07 [1] CRAN (R 3.6.0)                                  
   ShortRead              1.42.0    2019-05-02 [1] Bioconductor                                    
   stringi                1.4.3     2019-03-12 [1] CRAN (R 3.6.0)                                  
   stringr                1.4.0     2019-02-10 [1] CRAN (R 3.6.0)                                  
   SummarizedExperiment * 1.14.0    2019-05-02 [1] Bioconductor                                    
   survival               2.44-1.1  2019-04-01 [2] CRAN (R 3.6.0)                                  
   survminer              0.4.4     2019-05-21 [1] CRAN (R 3.6.0)                                  
   survMisc               0.5.5     2018-07-05 [1] CRAN (R 3.6.0)                                  
   sva                    3.32.1    2019-05-22 [1] Bioconductor                                    
   TCGAbiolinks         * 2.13.2    2019-07-09 [1] Github (BioinformaticsFMRP/TCGAbiolinks@0a441ea)
   tibble                 2.1.3     2019-06-06 [1] CRAN (R 3.6.0)                                  
   tidyr                  0.8.3     2019-03-01 [1] CRAN (R 3.6.0)                                  
   tidyselect             0.2.5     2018-10-11 [1] CRAN (R 3.6.0)                                  
   usethis              * 1.5.0     2019-04-07 [1] CRAN (R 3.6.0)                                  
   withr                  2.1.2     2018-03-15 [1] CRAN (R 3.6.0)                                  
   xfun                   0.8       2019-06-25 [1] CRAN (R 3.6.0)                                  
   XML                    3.98-1.20 2019-06-06 [1] CRAN (R 3.6.0)                                  
   xml2                   1.2.0     2018-01-24 [1] CRAN (R 3.6.0)                                  
   xtable                 1.8-4     2019-04-21 [1] CRAN (R 3.6.0)                                  
   XVector                0.24.0    2019-05-02 [1] Bioconductor                                    
   zlibbioc               1.30.0    2019-05-02 [1] Bioconductor                                    
   zoo                    1.8-6     2019-05-28 [1] CRAN (R 3.6.0)

**Comment by tiagochst** [comment]
Sorry for the late reply, there was a change of the name from entrezgene to entrezgene_id. I changed and made some improvements to the code. It should be working now.

Please, could you update with the github version with the following code `BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")`.

**Comment by Bang9suK** [comment]
> Sorry for the late reply, there was a change of the name from entrezgene to entrezgene_id. I changed and made some improvements to the code. It should be working now.
> 
> Please, could you update with the github version with the following code `BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")`.

Thank you Tiago. GDCperpare now runs nicely.

**Comment by onlyyouonlyyou** [comment]
> Sorry for the late reply, there was a change of the name from entrezgene to entrezgene_id. I changed and made some improvements to the code. It should be working now.
> 
> Please, could you update with the github version with the following code `BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")`.

Thank you Tiago.it works,GDCprepare runs now,you are the God in my heart.Thankyou again.

**Comment by hloefflerwirth** [comment]
Thanks Tiago, it works!

**Comment by BBJ0613** [comment]
`BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")
Bioconductor version 3.9 (BiocManager 1.30.4), R 3.6.0 (2019-04-26)
Installing github package(s) 'BioinformaticsFMRP/TCGAbiolinks'
Downloading GitHub repo BioinformaticsFMRP/TCGAbiolinks@master
Error: Failed to install 'TCGAbiolinks' from GitHub:
  incomplete block on file
`
sorry，I updated the ‘biomaRt’，and wanna update 'TCGAbiolinks', it error >_<

**Comment by BBJ0613** [comment]
> Sorry for the late reply, there was a change of the name from entrezgene to entrezgene_id. I changed and made some improvements to the code. It should be working now.
> 
> Please, could you update with the github version with the following code `BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")`.

BiocManager::install("BioinformaticsFMRP/TCGAbiolinks") Bioconductor version 3.9 (BiocManager 1.30.4), R 3.6.0 (2019-04-26) Installing github package(s) 'BioinformaticsFMRP/TCGAbiolinks' Downloading GitHub repo BioinformaticsFMRP/TCGAbiolinks@master Error: Failed to install 'TCGAbiolinks' from GitHub: incomplete block on file 
sorry，I updated the ‘biomaRt’，and wanna update 'TCGAbiolinks', it error >_<

**Comment by jammywwh** [comment]
> Sadly this mirror does not work in China. It just keeps loading like below:
> 
> => Adding subtype information to samples
> esca subtype information from:doi:10.1038/nature20805
> Accessing [www.ensembl.org](http://www.ensembl.org) (mirror useast)
> 
> never stop...

你好，你解决了吗

**Comment by a0neup03** [comment]
I am trying to use the  
`met.gbm.450<-GDCprepare(query=query.met.gbm,save=TRUE,save.filename = "gbmDNAmet450k.rda",summarizedExperiment = TRUE)`
based on https://f1000research.com/articles/5-1542 but I still have the same error $ operator is invalid for atomic vectors. I updated both biomart and TCGAbiolinks as specified above.

Based on the vignette from here, 
https://bioconductor.org/packages/release/data/experiment/vignettes/TCGAWorkflowData/inst/doc/TCGAWorkflowData.R
I got the same error from the line
`genes <- TCGAbiolinks:::get.GRCh.bioMart(genome = "hg19",as.granges=TRUE)`

Downloading genome information (try:0) Using: Human genes (GRCh38.p13)
Error: $ operator is invalid for atomic vectors

I think I have the two packages of the right version.

` sessionInfo()`
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] TCGAWorkflowData_1.6.0                 
 [2] biomaRt_2.38.0                         
 [3] TCGAbiolinks_2.10.5                    
 [4] ChIPseeker_1.18.0                      
 [5] TxDb.Hsapiens.UCSC.hg38.knownGene_3.4.0
 [6] GenomicFeatures_1.34.8                 
 [7] dplyr_0.8.5                            
 [8] GenomicRanges_1.34.0                   
 [9] GenomeInfoDb_1.18.2                    
[10] GeneAnswers_2.24.0                     
[11] RColorBrewer_1.1-2                     
[12] Heatplus_2.28.0                        
[13] MASS_7.3-51.4                          
[14] RSQLite_2.1.2                          
[15] annotate_1.60.1                        
[16] XML_3.98-1.20                          
[17] AnnotationDbi_1.44.0                   
[18] IRanges_2.16.0                         
[19] S4Vectors_0.20.1                       
[20] Biobase_2.42.0                         
[21] BiocGenerics_0.28.0                    
[22] RCurl_1.95-4.12                        
[23] bitops_1.0-6                           
[24] igraph_1.2.4.1
