### ISSUE TITLE
problem for installing TCGAbiolinks

### ISSUE THREAD

**Issue by modarzi** [BioinformaticsFMRP/TCGAbiolinks#251]
Hi,

As I told before, I couldn't download TCGA data and you told me this problem relate to windows 10. So, I change my OS and now I have Ubuntu 16. again I tried to install TCGAbiolinks and have problem. my command is:
library(devtools)
devtools::install_github(repo = "BioinformaticsFMRP/TCGAbiolinks",dependencies = T)
 but after while I receive below result in terminal:

* installing *source* package ‘TCGAbiolinks’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘ComplexHeatmap’ 1.6.0 is being loaded, but >= 1.10.2 is required
ERROR: lazy loading failed for package ‘TCGAbiolinks’
* removing ‘/usr/local/lib/R/site-library/TCGAbiolinks’
Installation failed: Command failed (1)

my sessioninfo() is:

R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8    LC_NUMERIC=C            LC_TIME=fa_IR          
 [4] LC_COLLATE=en_US.UTF-8  LC_MONETARY=fa_IR       LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=fa_IR          LC_NAME=C               LC_ADDRESS=C           
[10] LC_TELEPHONE=C          LC_MEASUREMENT=fa_IR    LC_IDENTIFICATION=C

I have tried hard but up to now I couldn't get my result via TCGAbiolinks package. I appreciate if you guide me for solving this problem.

Best Regards,
Mohammad

**Comment by tiagochst** [comment]
Hi,
the output says ComplexHeatmap is outdated. Could you update it via bioconductor? You have installed version 1.6.0 the actual version is 1.18.1.
```
source("https://bioconductor.org/biocLite.R")
biocLite("ComplexHeatmap",ask = FALSE)
```

**Comment by modarzi** [comment]
Hi, 
Thanks for your comment.I did it but as you see in below, 

>biocLite("ComplexHeatmap",ask = FALSE)

BioC_mirror: https://bioconductor.org
Using Bioconductor 3.2 (BiocInstaller 1.20.3), R 3.4.4 (2018-03-15).
Installing package(s) ‘ComplexHeatmap’
	trying URL 'https://bioconductor.org/packages/3.2/bioc/src/contrib/ComplexHeatmap_1.6.0.tar.gz'
Content type 'application/x-gzip' length 3505674 bytes (3.3 MB)
==================================================
downloaded 3.3 MB

* installing *source* package ‘ComplexHeatmap’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (ComplexHeatmap)

and again run installing command for TCGAbiolinks as below:
>devtools::install_github(repo = "BioinformaticsFMRP/TCGAbiolinks",dependencies = T)

but I recieved again previous message:

* installing *source* package ‘TCGAbiolinks’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘ComplexHeatmap’ 1.6.0 is being loaded, but >= 1.10.2 is required
ERROR: lazy loading failed for package ‘TCGAbiolinks’
* removing ‘/usr/local/lib/R/site-library/TCGAbiolinks’
* restoring previous ‘/usr/local/lib/R/site-library/TCGAbiolinks’
Installation failed: Command failed (1)

I appreciate if you guide me for solving this problem.

Best Regards,
Mohammad

**Comment by tiagochst** [comment]
Your bioconductor version is old (3.2). 
Could you follow the instructions here:
http://bioconductor.org/install/

I believe the code below should solve the problem.
## try http:// if https:// URLs are not supported source("https://bioconductor.org/biocLite.R") biocLite("BiocUpgrade") ## R version 2.15 or later

Tiago Chedraoui Silva

Em 10 de ago de 2018, à(s) 03:36, Mohammad Darzi <notifications@github.com> escreveu:
