### ISSUE TITLE
Error in parse query

### ISSUE THREAD

**Issue by asmagen** [BioinformaticsFMRP/TCGAbiolinks#252]
Hello,

I get an error trying to get clinical supplement / drug data.
I ran the following code:
```
library(TCGAbiolinks)
query <- GDCquery(project = projects, 
                  data.category = "Clinical", 
                  file.type = "xml")
GDCdownload(query)
```
where projects is a vector with several cancer types and the error I get in the parse function:
```
> drug <- GDCprepare_clinic(query, clinical.info = "drug")
Error in GDCprepare_clinic(query, clinical.info = "drug") : 
  I couldn't find all the files from the query.Please check directory parameter right
```

Thanks for helping with this.
Assaf

**Comment by asmagen** [comment]
But I saw in your code you have a loop for that. And it does download all the data separately for each cancer type. So why would running it separately for each cancer type in a loop help?

Thanks

**Comment by tiagochst** [comment]
Although `GDCquery` and `GDCprepare`   have an internal loop for projects. `GDCprepare_clinic` does not have that internal loop.

**Comment by tiagochst** [comment]
Now  `GDCprepare_clinic` should be working for multiple projects.

```
query <- GDCquery(project = c("TCGA-ESCA","TCGA-ACC"),
                  data.category = "Clinical", 
                  file.type = "xml")
GDCdownload(query)
info.drug.all <- GDCprepare_clinic(query, clinical.info = "drug")
info.patient.all <- GDCprepare_clinic(query, clinical.info = "patient")
info.admin.all <- GDCprepare_clinic(query, clinical.info = "admin")

```
