### ISSUE TITLE
GDCprepare for exon quantification

### ISSUE THREAD

**Issue by fiwong** [BioinformaticsFMRP/TCGAbiolinks#253]
Hi, I am trying to use GDCprepare for the exon quantification files that I downloaded. 

Here is the code
query.TCGASKCMexon.highALK.hg19 <- GDCquery(project = "TCGA-SKCM",
                                data.category = "Gene expression",
                                data.type = "Exon quantification",
                                barcode = c("TCGA-D3-A3CF-06A-11R-A18T-07", "TCGA-WE-A8K4-01A-12R-A37K-07"),
                                legacy = TRUE)
GDCdownload(query.TCGASKCMexon.highALK.hg19)
TCGASKCMexon.highALK.hg19. <- GDCprepare(query.TCGASKCMexon.highALK.hg19)

I am able to download the files but cannot combine the files into one summerized experiment.

Error is 
> TCGASKCMexon.highALK.hg19. <- GDCprepare(query.TCGASKCMexon.highALK.hg19)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘metadata<-’ for signature ‘"function"’

Can anyone help?

Thanks

**Comment by tiagochst** [comment]
Sorry there was no support for "Exon quantification" reading. Now, it should be working.

**Comment by fiwong** [comment]
working now. thank you very much!
