### ISSUE TITLE
Run TCGAbiolinks 

### ISSUE THREAD

**Issue by hexingkang1990** [BioinformaticsFMRP/TCGAbiolinks#254]
When I try to run TCGAbiolinks, it has problems. 

> TCGAbiolinksGUI()
Warning: Error in if: argument is of length zero
  48: survivalplotdata [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/survival.R#30]
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/survival.R#72]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in if: argument is of length zero
  48: survivalplotdata [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/survival.R#30]
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/survival.R#84]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in if: argument is of length zero
  48: survivalplotdata [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/survival.R#30]
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/survival.R#99]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in if: argument is of length zero
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/volcano.R#99]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in if: argument is of length zero
  64: <reactive:volcanodata> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/volcano.R#62]
  48: volcanodata
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/volcano.R#106]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in if: argument is of length zero
  68: eval [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/heatmap.R#164]
  67: eval
  66: withProgress
  65: <reactive:heatmapdata> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/heatmap.R#161]
  49: heatmapdata
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/heatmap.R#98]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in if: argument is of length zero
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/heatmap.R#111]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in if: argument is of length zero
  50: <Anonymous>
Warning: Error in if: argument is of length zero
  50: <Anonymous>
Warning: Error in if: argument is of length zero
  96: eval [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/dmr.R#153]
  95: eval
  94: withProgress
  93: <reactive:dmrdata> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/dmr.R#150]
  77: dmrdata
  75: observeEventHandler [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/dmr.R#29]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in if: argument is of length zero
  51: <Anonymous>
Warning: Error in if: argument is of length zero
  68: eval [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/meanMet.R#153]
  67: eval
  66: withProgress
  65: <reactive:meandata> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/meanMet.R#150]
  49: meandata
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/meanMet.R#26]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in if: argument is of length zero
  51: <Anonymous>
Warning: Error in gzfile: invalid 'description' argument
  80: gzfile
  79: load
  77: deadata [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/dea.R#165]
  75: observeEventHandler [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/dea.R#179]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in gzfile: invalid 'description' argument
  80: gzfile
  79: load
  77: deadata [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/dea.R#165]
  75: observeEventHandler [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/dea.R#186]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in gzfile: invalid 'description' argument
  52: gzfile
  51: load
  49: deadata [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/dea.R#165]
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/dea.R#194]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in if: argument is of length zero
  66: <reactive:annotation.maf> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/oncoprint.R#112]
  50: annotation.maf
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/oncoprint.R#90]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in gzfile: invalid 'description' argument
  70: gzfile
  69: load
  64: <reactive:maedata> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/elmer.R#347]
  48: maedata
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/elmer.R#192]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in gzfile: invalid 'description' argument
  78: <Anonymous>
Warning: Error in gzfile: invalid 'description' argument
  78: <Anonymous>
Warning: Error in gzfile: invalid 'description' argument
  70: gzfile
  69: load
  64: <reactive:elmer.results.data> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/elmer.R#334]
  48: elmer.results.data
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/elmer.R#357]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in gzfile: invalid 'description' argument
  78: <Anonymous>
Warning: Error in gzfile: invalid 'description' argument
  51: <Anonymous>
Warning: Error in gzfile: invalid 'description' argument
  51: <Anonymous>
> TCGAbiolinksGUI()
Warning: Error in if: argument is of length zero
  48: survivalplotdata [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/survival.R#30]
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/survival.R#72]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in if: argument is of length zero
  48: survivalplotdata [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/survival.R#30]
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/survival.R#84]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in if: argument is of length zero
  48: survivalplotdata [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/survival.R#30]
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/survival.R#99]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in if: argument is of length zero
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/volcano.R#99]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in if: argument is of length zero
  64: <reactive:volcanodata> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/volcano.R#62]
  48: volcanodata
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/volcano.R#106]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in if: argument is of length zero
  68: eval [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/heatmap.R#164]
  67: eval
  66: withProgress
  65: <reactive:heatmapdata> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/heatmap.R#161]
  49: heatmapdata
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/heatmap.R#98]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in if: argument is of length zero
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/heatmap.R#111]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in if: argument is of length zero
  50: <Anonymous>
Warning: Error in if: argument is of length zero
  50: <Anonymous>
Warning: Error in if: argument is of length zero
  96: eval [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/dmr.R#153]
  95: eval
  94: withProgress
  93: <reactive:dmrdata> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/dmr.R#150]
  77: dmrdata
  75: observeEventHandler [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/dmr.R#29]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in if: argument is of length zero
  51: <Anonymous>
Warning: Error in if: argument is of length zero
  68: eval [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/meanMet.R#153]
  67: eval
  66: withProgress
  65: <reactive:meandata> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/meanMet.R#150]
  49: meandata
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/meanMet.R#26]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in if: argument is of length zero
  51: <Anonymous>
Warning: Error in gzfile: invalid 'description' argument
  80: gzfile
  79: load
  77: deadata [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/dea.R#165]
  75: observeEventHandler [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/dea.R#179]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in gzfile: invalid 'description' argument
  80: gzfile
  79: load
  77: deadata [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/dea.R#165]
  75: observeEventHandler [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/dea.R#186]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in gzfile: invalid 'description' argument
  52: gzfile
  51: load
  49: deadata [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/dea.R#165]
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/dea.R#194]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in if: argument is of length zero
  66: <reactive:annotation.maf> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/oncoprint.R#112]
  50: annotation.maf
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/oncoprint.R#90]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in gzfile: invalid 'description' argument
  70: gzfile
  69: load
  64: <reactive:maedata> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/elmer.R#347]
  48: maedata
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/elmer.R#192]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in gzfile: invalid 'description' argument
  78: <Anonymous>
Warning: Error in gzfile: invalid 'description' argument
  78: <Anonymous>
Warning: Error in gzfile: invalid 'description' argument
  70: gzfile
  69: load
  64: <reactive:elmer.results.data> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/elmer.R#334]
  48: elmer.results.data
  47: <observer> [C:/Users/HXK/Documents/R/win-library/3.5/TCGAbiolinksGUI/app/server/elmer.R#357]
   4: shiny::runApp
   1: TCGAbiolinksGUI
Warning: Error in gzfile: invalid 'description' argument
  78: <Anonymous>
Warning: Error in gzfile: invalid 'description' argument
  51: <Anonymous>
Warning: Error in gzfile: invalid 'description' argument
  51: <Anonymous>

**Comment by tiagochst** [comment]
Could you try the github version?
`devtools::install_github("BioinformaticsFMRP/TCGAbiolinksGUI")`

**Comment by hexingkang1990** [comment]
Thank you for your reply. I have tried the github version and the problem is same.

**Comment by tiagochst** [comment]
Please, Which button are you selecting ? 
Or iota does not start?
The package we were using had a change in the object, I need to go through all buttons and update the code.

Please, could you check if you have the last version of shinyFiles?
https://github.com/thomasp85/shinyFiles



Em 25 de ago de 2018, à(s) 06:41, hexingkang1990 <notifications@github.com> escreveu:

**Comment by hexingkang1990** [comment]
Thank you for your help. I restart again and it works. Thank you very much.
