### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by martalovino** [BioinformaticsFMRP/TCGAbiolinks#26]
Hi, I'm new in R programming and RStudio software and I need to use TCGAbiolinks for my thesis.
However, I have some installation problems: typing devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")
in RStudio console I receive this error:

`Downloading GitHub repo BioinformaticsFMRP/TCGAbiolinks@master
from URL https://api.github.com/repos/BioinformaticsFMRP/TCGAbiolinks/zipball/master
Installing TCGAbiolinks
"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/marta/AppData/Local/Temp/RtmpAFVBV9/devtools1e5024642378/BioinformaticsFMRP-TCGAbiolinks-4c9059d"  \
  --library="C:/Users/marta/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'TCGAbiolinks' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'shape'
ERROR: lazy loading failed for package 'TCGAbiolinks'
* removing 'C:/Users/marta/Documents/R/win-library/3.3/TCGAbiolinks'
* restoring previous 'C:/Users/marta/Documents/R/win-library/3.3/TCGAbiolinks'
Error: Command failed (1)`

Moreover, sessionInfo() is

R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Italian_Italy.1252  LC_CTYPE=Italian_Italy.1252   
[3] LC_MONETARY=Italian_Italy.1252 LC_NUMERIC=C                  
[5] LC_TIME=Italian_Italy.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.2.1           R6_2.1.3             BiocInstaller_1.22.3 tools_3.3.1         
 [5] withr_1.0.2          curl_1.2             memoise_1.0.0        knitr_1.14          
 [9] git2r_0.15.0         digest_0.6.10        devtools_1.12.0 

Somebody knows what I'm getting wrong?

**Comment by torongs82** [comment]
Hi Marta thank you writing us and for your interest in TCGAbiolinks.

Before installing TCGAbiolinks can you try to install 'shape':
install.packages("shape")
require(shape)

Let us update.

**Comment by martalovino** [comment]
I've just installed this package and I have a similar errors, but with other packages.
In particular, after installing "tibble", "haven", "lme4", "stringdist", "tidyr", "foreach", "broom", "effects", "sjstats" packages, the command library(TCGAbiolinks) works fine.
Thank you very much for your solution!
