### ISSUE TITLE
Different pvalues in TCGAanalyze_survival

### ISSUE THREAD

**Issue by xiexiaowei** [BioinformaticsFMRP/TCGAbiolinks#27]
Thank you so much for your versatile and updated "TCGAbiolinks".
I have successfully installed that in our linux system. But when I used the "TCGAanalyze_survival", I met a problem.

code1. 
library(TCGAbiolinks)
clin.data <- GDCquery_clinic("TCGA-ACC", "clinical", save.csv=TRUE)
TCGAanalyze_survival(clin.data,clusterCol = "gender", filename = "test.pdf")
## # The pvalue is 6.5e−01 in test.pdf.

Because I need to output the pvalue, so I paste the code from "TCGAanalyze_survival", like this:
code2:
data=clin.data
clusterCol = "gender"
data$s <- grepl("dead", data$vital_status, ignore.case = TRUE)
data$type <- as.factor(data[, clusterCol])
f.m <- formula(Surv(as.numeric(data$days_to_death), event = data$s) ~ data$type)
fit <- survfit(f.m, data = data)
pvalue <- summary(coxph(Surv(as.numeric(data$days_to_death), event = data$s) ~ data$type))$logtest[3]
## # The pvalue is 0.7388095.

I have tested several conditions, all with different pvalues.
# So what happened? And how cal I get the exact pvalue of survival?

**Comment by tiagochst** [comment]
Hi,

There is one line of code that we do in which we replace the NA values of days_to_death to the last follow up information. Then you should get the same results.
For the case below is will be    pvalue = 0.6514598 or 6.5e−01 in test.pdf.

```
data=clin.data
clusterCol = "gender"
##### This code was missing
notDead <- is.na(data$days_to_death)
if (length(notDead) > 0) {
    data[notDead,]$days_to_death <- data[notDead,]$days_to_last_follow_up
}
#####
data$s <- grepl("dead", data$vital_status, ignore.case = TRUE)
data$type <- as.factor(data[, clusterCol])
f.m <- formula(Surv(as.numeric(data$days_to_death), event = data$s) ~ data$type)
fit <- survfit(f.m, data = data)
pvalue <- summary(coxph(Surv(as.numeric(data$days_to_death), event = data$s) ~ data$type))$logtest[3]
```
