### ISSUE TITLE
Open TCGAprepare Rdata saved file

### ISSUE THREAD

**Issue by caloto** [BioinformaticsFMRP/TCGAbiolinks#272]
I have downloaded methylation data for TCGA-BLCA and stored as .rData object in a directory. The TCGAprepare process is so long and I would like to know if this data can be directly opened from this file as SummarizedExperiment.

Thank you!

**Comment by tiagochst** [comment]
If you don't want to run GDCprepare several times, you can save as rda file either using TCGAbiolinks or outside in R.

```
data <- GDCprepare(query = query,save = T,save.filename = "file.Rda")
data <- get(load("file.Rda"))
```
