### ISSUE TITLE
Error in GDC prepare: cannot open file '~/R/R-3.5.1/library/TCGAbiolinks/R/sysdata.rdb': No such file or directory`

### ISSUE THREAD

**Issue by sumitpaliwal** [BioinformaticsFMRP/TCGAbiolinks#275]
I started some analysis using TCGAbiolinks as follows:
`> GDCdownload(query.met)
Downloading data for project TCGA-PAAD
GDCdownload will download 157 files. A total of 3.340610369 GB
The total size of files is big. We will download files in chunks
Downloading chunk 1 of 4 (46 files, size = 978.888743 MB) as Thu_Oct_25_17_36_30_2018_0.tar.gz
Downloading: 450 MB     Downloading chunk 2 of 4 (46 files, size = 978.551791 MB) as Thu_Oct_25_17_36_30_2018_1.tar.gz
Downloading: 450 MB     Downloading chunk 3 of 4 (46 files, size = 978.885009 MB) as Thu_Oct_25_17_36_30_2018_2.tar.gz
Downloading: 450 MB     Downloading chunk 4 of 4 (19 files, size = 404.284826 MB) as Thu_Oct_25_17_36_30_2018_3.tar.gz
Downloading: 190 MB     
> paad.met <- GDCprepare(query = query.met, save = TRUE, save.filename = "paadDNAmet.rda", summarizedExperiment = TRUE)
  |===================================================================  |  97%|--------------------------------------------------|
|==================================================|
  |=====================================================================| 100%
Downloading genome information (try:0) Using: Homo sapiens genes (GRCh37.p13)
Starting to add information to samples
 => Add clinical information to samples
Add FFPE information. More information at: 
=> https://cancergenome.nih.gov/cancersselected/biospeccriteria 
=> http://gdac.broadinstitute.org/runs/sampleReports/latest/FPPP_FFPE_Cases.html
 => Adding subtype information to samples
paad subtype information from:doi:10.1016/j.ccell.2017.07.007
Error in get(paste0(tolower(tumor), ".subtype")) : 
  cannot open file '~/R/R-3.5.1/library/TCGAbiolinks/R/sysdata.rdb': No such file or directory
In addition: Warning message:
In get(paste0(tolower(tumor), ".subtype")) :
  restarting interrupted promise evaluation`

I got the above error. But when I manually look into the folder, I see that file sysdata.rdb is there.
Any idea why this is happening?
Thanks.
Sumit

**Comment by zoe1995** [comment]
Dear Sumit,
I was wondering if you managed to figure out this problem? I think I am having the same issue. 
I tried to analyse the prostate adenocarcinoma dataset, and I am able to download read files (I can see them in the working directory folder) but the GDCprepare function is giving an error that suggests that it cannot recognise the files. 
Please see below an example of the code and the error message. I’m using R version 3.5.1, and the TCGAbiolinks package version 2.11.1. 
Sumit, is this the same version of the package as you were using and does it seem like the same problem?
If you, or anyone else, has any suggestions then I would be very grateful. 
Many Thanks,
Zoe 

Script:
devtools::install_github(repo = "BioinformaticsFMRP/TCGAbiolinks")
query <- GDCquery(project = "TCGA-PRAD",
                   data.category = "Transcriptome Profiling",
                   data.type = "miRNA Expression Quantification",
                   workflow.type = "BCGSC miRNA Profiling",
                   barcode = c("TCGA-2A-A8VL-01A","TCGA-2A-A8VO-01A"))
GDCdownload(query, method = "api", directory = "GDCdata",
            files.per.chunk = NULL)
GDCprepare(query, save = FALSE, save.filename, directory = "GDCdata",
           summarizedExperiment = TRUE, remove.files.prepared = FALSE,
           add.gistic2.mut = NULL, mut.pipeline = "mutect2",
           mutant_variant_classification = c("Frame_Shift_Del", "Frame_Shift_Ins",
                                             "Missense_Mutation", "Nonsense_Mutation", "Splice_Site", "In_Frame_Del",
                                             "In_Frame_Ins", "Translation_Start_Site", "Nonstop_Mutation"))

The GDCprepare function gives the error: 
0%Error in date_names_lang(date_names) : 
  cannot open file '~/R/win-library/3.5/readr/R/sysdata.rdb': No such file or directory
