### ISSUE TITLE
The package doesn't work.

### ISSUE THREAD

**Issue by zh9118** [BioinformaticsFMRP/TCGAbiolinks#277]
Hi,
I tried to search and download TCGA data using this package. The same code worked before doesn't work anymore. The GDCquery() returns NAs, and GDCdownload() gives an error saying "TCGAbiolinks.rdb' is corrupt". Also, I even couldn't find the package on Bioconductor any longer. Can I get some help? Thanks.

**Comment by zh9118** [comment]
Actually, it works on other machines.

**Comment by Melkiades** [comment]
This a general error, which often happens to me in Rstudio. I do not think it is related to the package at all. It is enough to restart the R session to fix it. For the next time please post only issues with a minimal and reproducible code example :)
