### ISSUE TITLE
 TCGAbiolinks TCGAanalyze_Preprocessing 

### ISSUE THREAD

**Issue by DaydayupNo1** [BioinformaticsFMRP/TCGAbiolinks#284]
Hi TCGAbiolinks!

I want to download ESCA and miRNA data, and analyze differentially expression genes according to G staging. But I have a problem with TCGAanalyze_Preprocessing.  I run the following code with version 2.8.4:

 ### ### 
 library("TCGAbiolinks", lib.loc="~/R/x86_64-redhat-linux-gnu-library/3.4")
> library(SummarizedExperiment)
> query <- GDCquery(project = "TCGA-ESCA",
+                   legacy = TRUE,
+                   data.category = "Gene expression",
+                   data.type = "miRNA gene quantification",
+                   file.type = "hg19.mirbase20"
+                   )
--------------------------------------
o GDCquery: Searching in GDC database
--------------------------------------
Genome of reference: hg19
--------------------------------------------
oo Accessing GDC. This might take a while...
--------------------------------------------
ooo Project: TCGA-ESCA
--------------------
oo Filtering results
--------------------
ooo By data.type
ooo By file.type
----------------
oo Checking data
----------------
ooo Check if there are duplicated cases
ooo Check if there results for the query
-------------------
o Preparing output
-------------------
> GDCdownload(query = query)
Downloading data for project TCGA-ESCA
Of the 195 files for download 195 already exist.
All samples have been already downloaded
> esca.hg19.mirbase20<- GDCprepare(query,save = TRUE, save.filename = "escaExphg19mirbase20.rda")
  |================================================================================================| 100%Saving file:escaExphg19mirbase20.rda
File saved
> dataSubt <- TCGAquery_subtype(tumor = "ESCA")
esca subtype information from:doi:10.1038/nature20805
> dataClin <- GDCquery_clinic(project = "TCGA-ESCA","clinical")
> dataPrep <- TCGAanalyze_Preprocessing(object = esca.hg19.mirbase20, cor.cut = 0.6)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘assays’ for signature ‘"data.frame"’
### ### 
I found  the similar errors, I try to run the command in that issue according to your advise:
### ### 
 library(SummarizedExperiment)
 assays(dataPrep)
### ### 
the error is still not solved.
Then I copied the code from the Case Study n.1, surprisingly, this error did not appear.  May be some errors in my code ? How can I solve this problem?
please give me a hand.
Think you very much!

**Comment by AnkitaShukla17** [comment]
Can you please tell how you resolved the above problem, as I am facing same error.

**Comment by AnkitaShukla17** [comment]
In GDCprepare set summarizedExperiment = TRUE, the following error will not occur anymore.
