### ISSUE TITLE
GDCprepare() failure on TCGA-LIHC

### ISSUE THREAD

**Issue by biochemist992** [BioinformaticsFMRP/TCGAbiolinks#292]
Hi,
I am trying to download and prepare "Gene Expression Quantification" using the following script:

```
query.exp <- GDCquery(project = "TCGA-LIHC", 
                       legacy = TRUE,
                       data.category = "Gene expression",
                       data.type = "Gene expression quantification",
                       platform = "Illumina HiSeq", 
                       file.type = "results",
                      experimental.strategy = "RNA-Seq",
                     sample.type = c("Primary solid Tumor","Solid Tissue Normal"))
GDCdownload(query.exp)
lihc.exp <- GDCprepare(query = query.exp, save = TRUE, save.filename = "lihcExp.rda")

```
The data download seems to work, however, after the last command line I keep getting this error:

Error in fix.by(by.y, y) : 'by' must specify a uniquely valid column

Is there any way to fix this issue?

Thank you very much!

**Comment by tiagochst** [comment]
It seems emsembl database is not available http://status.ensembl.org/

<img width="1424" alt="screen shot 2019-02-04 at 10 20 31 am" src="https://user-images.githubusercontent.com/145529/52221329-8e425d80-2866-11e9-8a96-940a3891401d.png">

**Comment by tiagochst** [comment]
I made an update in the code to use other mirror for hg19. You should update the package with `devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")`

**Comment by Rahel14350** [comment]
Hi,
I have the same error with TCGA-PRAD, I did update the package but still I have the same error. Any other suggestion?
MAny thanks in advance, Rahel
