### ISSUE TITLE
GDCquery_Maf not retrieving MAF files

### ISSUE THREAD

**Issue by D0g4** [BioinformaticsFMRP/TCGAbiolinks#305]
Hi, there
Thanks for the neat package, Tiago! However, I am not quite sure what is going on.
Whenever I use the function "GDCquery_Maf" it does not retrieve a maf class object. Instead, I get the following:

> maf <- GDCquery_Maf("OV", pipelines = "varscan2")
> class (maf)
> [1] "spec_tbl_df" "tbl_df"      "tbl"         "data.frame"

Is there anything that I am missing?
Thanks a lot in advance!

**Comment by tiagochst** [comment]
It is working here. 


<img width="679" alt="Screen Shot 2019-03-22 at 4 27 07 PM" src="https://user-images.githubusercontent.com/145529/54848171-5a5cb380-4cbf-11e9-9826-594e9880ec45.png">


Which TCGAbiolinks version do you have ? Also, can you check if the data was downloaded ? The data should be in the **GDCdata/TCGA-OV/harmonized/Simple_Nucleotide_Variation/Masked_Somatic_Mutation/a8f41106-633d-4027-9e1f-e73bfd48f11e/** folder

**Comment by DarioS** [comment]
You are expecting the object to have a particular class but that isn't what the function returns by design. See the documentation.

>**Value**
>A data frame with the maf file information

It's not some complicated S4 object, but simply a data frame of the tibble variety. The function worked correctly.
