### ISSUE TITLE
Question install and use  TCGAbiolinks

### ISSUE THREAD

**Issue by YangZX88** [BioinformaticsFMRP/TCGAbiolinks#31]
Hi, question with using packagesTCGAbiolinks, error like this:
1) when I use function GDCquery_Maf(), it appears: cannot open URL 'https://gdc-api.nci.nih.gov/data//abbe72a5-cb39-48e4-8df5-5fd2349f2bb2'
2) using TCGAquery_investigate(): could not find function "TCGAquery_investigate"
I install the packages with order: biocLite("TCGAbiolinks"), is there any other packages need to install?

very thanks !
Yang

**Comment by tiagochst** [comment]
Hi, 

1) I updated recently the method to download the Maf files, we had several connections problems this week and I tried to improve the code. However, the code is not in Bioconductor yet. 
Please, could you use the github version and see if it is working ?
`devtools::install_github(repo = "BioinformaticsFMRP/TCGAbiolinks")`

2) We just removed TCGAquery_Investigate (there was a difference in the name from the vignette and the code, sorry for that) and TGCA_profilePlot from the code. We had a problem with the limit size of the package and we had to prioritize some functions.

You're welcome,
Tiago

**Comment by YangZX88** [comment]
Hi, Tiago


It works with the new script,thanks!

But in running TCGAvisualize_oncoprint() commond, error like this:

[cid:397cffc0-ef39-4940-a95c-8274f3fcc94d]

BTW, commond : mut <- GDCquery_Maf(tumor = "ACC") must be handled, because mut can not be recognizes as an obj in R


Best

Yang



Yang Zhenxing

Department of Urology
Xinqiao Hospital
Third Military Medical University
Chongqing, 400037, PR China

Tel:+86 18290442322
Fax: 023-68774453
yangzx88@hotmail.com



________________________________

**Comment by tiagochst** [comment]
Hi,

I believe there is an image missing in the last post.

mut is a tibble object, it should be recognized. Does `library(readr)` works? 

```
> class(mut)
[1] "tbl_df"     "tbl"        "data.frame"
```

Best,
Tiago

**Comment by tiagochst** [comment]
Hi,

Is this last version working for you?
```
devtools::install_github(repo = "BioinformaticsFMRP/TCGAbiolinks")
library(TCGAbiolinks)
acc.muse.maf <- GDCquery_Maf("ACC", pipelines = "muse")
```
Best regards,
Tiago

**Comment by YangZX88** [comment]
Hi, Tiago,

It works,thanks!

Yang


Yang Zhenxing

Department of Urology
Xinqiao Hospital
Third Military Medical University
Chongqing, 400037, PR China

Tel:+86 18290442322
Fax: 023-68774453
yangzx88@hotmail.com



________________________________
