### ISSUE TITLE
GDCprepare problem

### ISSUE THREAD

**Issue by lykosherdshep** [BioinformaticsFMRP/TCGAbiolinks#317]
This is my first time to use TCGAbiolinks in downloading data from TCGA database and It really makes it convenient to download data frome TCGA database, but it feels that there are some thing wrong when I used GDCprepare and I can't deal with. I have also Googled it, however, I can't find anything useful for me. It presents this error below when I use GDCprepare,

Starting to add information to samples
 => Add clinical information to samples
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match

I'm using R whose version is 3.6.0, Rstudio version 1.2.1335 and TCGAbiolinks version 2.12.1,and my code is below:

counts_query <- GDCquery(project = "TCGA-PRAD",
                           data.category = "Transcriptome Profiling",
                           data.type = "Gene Expression Quantification",
                           workflow.type = "HTSeq - Counts")
GDCdownload(counts_query, files.per.chunk = 8)
counts_prepare <- GDCprepare(counts_query)

Can anyone solve it?

**Comment by tiagochst** [comment]
Hi, do you have the lastest version from github ?
`devtools::install_github("BioinformaticsFMRP/TCGAbiolinks")`

The version seems right. I am running on my side now, but I think I solved it some days ago.

**Comment by lykosherdshep** [comment]
Yes, it done, I tried it with a TCGAbiolinks version of 2.13.2 installed to me, and the problem is dealed with, I'm very thanks for your assistance.
