### ISSUE TITLE
GDCprepare Problem

### ISSUE THREAD

**Issue by Z-0121** [BioinformaticsFMRP/TCGAbiolinks#318]
```
queryDown.BRCA <- GDCquery(project = CancerProject.BRCA,
                      data.category = "Transcriptome Profiling",
                      data.type = "Gene Expression Quantification",
                      experimental.strategy = "RNA-Seq", 
                      workflow.type = "HTSeq - FPKM-UQ",
                      barcode = c(dataSmTP.BRCA, dataSmNT.BRCA))
GDCdownload(query = queryDown.BRCA)

dataPrep.BRCA <- GDCprepare(query = queryDown.BRCA)
When I using GDCprepare, it has this error:
Error in rbindlist(l, use.names, fill, idcol) : 
  Item 2 has 57 columns, inconsistent with item 1 which has 58 columns. To fill missing columns use fill=TRUE.
```

**Comment by tiagochst** [comment]
Which version of the package are you using? 
If you could update the package with `devtools::install_github(repo = "BioinformaticsFMRP/TCGAbiolinks")`, I think it was solved some days ago.

Otherwise, please,  could you send me dataSmTP.BRCA, dataSmNT.BRCA objects so I can replicated the problem locally.

**Comment by tiagochst** [comment]
With version 2.12.1 is is working.

<img width="820" alt="Screen Shot 2019-06-13 at 10 46 05 AM" src="https://user-images.githubusercontent.com/145529/59447356-b6b80680-8dc8-11e9-9267-0eb488549d9d.png">

**Comment by Z-0121** [comment]
I use 
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("TCGAbiolinks", version = "3.8")

Do I need to change the version to 2.12.1?

**Comment by tiagochst** [comment]
Please run `devtools::install_github(repo = "BioinformaticsFMRP/TCGAbiolinks")`, I am not sure the bioconductor one is updated. It should be version 2.13.2.

**Comment by Z-0121** [comment]
I have already ran this code but it still have error like before. My dataSmNT.BRCA and dataSmTP.BRCA is:
dataSmNT.BRCA <- TCGAquery_SampleTypes(barcode = samplesDown.BRCA, typesample = "NT")
dataSmTP.BRCA <- TCGAquery_SampleTypes(barcode = samplesDown.BRCA, typesample = "TP")

Thank you so much!

**Comment by tiagochst** [comment]
And if you ran `packageVersion("TCGAbiolinks")` which version it gives you? 2.13.2?

**Comment by Z-0121** [comment]
I use this to install the "TCGAbiolinks", 

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("TCGAbiolinks", version = "3.8")

but when I use the code packageVersion("TCGAbiolinks"), it said Error in packageVersion("TCGAbiolinks") : 
  package ‘TCGAbiolinks’ not found

Then I use install.packages("TCGAbiolinks"), it has
Warning in install.packages :
  package ‘TCGAbiolinks’ is not available (for R version 3.5.3)

Do I need to change the R version using this package? Since I need to use other package at this version so do you have some suggestions to make this work?

**Comment by tiagochst** [comment]
Hi, could you run `BiocManager::install("BioinformaticsFMRP/'TCGAbiolinks")` the commnad you are running is installing an old version.

**Comment by Z-0121** [comment]
I ran this then ran 
> packageVersion("BioinformaticsFMRP/TCGAbiolinks")

Error in packageVersion("BioinformaticsFMRP/TCGAbiolinks") : 
  package ‘BioinformaticsFMRP/TCGAbiolinks’ not found

**Comment by Z-0121** [comment]
Could you please help me to solve this problem?

**Comment by tiagochst** [comment]
But you need to run `BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")` not packageVersion("BioinformaticsFMRP/TCGAbiolinks")

**Comment by Z-0121** [comment]
I have already ran this.

**Comment by tiagochst** [comment]
OK, so if you restart R, rerun the code it does not work?

**Comment by Z-0121** [comment]
I restart r and ran this again
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")

These packages have more recent versions available.
Which would you like to update?

1:   mime (0.6 -> 0.7) [CRAN]

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 1
After installing the package I tried:
> library("BioinformaticsFMRP/TCGAbiolinks")
Error in library("BioinformaticsFMRP/TCGAbiolinks") : 
  there is no package called ‘BioinformaticsFMRP/TCGAbiolinks’

**Comment by tiagochst** [comment]
it should be`library("TCGAbiolinks")`

**Comment by Z-0121** [comment]
> library("TCGAbiolinks")
Error in library("TCGAbiolinks") : 
  there is no package called ‘TCGAbiolinks’
Same Error...

**Comment by Z-0121** [comment]
Which R version do I need to use to implement this package?

**Comment by Z-0121** [comment]
I review the Package ‘TCGAbiolinks’ documents it Depends R (>= 3.2). My R version is R version 3.5.3 (2019-03-11). I am confused why it cannot find my package after I install it.

**Comment by Z-0121** [comment]
When I running:
>BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")
It has this in Console:
Error in lazyLoadDBinsertVariable(vars[i], from, datafile, ascii, compress,  : 
  (converted from warning) internal error 10 in R_compress3
ERROR: unable to build sysdata DB for package 'TCGAbiolinks'
* removing 'C:/Users/ZhouW/Documents/R/win-library/3.5/TCGAbiolinks'
In R CMD INSTALL
Update all/some/none? [a/s/n]:

**Comment by tiagochst** [comment]
What R version do you have?

**Comment by tiagochst** [comment]
The new version I think depends on R > 3.5 or 3.6

**Comment by Z-0121** [comment]
I have already found the what is the problem is. I used R 3.5.3 before, but it does not work. Now I change to 3.6.0 it works! Thank you!
