### ISSUE TITLE
Could not find function "content"

### ISSUE THREAD

**Issue by Z-0121** [BioinformaticsFMRP/TCGAbiolinks#320]
> queryDown.BLCA <- GDCquery(project = CancerProject.BLCA,
                       data.category = "Transcriptome Profiling",
                       data.type = "Gene Expression Quantification",
                       experimental.strategy = "RNA-Seq", 
                       workflow.type = "HTSeq - FPKM-UQ")

Error in content(getURL(url, GET, timeout(600)), as = "text", encoding = "UTF-8") : 
  could not find function "content"

Could you please tell me where is the content function?

Thank you in advance!

**Comment by tiagochst** [comment]
content is important from httr package. So that problem should not exists. If you do `library(httr)` the problem persists?
