### ISSUE TITLE
Urgent: GDCquery access problem!!!

### ISSUE THREAD

**Issue by Z-0121** [BioinformaticsFMRP/TCGAbiolinks#321]
> queryDown.BLCA <- GDCquery(project = CancerProject.BLCA,
                       data.category = "Transcriptome Profiling",
                       data.type = "Gene Expression Quantification",
                       experimental.strategy = "RNA-Seq", 
                       workflow.type = "HTSeq - FPKM-UQ",
                       access = "controlled")

GDCquery: Searching in GDC database
Genome of reference: hg38
Accessing GDC. This might take a while...
Project: TCGA-BLCA

**Sorry! There is no result for your query. Please check in GDC the data available or if there is no error in your query.**

Hope you can help me!!! Thank you in advance!!!

**Comment by tiagochst** [comment]
The access to the  HTSeq - FPKM-UQ  is not controlled. 
<img width="356" alt="Screen Shot 2019-06-15 at 10 43 49 AM" src="https://user-images.githubusercontent.com/145529/59553440-81dbb900-8f5a-11e9-96cc-121d6059c3ec.png">

**Comment by Z-0121** [comment]
Thank you for your clarification. After I change the parameters to 
>queryDown.BLCA <- GDCquery(project = CancerProject.BLCA,
                      data.category = "Sequencing Reads",
                      experimental.strategy = "RNA-Seq", 
                      access = "controlled")
And try to use GDCdownload function with parameter query, token.file and directory to download the data. It has error:
Downloading data for project TCGA-BLCA
GDCdownload will download 433 files. A total of 3.147154953538 TB
The total size of files is big. We will download files in chunks
At least one of the chunks download was not correct. We will retry
Error in 0:ceiling(nrow(manifest)/step - 1) : 
  result would be too long a vector

Hope you can help me! Thank you!

**Comment by tiagochst** [comment]
You are trying to download the BAM files ? You need to set `method = "client"`.

**Comment by tiagochst** [comment]
Also, to download controlled access data you need the token.
