### ISSUE TITLE
error in GDCprepare for TCGA-PRAD project

### ISSUE THREAD

**Issue by martaluc** [BioinformaticsFMRP/TCGAbiolinks#325]
I am trying to run the following code to download the TCGA-PRAD data:
```

query_PRAD <- GDCquery(project = "TCGA-PRAD",
                        data.category = "Transcriptome Profiling",
                        data.type = "Gene Expression Quantification",
                        workflow.type = "HTSeq - Counts",
                        sample.type = c("Primary solid Tumor","Solid Tissue Normal"))

GDCdownload(query_PRAD)
data_PRAD <- GDCprepare(query_PRAD,save = TRUE, save.filename = paste0("pradExp_harmonized_",Sys.Date(),".rda"))

```
and I get the following error after running the GDCprepare function:

Starting to add information to samples
 => Add clinical information to samples
Error in rbindlist(l, use.names, fill, idcol) : 
  Item 2 has 57 columns, inconsistent with item 1 which has 58 columns. To fill missing columns use fill=TRUE.

How can I solve it? 
Thank you very much

**Comment by tiagochst** [comment]
How, you should update the package version with the one in Github. The API from GDC was updated and some behaviors changed.

Just install the new version, restart R and it should work. I just tested it on my side.
```
if (!requireNamespace("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")
```

**Comment by martaluc** [comment]
Thanks a lot for the super fast answer!!! Now it works
