### ISSUE TITLE
GDCprepare killed

### ISSUE THREAD

**Issue by Aashilbatavia** [BioinformaticsFMRP/TCGAbiolinks#334]
Hi 
i wanted to get the pan kidney cancer methylation data (KIRC + KIRP+KICH). I downloaded all the files successful, however, when it comes to preparing them it just gets killed during or following the:
Joining, by = c("Composite.Element.REF", "Gene_Symbol", "Chromosome", "Genomic_Coordinate") 
steps.(i think it just crashes) 

I installed TCGAbiolinks from GitHub just a few days ago and am using R 3.5.3. 

query.met.KIPAN <- GDCquery(project = c("TCGA-KIRC","TCGA-KICH","TCGA-KIRP") ,
                           legacy = TRUE,
                           data.category = "DNA methylation",
                           platform = "Illumina Human Methylation 450",
                           sample.type = "Primary solid Tumor")
GDCdownload(query.met.KIPAN)

met.KIPAN.450.all <- GDCprepare(query = query.met.KIPAN,
                               save = TRUE,
                               save.filename = "KIPAN_DNAmet450kall_All_Tumours.rda",
                               summarizedExperiment = TRUE)

when i try each one individually its successful

I was wondering if you know what the issue may be or if i can get around this somehow e.g. combining them following individual preparation

Thanks

**Comment by tiagochst** [comment]
Hello,

How much RAM the computer has? The data is close to 14GB. 
I would suggest to do a prepare for each tumor and then bind the summarziedExperiment objects.
The internal code is using a left join which will take more memory than a cbind. 

```
library(TCGAbiolinks)
library(SummarizedExperiment)

for(proj in c("TCGA-KIRC","TCGA-KICH","TCGA-KIRP")){
  query.met <- GDCquery(project = proj ,
                        legacy = TRUE,
                        data.category = "DNA methylation",
                        platform = "Illumina Human Methylation 450",
                        sample.type = "Primary solid Tumor")
  GDCdownload(query.met)
  
  data <- GDCprepare(query = query.met,
                     save = TRUE,
                     save.filename = paste0(proj,"_450K_hg19.rda"),
                     summarizedExperiment = TRUE)
  
  variable <- paste0("met_", gsub("-","_",proj))
  assign(variable,data)
}

# Just checking if the rownames are in the same order
all(rownames(met_TCGA_KICH) == rownames(met_TCGA_KIRP))
all(rownames(met_TCGA_KICH) == rownames(met_TCGA_KIRC))


all.met <- cbind(assay(met_TCGA_KICH),assay(met_TCGA_KIRP),assay(met_TCGA_KIRC))
rowRanges <- rowRanges(met_TCGA_KICH)
colData <- colDataPrepare(colnames(all.met))

met.KIPAN.450.all  <- SummarizedExperiment(assays = all.met,
                                           colData = colData,
                                           rowRanges = rowRanges)
```

**Comment by Aashilbatavia** [comment]
Hey Thanks for this, 
I have 32gb ram so i thought it would be able to manage it but this is probably better anyway. 
cheers!
