### ISSUE TITLE
Error in adding clinical information to methylation data

### ISSUE THREAD

**Issue by ldanilova** [BioinformaticsFMRP/TCGAbiolinks#337]
Hello,

I have a problem in adding clinical information to a SummarizedExperiment object when I use GDCprepare with harmonized DNA methylation data of several cancer types, e.g. THCA, BRCA and others. The methylation files are downloaded and processed, but on the step of adding clinical information I'm getting the following error:
Add clinical information to samples
<simpleError in rbindlist(l, use.names, fill, idcol): Item 2 has 58 columns, inconsistent with item 1 which has 57 columns. To fill missing columns use fill=TRUE.>

I'm using TCGAbiolinks_2.10.5. Could you advise how to fix that?

Thank you!
Ludmila

**Comment by tiagochst** [comment]
Hello Ludmila,

That bug was fixed last month can you update with the last version with:
`BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")`

Best regards,
Tiago
