### ISSUE TITLE
GDCPrepare Error! legacy?SummarizedExperiment?

### ISSUE THREAD

**Issue by doctorlqh** [BioinformaticsFMRP/TCGAbiolinks#338]
The following error occurs while trying to  prepare "Gene expression" data.
library(TCGAbiolinks)
library(SummarizedExperiment)
query.exp <- GDCquery(project = "TCGA-LGG",
                      legacy = TRUE,
                      data.category = "Gene expression",
                      data.type = "Gene expression quantification",
                      platform = "Illumina HiSeq",
                      file.type = "results",
                      experimental.strategy = "RNA-Seq",
                      sample.type = "Primary solid Tumor")
GDCdownload(query.exp, method = "api", files.per.chunk = 5)
lgg.exp <- GDCprepare(query = query.exp, save = TRUE, save.filename = "lggExp.rda")
#|==================================================================| 100%Accessing grch37.ensembl.org to get gene information
#Downloading genome information (try:0) Using: Human genes (GRCh37.p13)
#Error in fix.by(by.y, y) : 'by' must specify a uniquely valid column

I found that if"legacy=TRUE", error occurs when running"GDCprepare(...,summarizedExperiment=TRUE)">

Can you help me? Thanks a lot

**Comment by tiagochst** [comment]
Hello,

could you update the package with `BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")`
I believe this problem was solved some weeks ago.

Best regards,
Tiago

**Comment by doctorlqh** [comment]
thanks!!
the problem has been solved.
