### ISSUE TITLE
 TCGAbiolinks to download older builds (Version) from GDC 

### ISSUE THREAD

**Issue by archanabhardwaj** [BioinformaticsFMRP/TCGAbiolinks#344]
Hi, 
At firebrowse, multiple TCGA data version are  available at  http://gdac.broadinstitute.org/runs/

Is it possible to download GDC data of different build (version) via TCGAbiolinks  ?

**Comment by tiagochst** [comment]
Hi,

No, TCGAbiolinks only access the legacy archive and the latest version of the harmonized database.

I don't believe it is even possible to access old build (version) via GDC website.
