### ISSUE TITLE
GDCprepare error with duplicated samples

### ISSUE THREAD

**Issue by mikyzo88** [BioinformaticsFMRP/TCGAbiolinks#348]
Hi, I'm trying to do some analyses with TCGA-PRAD data, but i got an error doing the GDCprepare function because of duplicated samples. Here is my code:

```
query.PRAD.exp <- GDCquery(project = "TCGA-PRAD",
                            legacy = TRUE,
                            data.category = "Gene expression",
                            data.type = "Gene expression quantification",
                            platform = "Illumina HiSeq", 
                            file.type = "results",
                            sample.type = c("Primary solid Tumor", "Solid Tissue Normal"))
--------------------------------------
o GDCquery: Searching in GDC database
--------------------------------------
Genome of reference: hg19
--------------------------------------------
oo Accessing GDC. This might take a while...
--------------------------------------------
ooo Project: TCGA-PRAD
--------------------
oo Filtering results
--------------------
ooo By platform
ooo By data.type
ooo By file.type
ooo By sample.type
----------------
oo Checking data
----------------
ooo Check if there are duplicated cases
Warning: There are more than one file for the same case. Please verify query results. You can use the command View(getResults(query)) in rstudio
ooo Check if there results for the query
-------------------
o Preparing output
-------------------
> GDCdownload(query.PRAD.exp)
Downloading data for project TCGA-PRAD
GDCdownload will download 557 files. A total of 844.675214 MB
Downloading as: Mon_Sep__9_11_44_25_2019.tar.gz
Downloading: 340 MB     
> PRAD.exp <- GDCprepare(query = query.PRAD.exp, 
                       save = TRUE, 
                      save.filename = "PRADexp.rda")


|    |tags                            |cases                        |experimental_strategy |
|:---|:-------------------------------|:----------------------------|:---------------------|
|111 |c("unnormalized", "gene", "v2") |TCGA-HC-7740-01B-04R-2302-07 |Total RNA-Seq         |
|377 |c("unnormalized", "gene", "v2") |TCGA-HC-7740-01B-04R-2302-07 |Total RNA-Seq         |
|12  |c("unnormalized", "gene", "v2") |TCGA-HC-8258-01B-05R-2302-07 |Total RNA-Seq         |
|490 |c("unnormalized", "gene", "v2") |TCGA-HC-8258-01B-05R-2302-07 |Total RNA-Seq         |
|60  |c("unnormalized", "gene", "v2") |TCGA-HC-8261-01B-05R-2302-07 |Total RNA-Seq         |
|127 |c("unnormalized", "gene", "v2") |TCGA-HC-8261-01B-05R-2302-07 |Total RNA-Seq         |
|269 |c("unnormalized", "gene", "v2") |TCGA-HC-8265-01B-04R-2302-07 |Total RNA-Seq         |
|350 |c("unnormalized", "gene", "v2") |TCGA-HC-8265-01B-04R-2302-07 |Total RNA-Seq         |
Error in GDCprepare(query = query.PRAD.exp, save = TRUE, save.filename = "PRADexp.rda") : 
  There are samples duplicated. We will not be able to prepare it
```

How can I solve the issue or access to the query data and manually remove the duplicated samples??

Thank you!

**Comment by tiagochst** [comment]
Some samples have two experimental strategies experiments (RNA-Seq and Total RNA-Seq). You should filter to a single one.

```
query.PRAD.exp <- GDCquery(project = "TCGA-PRAD",
                           legacy = TRUE,
                           data.category = "Gene expression",
                           data.type = "Gene expression quantification",
                           platform = "Illumina HiSeq", 
                           file.type = "results",
                           experimental.strategy = "RNA-Seq",
                           sample.type = c("Primary solid Tumor", "Solid Tissue Normal"))
```

**Comment by mschubert** [comment]
I'm having the same issue. I see your suggestion, but the duplication does not seem to stem from different RNA-seq strategies?

```r
|111 |c("unnormalized", "gene", "v2") |TCGA-HC-7740-01B-04R-2302-07 |Total RNA-Seq
|377 |c("unnormalized", "gene", "v2") |TCGA-HC-7740-01B-04R-2302-07 |Total RNA-Seq
```

This is duplicated, yet both are the same strategy. So the reason for the duplication has to be something else?

**Comment by tiagochst** [comment]
There might be a problem in the error message. I'll double check.

These are the files we have for that patient
<img width="963" alt="Screen Shot 2019-09-10 at 8 20 34 AM" src="https://user-images.githubusercontent.com/145529/64609711-eb296780-d3a3-11e9-9d7b-ce0191f512dd.png">

**Comment by tiagochst** [comment]
I am not sure what is the difference of that case. [Even looking at the GDC legacy archive I did not find any clue].(
https://portal.gdc.cancer.gov/legacy-archive/search/f?filters=%7B%22op%22:%22and%22,%22content%22:%5B%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22cases.case_id%22,%22value%22:%5B%2291e249a6-b0b0-487e-9fad-0e9f5798dcae%22%5D%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.data_category%22,%22value%22:%5B%22Gene%20expression%22%5D%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.experimental_strategy%22,%22value%22:%5B%22Total%20RNA-Seq%22%5D%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.data_type%22,%22value%22:%5B%22Gene%20expression%20quantification%22%5D%7D%7D%5D%7D
)

<img width="1436" alt="Screen Shot 2019-09-10 at 8 32 11 AM" src="https://user-images.githubusercontent.com/145529/64610419-91c23800-d3a5-11e9-9425-af7fd0c0b814.png">

This is the API information from GDC. 
<img width="963" alt="Screen Shot 2019-09-10 at 8 20 34 AM" src="https://user-images.githubusercontent.com/145529/64610526-ca621180-d3a5-11e9-8165-e9af6f4fc917.png">
 
Sorry I cannot help, but if you want to investigate the problem, I think it is better to send an email to GDC: support@nci-gdc.datacommons.io

**Comment by mikyzo88** [comment]
Thank you @tiagochst !
