### ISSUE TITLE
about the p-value in "TCGAanalyze_survival"

### ISSUE THREAD

**Issue by xiexiaowei** [BioinformaticsFMRP/TCGAbiolinks#35]
Hi,
Showing my great gratitudes for your versatile and updated "TCGAbiolinks".
I have two question:
1. The Log-Rank P-value from "TCGAanalyze_survival" can be directly used for next analysis?
   I mean, if the p-value in figure < 0.05, the "clusterCol" is associated with survival, is this right?
2. As regards "TCGAanalyze_survival" and "TCGAanalyze_SurvivalKM",
   I used "TCGAanalyze_survival" a few days ago.
   In recent days, I see the "TCGAanalyze_SurvivalKM", which can be used to find survival genes.
   What's the brief difference between them, or they are the similar?

**Comment by tiagochst** [comment]
About question 2: They are similar. Both use functions from the [survival package ](https://cran.r-project.org/web/packages/survival/index.html) in CRAN, but they were written by two different groups/persons.

The functions used are in both are:

- Surv
- survfit

The differences are:

- TCGAanalyze_SurvivalKM will take into account the gene expression. For each gene, it will take 3 groups  High, intermediate, and low expression and do the survival analysis.
- For the p-value both use functions from the survival package. However, TCGAanalyze_SurvivalKM uses the **survdiff** function while TCGAanalyze_survival  uses the p-value of the Score (logrank) test from the **coxph** function. I'm not expert in survival analysis, but this difference is described [here](http://stats.stackexchange.com/questions/26780/difference-between-survdiff-log-rank-and-coxph-log-rank). 

Maybe another member might give you a better explanation, but both functions should give the same P-values. I made an example below with the same data.

<img width="446" alt="screen shot 2016-10-18 at 10 40 52 am" src="https://cloud.githubusercontent.com/assets/145529/19489325/ace932c2-951f-11e6-992b-ac37e528b366.png">

**Comment by tiagochst** [comment]
What I gathered on the question 1, with researchers from my laboratory:

"The p-value of survival tells if there is a difference between the pre-defined groups. The p-value does not define the groups. You define the groups and test p-value"

And instead of "clusterCol" is associated with survival, it would be the survival is associated with "clusterCol".

@torongs82 Do you have a better explanation for both questions ?
