### ISSUE TITLE
GDCprepare didn't work in TARGET-NBL RNA-Seq counts data

### ISSUE THREAD

**Issue by jianguozhouzunyimedicaluniversity** [BioinformaticsFMRP/TCGAbiolinks#353]
```
#####GDCprepare ######
query <- GDCquery(project = "TARGET-NBL",
data.category = "Transcriptome Profiling",
data.type = "Gene Expression Quantification",
workflow.type = "HTSeq - Counts")
destdir=file.path(getwd()) 
GDCdownload(query, directory =destdir ) 
TARGET_NBL_RNA_Seq_Counts <- GDCprepare(query, directory = destdir )

```
AND the work
|====================================================================================|100%                      Completed after 21 s 
Starting to add information to samples
Adding description to TARGET samples
 => Add clinical information to samples
Add FFPE information. More information at: 
=> https://cancergenome.nih.gov/cancersselected/biospeccriteria 
=> http://gdac.broadinstitute.org/runs/sampleReports/latest/FPPP_FFPE_Cases.html
Accessing www.ensembl.org to get gene information
Downloading genome information (try:0) Using: Human genes (GRCh38.p13)
From the 60483 genes we couldn't map 3971

but coud not map the gene by GRCh38.p13 @tiagochst

**Comment by jianguozhouzunyimedicaluniversity** [comment]
@jianguozhouzunyimedicaluniversity

**Comment by jianguozhouzunyimedicaluniversity** [comment]
@tiagochst

**Comment by tiagochst** [comment]
Sorry, I did not understand the issue. The gene ensemble IDs were mapped.

![Screenshot from 2019-10-02 09-00-40](https://user-images.githubusercontent.com/145529/66046161-262a4100-e4f3-11e9-9381-0d0941e4d397.png)

**Comment by jianguozhouzunyimedicaluniversity** [comment]
Thanks for your reply.
but the assays did  not have any data.
> TARGET_NBL_RNA_Seq_Counts@assays
Reference class object of class "ShallowSimpleListAssays"
Field "data":
List of length 1
names(1): HTSeq - Counts
Warning messages:
1: In class(object) <- "environment" :
  Setting class(x) to "environment" sets attribute to NULL; result will no longer be an S4 object
2: In class(object) <- "environment" :
  Setting class(x) to "environment" sets attribute to NULL; result will no longer be an S4 object

> TARGET_NBL_RNA_Seq_Counts@metadata
$data_release
[1] "Data Release 19.0 - September 17, 2019"

> TARGET_NBL_RNA_Seq_Counts@assays
Reference class object of class "ShallowSimpleListAssays"
Field "data":
List of length 1
names(1): HTSeq - Counts
@tiagochst

**Comment by tiagochst** [comment]
if you do `head(assay(TARGET_NBL_RNA_Seq_Counts))[1:5,1:5]` you got no data ? 
![Screenshot from 2019-10-02 10-37-12](https://user-images.githubusercontent.com/145529/66053598-9c817000-e500-11e9-8faf-7f8760cadee8.png)

**Comment by jianguozhouzunyimedicaluniversity** [comment]
it is workthanksbest wishes
Jian-Guo ZHOU
Department of Oncology, Affiliated Hospital of Zunyi Medical University
Address: NO.149, Dalian Road, Zunyi City, Guizhou Province, China, 563000
Email: jianguo.zhou@yahoo.com
 

    Tiago Chedraoui Silva <notifications@github.com> 于 2019年10月2日星期三 GMT+2 下午04:37:55写道：  
 
 
if you do head(assay(TARGET_NBL_RNA_Seq_Counts))[1:5,1:5] you got no data ?
