### ISSUE TITLE
package is not installed properly on jupyter notebook

### ISSUE THREAD

**Issue by rojinsafavi** [BioinformaticsFMRP/TCGAbiolinks#357]
I am trying to install TCGAbiolinks package on jupyter notebook, but it gives me an error for shortreads package. I was able to successfully install shortreads package in another way, but I was wondering if there is a way to not let the TCGAbiolinks reinstall shortreads?

**Comment by Melkiades** [comment]
If the package is already installed, the installation should not reinstall the dependencies. This only if it is the correct version. Please check that and, if you really want to try to avoid the installation of missing dependencies it is possible to use `install.packages` argument `dependencies = FALSE` which does simply that.
