### ISSUE TITLE
XML parsing problem

### ISSUE THREAD

**Issue by bigwiz83** [BioinformaticsFMRP/TCGAbiolinks#36]
Hello, I think TCGABiolinks is marvellous R-package.
However, I got a problem when I was trying to get clinical information such as radiation.

===
query1 <- GDCquery(project = "TCGA-GBM",
legacy = TRUE,
data.category = "Gene expression",
data.type = "Gene expression quantification",
platform = "AgilentG4502A_07_1",
sample.type = "Primary solid Tumor")

GDCdownload(query1)

(Until here it's o.k., But.. )

clinical <- GDCprepare_clinic(query, clinical.info = "radiation")

(After above command, I get followed error message.)

exception: Start tag expected, '<' not found [4]

===

Your example at tutorial works fine. 
But my case is not working due to XML parsing problem, i think.
How can I solve this problem?

It would be really helpful if this problem solved.
Thank you in advance.

**Comment by tiagochst** [comment]
GDCprepare_clinic will receive only files from data caregory Clinical and biospecimen.
It should be:

```
query1 <- GDCquery(project = "TCGA-GBM",data.category = "Clinical")
GDCdownload(query1)
clinical <- GDCprepare_clinic(query, clinical.info = "radiation")
```

**Comment by bigwiz83** [comment]
Thank you very much.
It really helped!

Sincerely,

2016-10-22 10:00 GMT+09:00 Tiago Chedraoui Silva <notifications@github.com>:
