### ISSUE TITLE
Fail to upload package TCGAbiolinks: no package "digest" found

### ISSUE THREAD

**Issue by anaiswanet** [BioinformaticsFMRP/TCGAbiolinks#362]
Hello,

I'm trying to install the package TCGAbiolinks here's what I get (translated from french), see error in last lane

> BiocManager::install("TCGAbiolinks")
Bioconductor version 3.9 (BiocManager 1.30.9), R 3.6.1 (2019-07-05)
Installing package(s) 'TCGAbiolinks'
essai de l'URL 'https://bioconductor.org/packages/3.9/bioc/bin/macosx/el-capitan/contrib/3.6/TCGAbiolinks_2.12.6.tgz'
Content type 'application/x-gzip' length 61635145 bytes (58.8 MB)
==================================================
downloaded 58.8 MB

The downloaded binary packages are in
	/var/folders/4h/dl_pnk_x5hx54lqlfd404tm40000gn/T//RtmpAqz6nH/downloaded_packages
> library(TCGAbiolinks)
Registered S3 method overwritten by 'R.oo':
  method        from       
  throw.default R.methodsS3
Error : package or namespace load failed for ‘TCGAbiolinks’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
no package named ‘digest’ found

Thanks for your help!

**Comment by tiagochst** [comment]
Normally those packages should be installed automatically.
If you run `BiocManager::install("TCGAbiolinks",dependencies = TRUE)` does it install digest ?
Otherwise, you can fix it by runing `BiocManager::install("digest")` and trying to reinstall `TCGAbiolinks`.
