### ISSUE TITLE
cpg mapping

### ISSUE THREAD

**Issue by rojinsafavi** [BioinformaticsFMRP/TCGAbiolinks#368]
Does TCGAbiolinks allow mapping of TCGA methylation probes to the CpG sites or genes?

**Comment by tiagochst** [comment]
For the annotation I normally use the annotation from Wanding Zhou:
[https://zwdzwd.github.io/InfiniumAnnotation](https://zwdzwd.github.io/InfiniumAnnotation) or [https://bioconductor.org/packages/sesameData/]( https://bioconductor.org/packages/sesameData/).

They will have genomic coordinates annotated and mapping to gene.
