### ISSUE TITLE
Error: could not find function "assay"and "assays "

### ISSUE THREAD

**Issue by ZHANGQiaosheng** [BioinformaticsFMRP/TCGAbiolinks#37]
I have downloaded TCGAbiolinks and but these GDC... functions do not work . 
What am I doing wrong?  for example,

BRCARnaseq_assay <- GDCprepare(query)
BRCAMatrix <- assay(BRCARnaseq_assay,"raw_counts")

Best regards

**Comment by tiagochst** [comment]
library(SummarizedExperiment)
BRCARnaseq_assay <- GDCprepare(query)
BRCAMatrix <- assay(BRCARnaseq_assay,"raw_counts")

**Comment by ZHANGQiaosheng** [comment]
Thank you so much. Greatly appreciate your help.

**Comment by adamfletcherUK** [comment]
I've got the SummarizedExperiment library's in place. However, when I type:

BRCAMatrix <- assay(BRCARnaseq_assay,"raw_counts")

this happens...

Error in assay(BRCARnaseq_assay, "raw_counts") : 
  'assay(<RangedSummarizedExperiment>, i="character", ...)' invalid subscript 'i'
'i' not in names(assays(<RangedSummarizedExperiment>))

**Comment by NatalieStephensonUoL** [comment]
I have the SummarizedExperiment library installed. However, when I type:

BRCAMatrix <- assay(BRCARnaseq_assay,"raw_counts")

This happens ... 
Error in assay(BRCARnaseq_assay, "raw_counts") : 
  'assay(<RangedSummarizedExperiment>, i="character", ...)' invalid subscript 'i'
'i' not in names(assays(<RangedSummarizedExperiment>))

Can someone help explain where I'm going wrong?

**Comment by NatalieStephensonUoL** [comment]
n/m figured it out!

Ran:
> assays(BRCARnaseq_assay)

Output:
List of length 2
names(2): raw_count scaled_estimate

i.e. ... should have been "raw_count"!

**Comment by torongs82** [comment]
Hi @NatalieStephensonUoL yes exactly you can use "raw_count" or consider names from assays(data).

**Comment by sharonteo** [comment]
In the vignette you have "assay(BRCARnaseq_assay,"raw_counts")" This did not work for me.

Instead I put assays(BRCARnaseq_assay,"raw_counts") and this worked.  Is there a typo in the vignette?

**Comment by JackieMium** [comment]
same question here.

**Comment by tiagochst** [comment]
Hi,

yes, there is a bug in the vignette code.

The correct code is either:
`assays(BRCARnaseq)[["raw_count"]]`
or 
`assay(BRCARnaseq,"raw_count")`

We'll fix it.
> assays(x), assays(x) <- value:
Get or set the assays. value is a list or SimpleList, each element of which is a matrix with the same dimensions as x.

> assay(x, i), assay(x, i) <- value:
A convenient alternative (to assays(x)[[i]], assays(x)[[i]] <- value) to get or set the ith (default first) assay element. value must be a matrix of the same dimension as x, and with dimension names NULL or consistent with those of x.

**Comment by tiagochst** [comment]
The problem was  the "raw_counts" instead of "raw_count"
<img width="577" alt="captura de tela 2017-02-27 as 14 29 16" src="https://cloud.githubusercontent.com/assets/145529/23372147/3256f14c-fcf9-11e6-93f7-c58514b955ae.png">
