### ISSUE TITLE
Error in GDCPepare

### ISSUE THREAD

**Issue by netphantom** [BioinformaticsFMRP/TCGAbiolinks#370]
Hi there, 
I am trying to reproduce the BRCA vignette. Unfortunately I have an error when lunching the GDCPrepare function.
Here is the code that I use

```
library(SummarizedExperiment)
library(TCGAbiolinks)

query <- GDCquery(project = "TCGA-BRCA", 
                      legacy = TRUE,
                      data.category = "Gene expression",
                      data.type = "Gene expression quantification",
                      platform = "Illumina HiSeq", 
                      file.type = "results",
                      experimental.strategy = "RNA-Seq",
                      sample.type = c("Primary Tumor","Solid Tissue Normal"))
GDCdownload(query)
brca <- GDCprepare(query = query, save = TRUE, save.filename = "brcaExp.rda")`

```
And this is the error I have:

`> brca.exp <- GDCprepare(query = query, save = TRUE, save.filename = "brcaExp.rda", add.gistic2.mut=FALSE)
  |======================================================================================================================================| 100%Accessing grch37.ensembl.org to get gene information
Downloading genome information (try:0) Using: Human genes (GRCh37.p13)
Starting to add information to samples
 => Add clinical information to samples
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match`

**Comment by tiagochst** [comment]
@netphantom Which version of the package do you have installed?
If it is not the 2.15.2, I would recommend updating it. 

Your code is still running on my side. I'll see if there is an error when it is done.

```
if (!requireNamespace("BiocManager", quietly=TRUE))
    install.packages("BiocManager")
BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")
```

**Comment by tiagochst** [comment]
Your code is working with version 2.15.2

![Screenshot from 2019-12-04 18-08-58](https://user-images.githubusercontent.com/145529/70189523-88edb380-16c1-11ea-95c7-b7660fdc5d1c.png)

**Comment by netphantom** [comment]
Hi @tiagochst , I installed the latest version of TCGABiolinks (2.15.2) and I'm using R 3.6.1.

**Comment by netphantom** [comment]
Ok, I think I got this. 
I followed these steps:
1) Removed TCGAbiolink (I installed it from bioconductor some weeks ago)
2) I closed and re-opened R and rstudio
3) I installed TCGAbilink again from github 
4) I updated all the packages it required
and it workeed.
