### ISSUE TITLE
TCGAbiolinks install error

### ISSUE THREAD

**Issue by Kathy-xin** [BioinformaticsFMRP/TCGAbiolinks#380]
Hello,I am trying to install the GCTAbiolinks, but there are some errors as the follow:
if (!requireNamespace("BiocManager", quietly=TRUE))
  install.packages("BiocManager")
BiocManager::install("TCGAbiolinks")
> library(TCGAbiolinks)
Error: package or namespace load failed for ‘TCGAbiolinks’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘GenomeInfoDbData’

What's more,I try to install the package GenomeInfoDbData, but there are still some errors:
> install.packages('GenomeInfoDbData')
Warning in install.packages :
  package ‘GenomeInfoDbData’ is not available (for R version 3.6.1)

I think biolinks will help me in my further work, and I need your help, thank you very much!

**Comment by tiagochst** [comment]
It seems GenomeInfoDbData is a Bioconductor package. 
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("GenomeInfoDbData")
```

http://bioconductor.org/packages/release/data/annotation/html/GenomeInfoDbData.html

**Comment by Kathy-xin** [comment]
Thank you! There are still some error when I try again. It shows that the R version need to be 3.6, but the version I installs is 3.6.1. How can I solve this problem? Thank you!
