### ISSUE TITLE
Error in TCGAquery_SampleTypes in MMRF-COMMPASS project 

### ISSUE THREAD

**Issue by MarzyUnicz** [BioinformaticsFMRP/TCGAbiolinks#382]
Dear Colleague,
I’m working with MMRF-COMMPASS project and I’m trying to use TCGAnalyze_DEA function.
To do that, I have to use the filter function TCGAquery_SampleTypes on which I get the following error:

“Error message: one or more sample types do not exis”

This is my code:
**library(TCGAbiolinks)
library(SummarizedExperiment)
library(dplyr)
library(DT)

query.mm <- GDCquery(project = "MMRF-COMMPASS",
data.category = "Transcriptome Profiling",
data.type = "Gene Expression Quantification",
workflow.type="STAR - Counts",
experimental.strategy = "RNA-Seq", 
legacy = F,
sample.type = c("Recurrent Blood Derived Cancer - Bone Marrow","Primary Blood Derived Cancer - Bone Marrow"))
GDCdownload(query.mm, method = "api", files.per.chunk = 10) 
DataMMRF <- GDCprepare(query = query.mm, save = TRUE, save.filename = "MMRFCompass.rda")
clinical_patient_Cancer_MMRF <- GDCquery_clinic("MMRF-COMMPASS","clinical")
dataSmTRBM <- TCGAquery_SampleTypes(getResults(query.mm,cols="cases"),"TRBM")  
dataSmTBM <- TCGAquery_SampleTypes(getResults(query.mm,cols="cases"),"TBM”)**

In this case dataSmTRBM and dataSmTBM are empty.

I tried also:
dataSmTRBM <- TCGAquery_SampleTypes(getResults(query.mm,cols="cases"),"Recurrent Blood Derived Cancer - Bone Marrow") 
dataSmTBM <- TCGAquery_SampleTypes(getResults(query.mm,cols="cases"),"Primary Blood Derived Cancer - Bone Marrow")
in the last case I get: “Error message: one or more sample types do not exis”
Could you help me please?
Thank you in advance

**Comment by tiagochst** [comment]
You can find the samples metadata in the SummarizedExperient object.
An example is shown in his rpubs: http://rpubs.com/tiagochst/MMRF-COMMPASS

That function `TCGAquery_SampleTypes` only works with TCGA data, and was written 4 years ago. Probably I will remove this function to avoid confusion.

Sorry for the problem.
