### ISSUE TITLE
GDCquery_Maf  Error Project TCGA-COMMPASS was not found

### ISSUE THREAD

**Issue by MarzyUnicz** [BioinformaticsFMRP/TCGAbiolinks#383]
Dear Colleague,
I try to get the maf for the Project TCGA-COMMPASS. This is my code:
maf <- GDCquery_Maf("COMMPASS", pipelines = "muse")

I get this error:
**Error in checkProjectInput(project) : 
  Please set a valid project argument from the column id above. Project TCGA-COMMPASS was not found.**
This is my Session info:
> sessionInfo("TCGAbiolinks")
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

other attached packages:
[1] TCGAbiolinks_2.15.3

Could you suggest any solution please?

**Comment by tiagochst** [comment]
Hello, 

There is only RNA-seq data for MMRF-COMMPASS project. 

![Screenshot from 2020-01-14 09-32-38](https://user-images.githubusercontent.com/145529/72390000-ae75d000-36f7-11ea-873b-83f3d28800be.png)
