### ISSUE TITLE
Error in unzip(basename(bin)) : invalid zip name argument

### ISSUE THREAD

**Issue by ghost** [BioinformaticsFMRP/TCGAbiolinks#392]
The folllowing error is received whenever attempting to download data from TCGA-*:

**Error in unzip(basename(bin)) : invalid zip name argument**

In addition, the following warning is generated:

**In addition: Warning message:
In if (grepl("^https?://", url)) { :
  the condition has length > 1 and only the first element will be used**

What could possibly be the issue? Thank you for your help.

**Comment by YCChih** [comment]
Try to reinstall TCGAbiolinks package and restart R
And run the code

At least this is how I fixed this error on my computer
