### ISSUE TITLE
Vignette fixes

### ISSUE THREAD

**Issue by mdozmorov** [BioinformaticsFMRP/TCGAbiolinks#4]
While working through some parts of http://www.bioconductor.org/packages/release/bioc/vignettes/TCGAbiolinks/inst/doc/tcgaBiolinks.html, I noted some inconsistencies. Fixing them may help others.

___
LGG_clinic <- TCGAquery_clinic(cancer = "LGG", 
                               clinical_data_type = "clinical_patient")
should be
LGG_clinic <- TCGAquery_clinic(tumor = "LGG", 
                               clinical_data_type = "clinical_patient")                            
___

Help page for ?TCGAquery_integrate has a typo: "commun" should be "common"                             
___
Section "TCGAquery_investigate: Find most studied TFs in pubmed"

# Select only transcription factors (TFs) from DEGs
TFs <- EAGenes[EAGenes$Family =="transcription regulator",]

Where is the "EAGenes" object?
___

Section "Case study n. 1: Pan Cancer downstream analysis BRCA"

dataClin <- TCGAquery_clinic(tumor = cancer,
                             clinical_data_type = "clinical_patient")         # time = 2.606s
should be
dataClin <- TCGAquery_clinic(tumor = cancer,
                             clinical_data_type = "clinical_patient")         # time = 2.606s

dataPrep <- TCGAanalyze_Preprocessing(object = dataAssy,
                                      cor.cut = 0.6,
                                      path = pathCancer,
                                      cancer = cancer )                      #time = 50.372s
should be
dataPrep <- TCGAanalyze_Preprocessing(object = dataAssy,
                                      cor.cut = 0.6)                      #time = 50.372s

**Comment by tiagochst** [comment]
@torongs82 could you take a look on questions 3 and 4?

**Comment by torongs82** [comment]
@mdozmorov thank you writing us and for interest in our package, @tiagochst of course I will take care of these questions.
