### ISSUE TITLE
Question in using GDCdownload

### ISSUE THREAD

**Issue by lixinjunhe** [BioinformaticsFMRP/TCGAbiolinks#40]
Hi, question with using packagesTCGAbiolinks, error like this:

> query<- GDCquery(project = "TCGA-STAD",
> -                   data.category = "Transcriptome Profiling",
> -                   data.type = "miRNA Expression Quantification" 
> -                   )
>   Accessing GDC. This might take a while...
> 
> GDCdownload(query)
> 试开URL’https://gdc.cancer.gov/files/public/file/gdc-client_v1.1.0_Windows_x64.zip'
> Error in download.file(url, method = method, ...) : 
>   无法打开URL'https://gdc.cancer.gov/files/public/file/gdc-client_v1.1.0_Windows_x64.zip'

**Comment by tiagochst** [comment]
Please, could you send you sessionInfo() from R?

**Comment by tiagochst** [comment]
Is it working now?
