### ISSUE TITLE
Question about TCGAquery_subtype

### ISSUE THREAD

**Issue by 276562578** [BioinformaticsFMRP/TCGAbiolinks#406]
Thanks for your software, it's very helpful!
I wonder the source of the result of "TCGAquery_subtype", where should I go to download the raw data? I have read the subtype paper and get a website: [https://tcga-data.nci.nih.gov/ docs/publications/lgggbm_2015/](url) ,but can't open it. 
Did you generate the result of "TCGAquery_subtype"? Or, where can I download?

**Comment by tiagochst** [comment]
Hello,

All the information from `TCGAquery_subtype` was downloaded from the TCGA marker papers and imported to the package. The files and articles used can be found here https://bioconductor.org/packages/release/bioc/vignettes/TCGAbiolinks/inst/doc/subtypes.html

You can also find the latest publications here: https://gdc.cancer.gov/about-data/publications.

**Comment by 276562578** [comment]
It's very appreciated for your help! I have got the file wanted.
