### ISSUE TITLE
Installation error: purrrogress dependency not found

### ISSUE THREAD

**Issue by OmriNach** [BioinformaticsFMRP/TCGAbiolinks#409]
ERROR: dependency ‘purrrogress’ is not available for package ‘TCGAbiolinks’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/TCGAbiolinks’

Tried both stable and development versions.

**Comment by OmriNach** [comment]
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          0.1                         
year           2020                        
month          06                          
day            06                          
svn rev        78648                       
language       R                           
version.string R version 4.0.1 (2020-06-06)
nickname       See Things Now

**Comment by k1muk** [comment]
Following- are facing the same issue.

**Comment by OmriNach** [comment]
I fixed it by downloading the purrrogress package from an archive: https://cran.r-project.org/src/contrib/Archive/purrrogress/ and selecting the file from the install package GUI on RStudio

Then it throws an error that it needs two other packages, which I just downloaded using the usual install.packages() function. 

After that, it worked.

**Comment by k1muk** [comment]
We tried doing that, but it says it needs Rtools 40....
We tried that too, but we were unsuccessful

**Comment by tiagochst** [comment]
Are you able to install from github ? 
`BiocManager::install("halpo/purrrogress")`

Otherwise, I'll rewrite the code to remove it.

Someone posted an issue in the repository https://github.com/halpo/purrrogress/issues/2

**Comment by lwaldron** [comment]
FYI this change hasn't propagated to Bioconductor [devel](https://bioconductor.org/packages/devel/bioc/html/TCGAbiolinks.html) due to another check error, making it uninstallable. I'll include TCGAbiolinks in [this BioC2020 workshop](https://github.com/waldronlab/PublicDataResources) if I get get it built in time.

**Comment by tiagochst** [comment]
Hi Levi,

I just made a commit to remove that dependence. I will double check it
during the next week. And thanks for adding TCGAbiolibks to the workshop.

Best regards,
Tiago




Em sáb, 11 de jul de 2020 17:49, Levi Waldron <notifications@github.com>
escreveu:

**Comment by lwaldron** [comment]
Thanks! The commit removing that dependence was already in bioc-devel I think, but the commit didn't build due to another `R CMD check` error. So it's still an older version on the package landing page with the purrrfect dependency.

**Comment by lwaldron** [comment]
The dependency on purrrogress still exists in the version installed through bioc-devel (2.17.1, see https://bioconductor.org/packages/devel/bioc/html/TCGAbiolinks.html). Version update is being blocked by https://github.com/BioinformaticsFMRP/TCGAbiolinks/issues/415

**Comment by snijesh** [comment]
Follow the steps in order:

`remotes::install_github("RDocTaskForce/parsetools")`
`remotes::install_github("RDocTaskForce/testextra")`
`BiocManager::install("halpo/purrrogress")`
`BiocManager::install("TCGAbiolinks")`
