### ISSUE TITLE
problems getting data II

### ISSUE THREAD

**Issue by isglobal-brge** [BioinformaticsFMRP/TCGAbiolinks#41]
I execute

query2a <- GDCquery(project = "TCGA-COAD",
                   data.category = "Gene expression",
                   data.type = "Exon quantification",
                   legacy = TRUE,
                   sample.type = c("Solid Tissue Normal"))
GDCdownload(query2a)
data2a <- GDCprepare(query2a)

and I get 

 data2a
function (..., list = character(), package = NULL, lib.loc = NULL, 
    verbose = getOption("verbose"), envir = .GlobalEnv) 
{
    fileExt <- function(x) {
        db <- grepl("\\.[^.]+\\.(gz|bz2|xz)$", x)
        ans <- sub(".*\\.", "", x)
        ans[db] <- sub(".*\\.([^.]+\\.)(gz|bz2|xz)$", "\\1\\2", 
            x[db])

.....

**Comment by isglobal-brge** [comment]
Just related to this post ...  

I'm looking for something to get exon/isoform count data having the name of the genes and the exons .. something similar to what I obtained when using previous version of TCGABiolinks ...

datQuery <- TCGAquery(tumor = "BRCA", platform = "IlluminaHiSeq_RNASeqV2", level = "3")
lsSample <- TCGAquery_samplesfilter(query = datQuery)
dataSmTP <- TCGAquery_SampleTypes(barcode = lsSample$IlluminaHiSeq_RNASeqV2,
                                  typesample = "TP")
TCGAdownload(data = datQuery,
             path = "brca",
             type = "rsem.isoforms.results",
             samples = dataSmTP)
dataAssy <- TCGAprepare(query = datQuery,
                        dir = "brca",
                        type = "rsem.isoforms.results",
                        save = TRUE,
                        summarizedExperiment = TRUE,
                        samples = dataSmTP,
                        filename = "brca.rda")


or ---- 

the same using RNASeq and  exon.quantification

Thank you very much in advanced for your help!

**Comment by tiagochst** [comment]
Please update the package, the output is still a dataframe, once I have time I'll try to make a SummarizedExperiment.
```
devtools::install_github(repo = "BioinformaticsFMRP/TCGAbiolinks")
library(TCGAbiolinks)
datQuery <- GDCquery(project  = "TCGA-BRCA", 
                     data.category = "Gene expression",
                     data.type = "Isoform expression quantification",
                     legacy = TRUE, 
                     file.type = "rsem.isoforms.results",
                     experimental.strategy = "RNA-Seq",
                     sample.type = c("Primary solid Tumor"))
GDCdownload(datQuery, directory = "brca",chunks.per.download = 100)
            
dataAssy <- GDCprepare(query = datQuery, directory =  "brca")

```

**Comment by isglobal-brge** [comment]
Has the SummarizedExperiment issue fixed?

**Comment by tiagochst** [comment]
Not yet.

**Comment by isglobal-brge** [comment]
Tiago, I know that creating a SummarizedExperiment can be very time consuming. However, could it be possible (at least) to get the data.frame annotated?

**Comment by tiagochst** [comment]
Hi, 

I tried to annotate  with biomart, but I lose 80% of the Isoform based on the USC names.

```
library(biomaRt)
# for hg19
ensembl <- useMart(biomart = "ENSEMBL_MART_ENSEMBL",
                   host = "feb2014.archive.ensembl.org",
                   path = "/biomart/martservice" ,
                   dataset = "hsapiens_gene_ensembl")
attributes <- c("chromosome_name",
                "start_position",
                "end_position", "strand",
                "ensembl_gene_id", "entrezgene",
                "external_gene_id","ucsc")

chrom <- c(1:22, "X", "Y")
gene.location <- getBM(attributes = attributes,
                       filters = c("chromosome_name"),
                       values = list(chrom), mart = ensembl)



library(TCGAbiolinks)
datQuery <- GDCquery(project  = "TCGA-BRCA", 
                     data.category = "Gene expression",
                     data.type = "Isoform expression quantification",
                     legacy = TRUE, 
                     file.type = "rsem.isoforms.results",
                     experimental.strategy = "RNA-Seq",
                     sample.type = c("Primary solid Tumor"))
# Lets get a smalled sample to test
datQuery$results[[1]] <- datQuery$results[[1]][1:5,] 
GDCdownload(datQuery, directory = "brca",chunks.per.download = 100)
dataAssy <- GDCprepare(query = datQuery, directory =  "brca")

# Get annotation for hg19
ensembl <- useMart(biomart = "ENSEMBL_MART_ENSEMBL",
                   host = "feb2014.archive.ensembl.org",
                   path = "/biomart/martservice" ,
                   dataset = "hsapiens_gene_ensembl")
attributes <- c("chromosome_name",
                "start_position",
                "end_position", "strand",
                "ensembl_gene_id", "entrezgene",
                "external_gene_id","ucsc")

chrom <- c(1:22, "X", "Y")
gene.location <- getBM(attributes = attributes,
                       filters = c("chromosome_name"),
                       values = list(chrom), mart = ensembl)

# We are able to map only 13k from the 70k isoforms...
table(rownames(dataAssy) %in% gene.location$ucsc)
```

I read that USC changed the names and you should use the files in their server to remap it.
http://hgdownload.cse.ucsc.edu/goldenpath/hg19/database/

If GDC harmonizes the isoform data that would be the best solution. But if you find the right way to updated and remap the genomic positions, I'll add to the package.

**Comment by tiagochst** [comment]
By the way, here is the description of the file. I hope this might help you.
[DESCRIPTION.txt](https://github.com/BioinformaticsFMRP/TCGAbiolinks/files/671998/DESCRIPTION.txt)
