### ISSUE TITLE
testthat Error: Non TCGA data is processed (@test-prepare-download.R#111) 

### ISSUE THREAD

**Issue by lwaldron** [BioinformaticsFMRP/TCGAbiolinks#415]
On Windows platform in bioc-devel, see http://bioconductor.org/checkResults/devel/bioc-LATEST/TCGAbiolinks/tokay1-checksrc.html

**Comment by tiagochst** [comment]
I just removed that test. The path of the file downloaded goes beyond the windows limit.

**Comment by tiagochst** [comment]
The build is fixed on windows devel. 
<img width="1783" alt="Screen Shot 2020-07-17 at 3 48 36 PM" src="https://user-images.githubusercontent.com/145529/87825465-31154e80-c845-11ea-9d3e-d537a1c6950f.png">
