### ISSUE TITLE
"Primary Tumor" vs "Primary solid Tumor" change

### ISSUE THREAD

**Issue by caloto** [BioinformaticsFMRP/TCGAbiolinks#416]
First of all, thank you for your amazing work!!

I am using TCGAbiolinks to download TCGA RNAseq counts and there was a change on how to name tumor samples. Previous packages used "Primary Tumor" whereas newest use "Primary solid Tumor". I wonder if it is possible to know at which TCGAbiolinks version this change was made to update my script.

Thank you very much once again!

**Comment by tiagochst** [comment]
Hi,
That change was made on the GDC side. In November 2019 I fixed it (TCGAbiolinks version 2.15.1).

**Comment by caloto** [comment]
Thank you very much!!!
