### ISSUE TITLE
TCGAanalyze_Normalization: Error in offst(tmp) : could not find function "offst"

### ISSUE THREAD

**Issue by mherberg** [BioinformaticsFMRP/TCGAbiolinks#417]
I am not sure if this is an error in TCGAanalyze_Normalization or EDASeq. However when I run an example like below I get the error in Step 3 (betweenLaneNormalization) that there is an error in offst(tmp) : could not find function "offst".

I am obviously familiar with the offset function in R but not sure what offst is. I am currently running my code in R 4.0.2 on Windows 10.

```
dataNorm <- TCGAanalyze_Normalization(tabDF = dataPrep,
                                      geneInfo = geneInfoHT,
                                      method = "gcContent") 
```
> I Need about  384 seconds for this Complete Normalization Upper Quantile  [Processing 80k elements /s]  
Step 1 of 4: newSeqExpressionSet ...
Step 2 of 4: withinLaneNormalization ...
Step 3 of 4: betweenLaneNormalization ...
Error in offst(tmp) : could not find function "offst"

**Comment by tiagochst** [comment]
I just fixed it. Please, could you update it with `BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")`.

**Comment by mherberg** [comment]
So I fixed it by adding `libary(EDSeq)` so I assume loading the library was just missing from the function.

Thanks.
