### ISSUE TITLE
GDCprepare BioMart error

### ISSUE THREAD

**Issue by talipzengin** [BioinformaticsFMRP/TCGAbiolinks#418]
Hi,
I am using TCGAbiolinks and get BioMart error while running GDCprepare command. I reinstalled TCGAbiolinks and BioMart but got same error. My commands and session info are below. How can I solve this problem? 
Thanks in advance.

```
library(TCGAbiolinks)
library(SummarizedExperiment)
library(dplyr)
library(DT)

query_exp <- GDCquery(project = "TCGA-LUAD",
                      data.category = "Transcriptome Profiling",
                      data.type = "Gene Expression Quantification", 
                      workflow.type = "HTSeq - Counts",
                      barcode = common_patients)

GDCdownload(query_exp, files.per.chunk = 100)

GeneExp <- GDCprepare(query_exp)
save(GeneExp, file ="_GeneExp.rda")
```

> |====================================================|100%                      Completed after 38 s 
> Starting to add information to samples
>  => Add clinical information to samples
>  => Adding TCGA molecular information from marker papers
>  => Information will have prefix 'paper_' 
> luad subtype information from:doi:10.1038/nature13385
> Accessing www.ensembl.org to get gene information
> 
> <MartRegistry>
>   <MartURLLocation database="ensembl_mart_100" default="1" displayName="Ensembl Genes 100" host="www.ensembl.org" includeDatasets="" martUser="" name="ENSEMBL_MART_ENSEMBL" path="/biomart/martservice" port="80" serverVirtualSchema="default" visible="1" />
>   <MartURLLocation database="mouse_mart_100" default="" displayName="Mouse strains 100" host="www.ensembl.org" includeDatasets="" martUser="" name="ENSEMBL_MART_MOUSE" path="/biomart/martservice" port="80" serverVirtualSchema="default" visible="1" />
>   <MartURLLocation database="sequence_mart_100" default="" displayName="Sequence" host="www.ensembl.org" includeDatasets="" martUser="" name="ENSEMBL_MART_SEQUENCE" path="/biomart/martservice" port="80" serverVirtualSchema="default" visible="" />
>   <MartURLLocation database="ontology_mart_100" default="" displayName="Ontology" host="www.ensembl.org" includeDatasets="" martUser="" name="ENSEMBL_MART_ONTOLOGY" path="/biomart/martservice" port="80" serverVirtualSchema="default" visible="" />
>   <MartURLLocation database="genomic_features_mart_100" default="" displayName="Genomic features 100" host="www.ensembl.org" includeDatasets="" martUser="" name="ENSEMBL_MART_GENOMIC" path="/biomart/martservice" port="80" serverVirtualSchema="default" visible="" />
>   <MartURLLocation database="snp_mart_100" default="" displayName="Ensembl Variation 100" host="www.ensembl.org" includeDatasets="" martUser="" name="ENSEMBL_MART_SNP" path="/biomart/martservice" port="80" serverVirtualSchema="default" visible="1" />
>   <MartURLLocation database="regulation_mart_100" default="" displayName="Ensembl Regulation 100" host="www.ensembl.org" includeDatasets="" martUser="" name="ENSEMBL_MART_FUNCGEN" path="/biomart/martservice" port="80" serverVirtualSchema="default" visible="1" />
> </MartRegistry>
> Accessing www.ensembl.org (mirror useast)
> 
> <MartRegistry>
>   <MartURLLocation database="ensembl_mart_100" default="1" displayName="Ensembl Genes 100" host="www.ensembl.org" includeDatasets="" martUser="" name="ENSEMBL_MART_ENSEMBL" path="/biomart/martservice" port="80" serverVirtualSchema="default" visible="1" />
>   <MartURLLocation database="mouse_mart_100" default="" displayName="Mouse strains 100" host="www.ensembl.org" includeDatasets="" martUser="" name="ENSEMBL_MART_MOUSE" path="/biomart/martservice" port="80" serverVirtualSchema="default" visible="1" />
>   <MartURLLocation database="sequence_mart_100" default="" displayName="Sequence" host="www.ensembl.org" includeDatasets="" martUser="" name="ENSEMBL_MART_SEQUENCE" path="/biomart/martservice" port="80" serverVirtualSchema="default" visible="" />
>   <MartURLLocation database="ontology_mart_100" default="" displayName="Ontology" host="www.ensembl.org" includeDatasets="" martUser="" name="ENSEMBL_MART_ONTOLOGY" path="/biomart/martservice" port="80" serverVirtualSchema="default" visible="" />
>   <MartURLLocation database="genomic_features_mart_100" default="" displayName="Genomic features 100" host="www.ensembl.org" includeDatasets="" martUser="" name="ENSEMBL_MART_GENOMIC" path="/biomart/martservice" port="80" serverVirtualSchema="default" visible="" />
>   <MartURLLocation database="snp_mart_100" default="" displayName="Ensembl Variation 100" host="www.ensembl.org" includeDatasets="" martUser="" name="ENSEMBL_MART_SNP" path="/biomart/martservice" port="80" serverVirtualSchema="default" visible="1" />
>   <MartURLLocation database="regulation_mart_100" default="" displayName="Ensembl Regulation 100" host="www.ensembl.org" includeDatasets="" martUser="" name="ENSEMBL_MART_FUNCGEN" path="/biomart/martservice" port="80" serverVirtualSchema="default" visible="1" />
> </MartRegistry>
> Accessing www.ensembl.org (mirror uswest)
> 
> <MartRegistry>
>   <MartURLLocation database="ensembl_mart_100" default="1" displayName="Ensembl Genes 100" host="www.ensembl.org" includeDatasets="" martUser="" name="ENSEMBL_MART_ENSEMBL" path="/biomart/martservice" port="80" serverVirtualSchema="default" visible="1" />
>   <MartURLLocation database="mouse_mart_100" default="" displayName="Mouse strains 100" host="www.ensembl.org" includeDatasets="" martUser="" name="ENSEMBL_MART_MOUSE" path="/biomart/martservice" port="80" serverVirtualSchema="default" visible="1" />
>   <MartURLLocation database="sequence_mart_100" default="" displayName="Sequence" host="www.ensembl.org" includeDatasets="" martUser="" name="ENSEMBL_MART_SEQUENCE" path="/biomart/martservice" port="80" serverVirtualSchema="default" visible="" />
>   <MartURLLocation database="ontology_mart_100" default="" displayName="Ontology" host="www.ensembl.org" includeDatasets="" martUser="" name="ENSEMBL_MART_ONTOLOGY" path="/biomart/martservice" port="80" serverVirtualSchema="default" visible="" />
>   <MartURLLocation database="genomic_features_mart_100" default="" displayName="Genomic features 100" host="www.ensembl.org" includeDatasets="" martUser="" name="ENSEMBL_MART_GENOMIC" path="/biomart/martservice" port="80" serverVirtualSchema="default" visible="" />
>   <MartURLLocation database="snp_mart_100" default="" displayName="Ensembl Variation 100" host="www.ensembl.org" includeDatasets="" martUser="" name="ENSEMBL_MART_SNP" path="/biomart/martservice" port="80" serverVirtualSchema="default" visible="1" />
>   <MartURLLocation database="regulation_mart_100" default="" displayName="Ensembl Regulation 100" host="www.ensembl.org" includeDatasets="" martUser="" name="ENSEMBL_MART_FUNCGEN" path="/biomart/martservice" port="80" serverVirtualSchema="default" visible="1" />
> </MartRegistry>
> Error in get.GRCh.bioMart("hg38") : failed to get URL after 3 tries:
>   error: Unexpected format to the list of available marts.
> Please check the following URL manually, and try ?listMarts for advice.
> http://uswest.ensembl.org:80/biomart/martservice?type=registry&requestid=biomaRt
> Ek olarak: Warning messages:
> 1: In mapCurlOptNames(names(.els), asNames = TRUE) :
>   Unrecognized CURL options: followlocation, ssl.verifypeer, writefunction
> 2: In mapCurlOptNames(names(.els), asNames = TRUE) :
>   Unrecognized CURL options: followlocation, ssl.verifypeer, writefunction
> 3: In mapCurlOptNames(names(.els), asNames = TRUE) :
>   Unrecognized CURL options: followlocation, ssl.verifypeer, writefunction

`BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")`
`BiocManager::install("biomaRt")`

`sessionInfo()`

> R version 3.5.2 (2018-12-20)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: CentOS Linux 7 (Core)
> 
> Matrix products: default
> BLAS: /truba/home/tzengin/R/lib64/R/lib/libRblas.so
> LAPACK: /truba/home/tzengin/R/lib64/R/lib/libRlapack.so
> 
> locale:
>  [1] LC_CTYPE=tr_TR.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=tr_TR.UTF-8        LC_COLLATE=tr_TR.UTF-8    
>  [5] LC_MONETARY=tr_TR.UTF-8    LC_MESSAGES=tr_TR.UTF-8   
>  [7] LC_PAPER=tr_TR.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=tr_TR.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] parallel  stats4    stats     graphics  grDevices utils     datasets 
> [8] methods   base     
> 
> other attached packages:
>  [1] forcats_0.5.0               stringr_1.4.0              
>  [3] purrr_0.3.4                 readr_1.3.1                
>  [5] tidyr_1.1.0                 tibble_3.0.3               
>  [7] ggplot2_3.3.2               tidyverse_1.3.0            
>  [9] DT_0.14                     dplyr_1.0.0                
> [11] SummarizedExperiment_1.12.0 DelayedArray_0.8.0         
> [13] BiocParallel_1.16.6         matrixStats_0.56.0         
> [15] Biobase_2.42.0              GenomicRanges_1.34.0       
> [17] GenomeInfoDb_1.18.2         IRanges_2.16.0             
> [19] S4Vectors_0.20.1            BiocGenerics_0.28.0        
> [21] TCGAbiolinks_2.17.3        
> 
> loaded via a namespace (and not attached):
>  [1] httr_1.4.1             bit64_0.9-7.1          jsonlite_1.7.0        
>  [4] R.utils_2.8.0          modelr_0.1.8           assertthat_0.2.1      
>  [7] blob_1.2.1             cellranger_1.1.0       GenomeInfoDbData_1.2.0
> [10] progress_1.2.2         pillar_1.4.6           RSQLite_2.2.0         
> [13] backports_1.1.8        lattice_0.20-41        glue_1.4.1            
> [16] downloader_0.4         digest_0.6.25          XVector_0.22.0        
> [19] rvest_0.3.5            colorspace_1.4-1       htmltools_0.5.0       
> [22] Matrix_1.2-18          R.oo_1.22.0            plyr_1.8.6            
> [25] XML_3.98-1.19          pkgconfig_2.0.3        broom_0.7.0           
> [28] biomaRt_2.38.0         haven_2.3.1            zlibbioc_1.28.0       
> [31] scales_1.1.1           generics_0.0.2         ellipsis_0.3.1        
> [34] withr_2.2.0            cli_2.0.2              readxl_1.3.1          
> [37] magrittr_1.5           crayon_1.3.4           memoise_1.1.0         
> [40] R.methodsS3_1.8.0      fansi_0.4.1            fs_1.4.2              
> [43] xml2_1.3.2             tools_3.5.2            data.table_1.12.8     
> [46] prettyunits_1.1.1      hms_0.5.3              lifecycle_0.2.0       
> [49] reprex_0.3.0           munsell_0.5.0          AnnotationDbi_1.44.0  
> [52] compiler_3.5.2         rlang_0.4.7            grid_3.5.2            
> [55] RCurl_1.98-1.2         rstudioapi_0.11        htmlwidgets_1.5.1     
> [58] bitops_1.0-6           gtable_0.3.0           DBI_1.1.0             
> [61] curl_4.3               R6_2.4.1               lubridate_1.7.9       
> [64] knitr_1.29             bit_1.1-15.2           stringi_1.4.6         
> [67] Rcpp_1.0.5             vctrs_0.3.2            dbplyr_1.4.4          
> [70] tidyselect_1.1.0       xfun_0.15             
>

**Comment by shaojunyu** [comment]
I have the similar issue for GDCprepare and have tried all possible solutions from Google on different servers, still got this error. Could anyone help? Thanks a lot!
```
library(TCGAbiolinks)

query <- GDCquery(project = "TCGA-PAAD",
                  data.category = "Transcriptome Profiling",
                  data.type = "Gene Expression Quantification",
                  workflow.type = "HTSeq - FPKM-UQ")

GDCdownload(query)
data <- GDCprepare(query)
```

### Output:
......
Downloading data for project TCGA-PAAD
Of the 182 files for download 182 already exist.
All samples have been already downloaded
|====================================================|100%                      Completed after 14 s
Starting to add information to samples
 => Add clinical information to samples
 => Adding TCGA molecular information from marker papers
 => Information will have prefix 'paper_'
paad subtype information from:doi:10.1016/j.ccell.2017.07.007
Accessing www.ensembl.org to get gene information
Ensembl site unresponsive, trying useast mirror
Ensembl site unresponsive, trying useast mirror
Ensembl site unresponsive, trying uswest mirror
Accessing www.ensembl.org (mirror useast)
Ensembl site unresponsive, trying uswest mirror
Accessing www.ensembl.org (mirror uswest)
Ensembl site unresponsive, trying uswest mirror
Error in get.GRCh.bioMart("hg38") : failed to get URL after 3 tries:
  error: SSL certificate problem: unable to get local issuer certificate
Calls: GDCprepare ... makeSEfromTranscriptomeProfiling -> get.GRCh.bioMart


### Error

> Ensembl site unresponsive, trying uswest mirror
Error in get.GRCh.bioMart("hg38") : failed to get URL after 3 tries:
  error: SSL certificate problem: unable to get local issuer certificate

**Comment by Ruizheng98** [comment]
I have this problem too. I can't use TCGAbiolinks linked to Ensembl and get gene annotation information. How can I solve this problem? Thanks a lot

**Comment by mfortis** [comment]
> I have this problem too. I can't use TCGAbiolinks linked to Ensembl and get gene annotation information.
> 
> ```
> Error in get.GRCh.bioMart("hg38") : failed to get URL after 3 tries:
>   error: failed to load external entity "http://www.ensembl.org/info/website/archives/index.html?redirect=no"
> ```
> 
> How can I solve this problem? Thanks a lot

I have this problem too!! :(
