### ISSUE TITLE
GDCquery_Maf  for mutect2

### ISSUE THREAD

**Issue by sigven** [BioinformaticsFMRP/TCGAbiolinks#42]
Hi,

I am using the `GDCquery_Maf` function in TCGAbiolinks v2.3.5 to retrieve MAF files from GDC. It works fine when pipeline is any of 'muse','somaticsniper', or 'varscan2', but it fails when I try 'mutect2' (Error message: 'cannot download all files / URL 400 Bad Request') 

The same error happens for any tumor type.  Would you be able to enable download of these MAF files as well?

cheers,
Sigve

**Comment by tiagochst** [comment]
I'm really sorry!
I made a change in the code. I actually called it "mutect" instead of mutect2.
I just fixed it.
