### ISSUE TITLE
purrrogress dependency not available

### ISSUE THREAD

**Issue by caloto** [BioinformaticsFMRP/TCGAbiolinks#420]
First, thank you for taking your time to attend this new issue.

My under-development package depends on TCGAbiolinks for data downloading and manipulation. When trying to install it using devtools, it throws back an error due to TCGAbiolinks dependence on purrrogress.

I have checked your description file and I noticed purrrogress is not actually but purrr, so I am completely lost...

Do you have any idea about this?

**Comment by GMFranceschini** [comment]
The package has been removed from CRAN.
`devtools::install_github("halpo/purrrogress")` solved the issue for me. 
Best
