### ISSUE TITLE
GDCprepare "Can't recycle"

### ISSUE THREAD

**Issue by NatashaJorge** [BioinformaticsFMRP/TCGAbiolinks#422]
Hello! I'm running the following code and facing this problem: 

library(TCGAbiolinks)

query <- GDCquery(project = c("BEATAML1.0-COHORT","NCICCR-DLBCL","TCGA-LAML","CGCI-BLGSP","TCGA-DLBC","CTSP-DLBCL1"),
                  data.category = c("Transcriptome Profiling"),
                  data.type = c("Gene Expression Quantification"),
                  workflow.type = c("HTSeq - Counts"),
                  legacy = FALSE)
GDCdownload(query)
data = GDCprepare(query)

|====================================================|100%                      Completed after 1 m 
Starting to add information to samples
 => Add clinical information to samples
Error: Can't recycle `..1` (size 0) to match `..2` (size 2).
Run `rlang::last_error()` to see where the error occurred.

If I run the rlang::last_error() I get:

> rlang::last_error()
<error/vctrs_error_incompatible_size>
Can't recycle `..1` (size 0) to match `..2` (size 2).
Backtrace:
  1. TCGAbiolinks::GDCprepare(query)
 14. vctrs::stop_incompatible_size(...)
 15. vctrs:::stop_incompatible(...)
 16. vctrs:::stop_vctrs(...)
Run `rlang::last_trace()` to see the full context.

Please, how can I solve this problem?

Thanks in advance,
Best

**Comment by tiagochst** [comment]
`NCICCR-DLBCL` was breaking the logic of the code. I prefer not to fix this, but warn the users to prepare separately.

**Comment by NatashaJorge** [comment]
Hello! Me again!

I'm running the same code with BEATAML1.0-COHORT and I'm running into the same problem. You wrote the project was breaking the logic of the code and suggested to prepare it individually. Please, how can I do that? 

My command were:

> aa = GDCquery(project="BEATAML1.0-COHORT",data.category="Transcriptome Profiling",data.type="Gene Expression Quantification", workflow.type="STAR - Counts")
> GDCdownload(aa)
> data = GDCprepare(aa, save = TRUE, save.filename=paste(projects[a],"rda",sep="."))
|====================================================|100%                      Completed after 7 m 
Starting to add information to samples
 => Add clinical information to samples
Error in `dplyr::bind_cols()`:
! Can't recycle `..1` (size 0) to match `..2` (size 2).
Run `rlang::last_trace()` to see where the error occurred.

> rlang::last_trace()
<error/vctrs_error_incompatible_size>
Error in `dplyr::bind_cols()`:
! Can't recycle `..1` (size 0) to match `..2` (size 2).
---
Backtrace:
     ▆
  1. └─TCGAbiolinks::GDCprepare(...)
  2.   └─TCGAbiolinks:::readTranscriptomeProfiling(...)
  3.     └─TCGAbiolinks:::makeSEfromTranscriptomeProfilingSTAR(...)
  4.       └─TCGAbiolinks::colDataPrepare(cases)
  5.         └─TCGAbiolinks:::splitAPICall(...)
  6.           └─base::tryCatch(...)
  7.             └─base (local) tryCatchList(expr, classes, parentenv, handlers)
  8.               └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
  9.                 └─value[[3L]](cond)
 10.                   └─TCGAbiolinks (local) FUN(items[start:end])
 11.                     └─dplyr::bind_cols(df %>% as.data.frame, diagnoses %>% as.data.frame)
Run rlang::last_trace(drop = FALSE) to see 5 hidden frames.

Thanks in advance!

**Comment by janetian123** [comment]
Running to the exact same problem here...

**Comment by kellentjioe** [comment]
Me too (with the BEAT-AML1.0 cohort)
