### ISSUE TITLE
The TCGAvisualize_SurvivalCoxNET needs updating asap

### ISSUE THREAD

**Issue by wp1g19** [BioinformaticsFMRP/TCGAbiolinks#425]
After reading around, I have found this function to be broken, with fixes posted around.

Firstly, the function uses the wrong header identifiers, noted here: https://github.com/BioinformaticsFMRP/TCGAbiolinks/issues/343

Secondly, after correcting these manually, you will encounter this error:
Error in coxph(formula = Surv(time, status) ~ ., data = data) : 
  No (non-missing) observations
In addition: Warning messages:
1: Setting row names on a tibble is deprecated. 
2: In max(event[who2]) : no non-missing arguments to max; returning -Inf

This is perhaps due to the function reading all the data on status as numeric, however, there are many NAs in the TCGA datasets which are misread, this error could possibly be fixed by reading the data by (as.numeric(as.character)).

KR,
Will

**Comment by kellentjioe** [comment]
We are having the same problems here. An update would be very helpful.

Thanks.

**Comment by Bezerra-95** [comment]
I'm having the same problem, but the correction isn't too hard. Just adding the above line before the analysis fixed the problem.

```
names(dataClin)[8]<-"days_to_last_followup"
names(dataClin)[10]<-"age_at_initial_pathologic_diagnosis"
```
