### ISSUE TITLE
download the dataset on MCC

### ISSUE THREAD

**Issue by DrZhaoJie** [BioinformaticsFMRP/TCGAbiolinks#426]
Hi, I'd like to download TCGA dataset with GDCquery and GDCdownload function. But I didn't find the project ID for Merkel cell carcinoma (MCC) and Triple-negative breast cancer (TNBC). How may I solve this? Thank you very much！

**Comment by tiagochst** [comment]
The Triple-negative breast cancer (TNBC) is a subset of Breast Invasive Carcinoma (BRCA). You will need to select the TNBC samples before downloading all BRCA, or subsetting after.

I am not familiar with  Merkel cell carcinoma (MCC).
