### ISSUE TITLE
I couldn't find all the files from the query. Please check if the directory parameter is right or `GDCdownload` downloaded the samples.

### ISSUE THREAD

**Issue by VaHiX** [BioinformaticsFMRP/TCGAbiolinks#433]
I tried the following codes and get this error what is the issue?

query_h_c <- GDCquery(project = "TCGA-HNSC", 
                      legacy = TRUE,data.category = "Gene expression",data.type = "Gene expression quantification",
                      file.type = "results",platform = "Illumina HiSeq",sample.type = "Solid Tissue Normal")

GDCdownload(query_h_n)
rse_h_n <- GDCprepare(query_h_n)

Error:

Error in GDCprepare(query_h_c) : 
  I couldn't find all the files from the query. Please check if the directory parameter is right or `GDCdownload` downloaded the samples.

**Comment by CynStr** [comment]
I have the same issue, @VaHiX were you able to resolve this?

**Comment by VaHiX** [comment]
> I have the same issue, @VaHiX were you able to resolve this or found out what the issue is from somewhere else?

I run it on OSX and there is no issue, I am not sure it is a Linux bug our any server conflict!
I do not know how to reinstall it from scratch

**Comment by CynStr** [comment]
I'm using Windows. I updated R from 4.0.2 to 4.0.3 and ran Rstudio as administrator and it seemed to solve the issue. I am also using the dev. version of TCGABiolinks.
