### ISSUE TITLE
GDCprepare can't find the files

### ISSUE THREAD

**Issue by MercedesBentata** [BioinformaticsFMRP/TCGAbiolinks#438]
Hello,

I successfully ran the **GDCquery** function.

Then, I ran the **GDCdownload**. Everything was downloaded and ran smoothly besides these warnings: (here is one example)
<simpleWarning in file.copy(from = from, to = todir, recursive = TRUE): problem copying ... No such file or directory>
So I just copied manually the downloaded files to this directory: GDCdata\TCGA-LGG\harmonized\DNA_Methylation\Methylation_Beta_Value

Next, I ran **GDCprepare** and the next problem appeared:
Error in GDCprepare(query = query) : 
  I couldn't find all the files from the query. Please check if the directory parameter is right or `GDCdownload` downloaded the samples.

I am sure I am in the correct directory and my files are there. What could be the problem? Has someone faced this problem before?

Thanks a lot in advance!

**Comment by MercedesBentata** [comment]
I solved the problem. The length of the path name was too long.

**Comment by tjhwangxiong** [comment]
> I solved the problem. The length of the path name was too long.

How did you solve the length of the path name ? I have this problem too.
