### ISSUE TITLE
Vignette Should Use Consistent Casing

### ISSUE THREAD

**Issue by DarioS** [BioinformaticsFMRP/TCGAbiolinks#44]
In the vignette there is a table which has headings like "Data.type" and entries like "Copy number variation". Because R is case-sensitive, this causes errors if used. The vignette should be updated to use upper case for the entries and lower case for the parameters, to conform with the software.

**Comment by tiagochst** [comment]
I changed the headers to be the same as the name of the parameters.
But  the upper case for the entries depends if it is legacy or harmonized database that you are accessing.  This difference is in GDC database, "Copy number variation" works for legacy and "Copy Number Variation" works for Harmonized.
