### ISSUE TITLE
GDCprepare() function error

### ISSUE THREAD

**Issue by mdkessler** [BioinformaticsFMRP/TCGAbiolinks#442]
I'm cleaning up code from an analysis reliant on data downloaded using TCGAbiolinks. The code worked perfectly previously (same machine, settings, etc). However, currently the analysis fails with the following error:

Accessing grch37.ensembl.org to get gene information
Downloading genome information (try:0) Using: Human genes (GRCh37.p13)
Accessing grch37.ensembl.org (mirror useast)
Downloading genome information (try:1) Using: Human genes (GRCh38.p13)
Accessing grch37.ensembl.org (mirror uswest)
Downloading genome information (try:2) Using: Human genes (GRCh38.p13)
Error in get.GRCh.bioMart(genome) : failed to get URL after 3 tries:
  error: no applicable method for 'filter_' applied to an object of class "c('tbl_SQLiteConnection', 'tbl_dbi', 'tbl_sql', 'tbl_lazy', 'tbl')"

This has happened for two cancer-types (i.e. projects). Example code to generate the error:

query <- GDCquery(project = "TCGA-UCEC", 
                    data.category = "Gene expression",
                    data.type = "Gene expression quantification",
                    platform = "Illumina HiSeq", 
                    file.type  = "normalized_results",
                    experimental.strategy = "RNA-Seq",
                    legacy = TRUE)

GDCdownload(query, method = "api", files.per.chunk = 10)

TCGAdata <- GDCprepare(query)

Perhaps something has broken with this function/biomart?

Thanks!

**Comment by tiagochst** [comment]
This code worked on my side. I think it was a biomart connection problem.

```r
query <- GDCquery(
  project = "TCGA-UCEC",
  data.category = "Gene expression",
  data.type = "Gene expression quantification",
  platform = "Illumina HiSeq",
  file.type = "normalized_results",
  experimental.strategy = "RNA-Seq",
  legacy = TRUE
)

GDCdownload(query, method = "api", files.per.chunk = 10)

TCGAdata <- GDCprepare(query)


```
