### ISSUE TITLE
TCGAvisualisevolcano plot height bug

### ISSUE THREAD

**Issue by wp1g19** [BioinformaticsFMRP/TCGAbiolinks#449]
Script attached:
TCGAVisualize_volcano(DEG.ucs$logFC, DEG.ucs$adj.P.Val,
                       filename = "OCCAMS.png", xlab = "logFC", names = genelist,
                       names.fill = TRUE, show.names = "highlighted", highlight = genelist,
                       x.cut = 1, y.cut = 0.0000000000000000000000000005,xlim = 50, ylim = 500, width = 49, height = 49,
                       highlight.color = "Black",
                       height = 10, title = "DEA OCCAMS (Tumour vs GTex Normal")
Error in TCGAVisualize_volcano(DEG.ucs$logFC, DEG.ucs$adj.P.Val, filename = "OCCAMS.png",  : 
  formal argument "height" matched by multiple actual arguments

**Comment by tiagochst** [comment]
height was provided twice in the function. 

TCGAVisualize_volcano(
    DEG.ucs$logFC,
    DEG.ucs$adj.P.Val,
    filename = "OCCAMS.png",
    xlab = "logFC",
    names = genelist,
    names.fill = TRUE,
    show.names = "highlighted",
    highlight = genelist,
    x.cut = 1,
    y.cut = 0.0000000000000000000000000005,
    xlim = 50,
    ylim = 500,
    width = 49,
    **height = 49,**
    highlight.color = "Black",
    **height = 10,**
    title = "DEA OCCAMS (Tumour vs GTex Normal"
)
