### ISSUE TITLE
Downloading data using manifest file

### ISSUE THREAD

**Issue by jnrmro** [BioinformaticsFMRP/TCGAbiolinks#455]
Hello. 

Great package. Have been using for downloading tcga data moving forward.

With the recent pan-tcga analysis, some manifest files have been provided: https://gdc.cancer.gov/files/public/file/PanCan-General_Open_GDC-Manifest_2.txt

Is there a manner to download tcga data by inputing manifest file into GDCquery/GDCdownload? I understand there is a function to produce a manifest file, but cannot find the function to take a manifest file and download the data.

Thanks.

**Comment by tiagochst** [comment]
Sorry for the very late reply.

Initially, the idea was that the manifest was going to be used with the GDC client tool. 

But I believe this should work.

```
query = GDCquery(
    project = "TCGA-ACC",
    data.category = "Proteome Profiling",
    sample.type = "Primary Tumor", 
    legacy = FALSE)

manifest <- getManifest(query)
TCGAbiolinks:::GDCdownload.aux(
    server = "https://api.gdc.cancer.gov/data/",
    manifest = manifest,
    name = "test.tar.gz",
    path = "Test"
)
```
