### ISSUE TITLE
error reading from connection (Error in load(url(con)))

### ISSUE THREAD

**Issue by Xiaofei-git** [BioinformaticsFMRP/TCGAbiolinks#456]
Dear there, 

I got an error when used TCGAquery_recount2 from TCGAbiolinks. Here are the code and the error as below. I did some search for the error but did not figure out why and how to fix it out. I asked the same question here https://support.bioconductor.org/p/9136064/ . Really appreciate for any clues, thanks a lot!

Lung_GTEx_recount2 <- TCGAquery_recount2(project = "gtex", tissue = "lung")
downloading Range Summarized Experiment for: lung
Error in load(url(con)) : cannot read from connection
In addition: Warning message:
In load(url(con)) :
  URL 'http://idies.jhu.edu/recount/data/v2/SRP012682/rse_gene_lung.Rdata': Timeout of 60 seconds was reached

**Comment by tiagochst** [comment]
It is working on my side. It could be a server problem, or a firewall blocking the access.

**Comment by Xiaofei-git** [comment]
Fixed, because of the poor signal
