### ISSUE TITLE
Problems downloading GDC data

### ISSUE THREAD

**Issue by AndreVidas** [BioinformaticsFMRP/TCGAbiolinks#46]
Hi TCGAbiolinks!

One of our users have tried to download GDC but keep getting the same error message:

Error in curl::curl_fetch_memory(url, handle = handle) :
  SSL connect error
Calls: GDCquery ... request_fetch -> request_fetch.write_memory -> <Anonymous> -> .Call

Among other things the user has tried:

query.exp <- GDCquery(project = "TCGA-BRCA",
                      legacy = TRUE,
                      data.category = "Gene expression",
                      data.type = "Gene expression quantification",
                      platform = "Illumina HiSeq",
                      file.type = "results",
                      experimental.strategy = "RNA-Seq",
                      sample.type = c("Primary solid Tumor","Solid Tissue Normal"))

, but the same error keeps occurring. The user says that she has updated TCGAbiolinks last Saturday.

Do you have any idea of why this error occur?

Thanks in advance.

Best,
André

**Comment by tiagochst** [comment]
Hi André,

Which OS is it? Linux, windows, mac? For linux, apparently, installing  libcurl4-openssl-dev solves the problem. I need to test for other OS.

`sudo apt-get install libcurl4-openssl-dev`

Best regards,
Tiago

**Comment by AndreVidas** [comment]
Thanks for the short reply Tiago!

She found out that it was actually a matter of updating a lot of packages that had not been up to date. So now it works.

Best,
André
