### ISSUE TITLE
Get difference sample number when using TCGAbiolinks to download TCGA-COAD dataset!

### ISSUE THREAD

**Issue by xiekunwhy** [BioinformaticsFMRP/TCGAbiolinks#460]
Hi,

When I use TCGAbiolinks to download TCGA-COAD RNA-seq counts, I got 521 samples, but the real sample size is 512 according to ucsc xena webpage https://xenabrowser.net/datapages/?dataset=TCGA-COAD.htseq_counts.tsv&host=https%3A%2F%2Fgdc.xenahubs.net&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443
Why they are different?

library(TCGAbiolinks)
library(matrixStats)
library(SummarizedExperiment)
query <- GDCquery(project = "TCGA-COAD",
                  data.category = "Transcriptome Profiling",
                  data.type = "Gene Expression Quantification",
                  workflow.type = "HTSeq - Counts"
)
GDCdownload(query, method = "api", files.per.chunk = 1000)
expdat <- GDCprepare(query = query)
count_matrix <- assay(expdat)
write.csv(count_matrix,file = paste("TCGA-COAD","Counts.csv",sep = "."), quote = F)

Best,
Kun

**Comment by tiagochst** [comment]
Hi, 

We don't do any processing like this one in TCGAbiolinks:

`Data from the same sample but from different vials/portions/analytes/aliquotes is averaged;`

If you consider only the same samples, you have 512. You can check with the code below:

```{R}
library(TGAbiolinks)
query.exp <- GDCquery(
    project = "TCGA-COAD", 
    data.category = "Transcriptome Profiling",
    data.type = "Gene Expression Quantification", 
    workflow.type = "STAR - Counts"
)
length(unique(substr(query.exp$results[[1]]$cases,1,16)))

```
<img width="626" alt="Screen Shot 2022-04-19 at 10 13 18 AM" src="https://user-images.githubusercontent.com/145529/164024054-4ef38ad0-59f6-4db6-8bbb-4c2ae6458e03.png">
