### ISSUE TITLE
TARGET-ALL-P3 GDCprepare issue

### ISSUE THREAD

**Issue by brdfrdd** [BioinformaticsFMRP/TCGAbiolinks#461]
Hi there,

I wanted to download the TARGET-ALL-P3 dataset via TCGABiolinks. The download was fine with GDCdownload(query), in which the query was for category = "Transcriptome Profiling", type = "Gene Expression Quantification", workflow = "HTSeq  - Counts".

The GDCprepare(query) step did not complete successfully:

>      d <- GDCprepare(query)
|=====================================|100%                      Completed after 9 s 
Starting to add information to samples
Adding description to TARGET samples
 => Add clinical information to samples
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

Can someone tell me how to solve this?

Thanks in advance for the help!

**Comment by tiagochst** [comment]
@brdfrdd  thanks!
