### ISSUE TITLE
TCGA-LAML CNV data

### ISSUE THREAD

**Issue by renhuasong** [BioinformaticsFMRP/TCGAbiolinks#464]
I used the below code: 
query.lAML.nocnv <- GDCquery(
  project = "TCGA-LAML",
  data.category = "Copy number variation",
  legacy = TRUE,
  file.type = "nocnv_hg19.seg",
  sample.type = c("Primary Tumor")
)

Error:
ooo Project: TCGA-LAML
Sorry! There is no result for your query. Please check in GDC the data available or if there is no error in your query.

It is ok for other cancers. Why I can not get the data for LAML? Thanks

**Comment by tiagochst** [comment]
Hi, 
For "TCGA-LAML"  there was no "Primary Tumor"
```
query.lAML.nocnv <- GDCquery(
  project = "TCGA-LAML",
  data.category = "Copy number variation",
  legacy = TRUE,
 file.type = "nocnv_hg19.seg"
)
```

<img width="624" alt="Screen Shot 2021-11-12 at 5 23 25 PM" src="https://user-images.githubusercontent.com/145529/141545536-0581b61f-8a69-4aea-8d9c-bf65f4824fc0.png">
