### ISSUE TITLE
TCGAbiolinks Crashes R When Trying to Use GDCPrepare to Prepare More Than One Project

### ISSUE THREAD

**Issue by compbiolover** [BioinformaticsFMRP/TCGAbiolinks#468]
Hi,
I have been using TCGAbiolinks for several projects over the past two years and the latest update has caused it to crash R when trying to use GDCPrepare to prepare two of my projects. This same code worked in previous versions. I see a massive spike in memory usage (exhausts all of my memory and uses most of my swap memory) before crashing R.  It starts preparing the object and gets to 100% on the progress bar but then never advances beyond that and crashes R. Thanks!

**Comment by tiagochst** [comment]
Please, could you provide the code and R/Bioconductor version?
I'll try to see if there is a way to reduce memory usage.

**Comment by compbiolover** [comment]
Certainly, My code is 
`#Loading needed package
library(TCGAbiolinks)


#TCGA query
combined_query <- GDCquery(project       = c("TCGA-READ", "TCGA-COAD"),
                           data.category = "Transcriptome Profiling",
                           data.type     = "Gene Expression Quantification",
                           workflow.type = "HTSeq - Counts")

#Downloading the data
GDCdownload(query = combined_query,
            method          = "api",
            files.per.chunk = 10,
            directory       = "Data/Bulk-data/TCGA-COAD-and-TCGA-READ-Dataset")

#Preparing the object
combined_data_se <- GDCprepare(combined_query, summarizedExperiment = TRUE, directory = "Data/Bulk-data/TCGA-COAD-and-TCGA-READ-Dataset/")
`
Also, attached are some photos of the memory for the rsession processes as its memory increases. Let me know if there is anything else I can provide. 
![Memory_after_R_crash](https://user-images.githubusercontent.com/39838470/129062017-f7e5fef3-4200-4257-a7b1-11b22f110e79.png)
![Reaches_100%](https://user-images.githubusercontent.com/39838470/129062023-f2e1ab8c-d58d-4b44-815f-d002d485a2c8.png)
![Memory_is_very_high](https://user-images.githubusercontent.com/39838470/129062024-62b25ad7-f98b-4d8c-8fe7-ef583ebaff0f.png)
![Memory_growing](https://user-images.githubusercontent.com/39838470/129062026-f8336769-e73e-4e42-a004-869d5408f309.png)
![Memory_starts_to_grow](https://user-images.githubusercontent.com/39838470/129062029-4f89b0ea-33e6-4218-b8c4-4f18958cbc63.png)

**Comment by compbiolover** [comment]
@tiagochst Any update?

**Comment by hersheymy** [comment]
@tiagochst I also encountered the same problem. When I run GDCprepare to integrate TCGA-LIHC data, R software crashed with consuming a lot of computer memory. Later, I updated the "TCGAbiolinks" package according to your suggestion, and it still consumed a lot of memory within ten minutes after running, as shown in figure 1. After that, the remaining memory gradually increased,, but it was still running after 2 hours, as shown in figure 2.
![figure 1](https://user-images.githubusercontent.com/73090599/131206327-b67012a4-3885-4a00-90a0-73f8fa8e782f.jpg)
![figure 2](https://user-images.githubusercontent.com/73090599/131206330-5fcb6a4d-a374-4400-8c0a-f18540551eae.jpg)

**Comment by AndresMCB** [comment]
same issue here, looks like the new version has a problem with the function GDCprepare()

**Comment by tiagochst** [comment]
It is very weird this change in dplyr, it is allocating 10x more memory.
I had to do a column binding to reduce memory usage.
@AndresMCB, @herseymy, @compbiolover  could you check on your side?

You can update with

BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")

**Comment by compbiolover** [comment]
Thanks for the changes @tiagochst. I re-ran my combined COAD + READ dataset, them independently plus the datasets mentioned by @xjin15 and @hersheymy and all of them were able to complete successfully. The only problem remaining is that if I don't explicitly load tidyverse before running the following code I get the following error about not being able to find the 'map' function. Maybe this could be required when loading tcgabiolinks? I've pasted my test R script and a screenshot of the map error below. Just comment out the loading of tidyverse to see the error. Note I am using version 1.3.1 of tidyverse. Thanks for all your work on this issue. 
![tcgabiolinks-map-error](https://user-images.githubusercontent.com/39838470/131371918-1502b171-7afb-4078-9836-3f738ab77471.png)

`#tcgabiolinks_error_code.R

#Loading needed package
library(TCGAbiolinks);packageVersion("TCGAbiolinks")
library(tidyverse);packageVersion("tidyverse")

#TCGA query
combined_query <- GDCquery(project       = c("TCGA-READ", "TCGA-COAD"),
                           data.category = "Transcriptome Profiling",
                           data.type     = "Gene Expression Quantification",
                           workflow.type = "HTSeq - Counts")

#Downloading the data
GDCdownload(query           = combined_query,
            method          = "api",
            files.per.chunk = 10,
            directory       = "Data/Bulk-data/TCGA-COAD-and-TCGA-READ-Dataset")

#Preparing the object
combined_data_se <- GDCprepare(combined_query, summarizedExperiment = TRUE, directory = "Data/Bulk-data/TCGA-COAD-and-TCGA-READ-Dataset/")


#COAD alone
coad_query <- GDCquery(project       = "TCGA-COAD",
                       data.category = "Transcriptome Profiling",
                       data.type     = "Gene Expression Quantification",
                       workflow.type = "HTSeq - Counts")


GDCdownload(query           = coad_query,
            method          = "api",
            files.per.chunk = 10,
            directory       = "Data/Bulk-data/TCGA-COAD-Dataset")

coad_data_se <- GDCprepare(coad_query, summarizedExperiment = TRUE, directory = "Data/Bulk-data/TCGA-COAD-Dataset/")


#READ alone
read_query <- GDCquery(project       = "TCGA-READ",
                       data.category = "Transcriptome Profiling",
                       data.type     = "Gene Expression Quantification",
                       workflow.type = "HTSeq - Counts")


GDCdownload(query           = read_query,
            method          = "api",
            files.per.chunk = 10,
            directory       = "Data/Bulk-data/TCGA-READ-Dataset/")

read_data_se <- GDCprepare(read_query, summarizedExperiment = TRUE, directory = "Data/Bulk-data/TCGA-READ-Dataset/")


#LIHC alone
lihc_query <- GDCquery(project       = "TCGA-LIHC",
                       data.category = "Transcriptome Profiling",
                       data.type     = "Gene Expression Quantification",
                       workflow.type = "HTSeq - Counts")



GDCdownload(query           = lihc_query,
            method          = "api",
            files.per.chunk = 10,
            directory       = "Data/Bulk-data/TCGA-LIHC-Dataset/")


lihc_data_se <- GDCprepare(lihc_query, summarizedExperiment = TRUE, directory = "Data/Bulk-data/TCGA-LIHC-Dataset/")


#LUSC alone
lusc_query <- GDCquery(project       = "TCGA-LUSC",
                       data.category = "Transcriptome Profiling",
                       data.type     = "Gene Expression Quantification",
                       workflow.type = "HTSeq - Counts")

GDCdownload(query           = lusc_query,
            method          = "api",
            files.per.chunk = 10,
            directory       = "Data/Bulk-data/TCGA-LUSC-Dataset/")

lusc_data_se <- GDCprepare(lusc_query, summarizedExperiment = TRUE, directory = "Data/Bulk-data/TCGA-LUSC-Dataset/")
`

**Comment by compbiolover** [comment]
@tiagochst I just updated to the very latest release and it fixes the namespace issue. I am going to go ahead and close this issue as it has been resolved. Thanks again.
