### ISSUE TITLE
Problem downloading TCGA-LAML clinical data

### ISSUE THREAD

**Issue by rbentham** [BioinformaticsFMRP/TCGAbiolinks#47]
Upon running the following simple query:

`library(TCGAbiolinks)`
`q<- GDCquery(project = "TCGA-LAML", 
                  data.category = "Clinical")`
`GDCdownload(q)`
`GDCprepare_clinic(q, clinical.info = "patient")`

The output in R returns the following error:

Error in `[.data.frame`(clin, , i) : undefined columns selected

This appears to be a bug in `GDCprepare_clinic` due to the data frame `clin` having no column named `new_tumor_events` in the following segment of code:

`   for (i in c("new_tumor_events", "drugs", "follow_ups", `
            `"radiations")) {`
           ` clin[, i] <- as.character(clin[, i])`
            `clin[which(clin[, i] != ""), i] <- "YES"`
           ` clin[which(clin[, i] == ""), i] <- "NO"`
           ` colnames(clin)[which(colnames(clin) == i)] <- paste0("has_", `
            `    i, "_information")`
       ` }`

**Comment by tiagochst** [comment]
Please, which version are you using? I ran the last version and it is working.
I added a verification step some days ago.

```
 composed.cols <- c("new_tumor_events","drugs","follow_ups","radiations")
 composed.cols <- composed.cols[composed.cols %in% colnames(clin)]
```

**Comment by rbentham** [comment]
You were right, I was using an old version and now everything runs fine!
