### ISSUE TITLE
Can I get the number of affectted cases in a cohort of a somatic mutation by query with GDCquery_Maf?

### ISSUE THREAD

**Issue by Xu-Dong** [BioinformaticsFMRP/TCGAbiolinks#481]
I used GDCquery_Maf to obtained the somatic mutations in maf format of a certain tumor type, where I can not find the information about the number of affected cases in a cohort of the mutations, which I can see in the GDC data portal.
Is there any way in TCGAbiolinks that I can query such information?

**Comment by tiagochst** [comment]
Hi, you should be able to do it using maftools (https://bioconductor.org/packages/maftools/)


We have a code to import the data into maftools format here:
https://bioconductor.org/packages/release/bioc/vignettes/TCGAbiolinks/inst/doc/mutation.html#Visualize_the_data
