### ISSUE TITLE
gdcprepare error: ‘==’ only defined for equally-sized data frames

### ISSUE THREAD

**Issue by aastha-v** [BioinformaticsFMRP/TCGAbiolinks#485]
Hello!

I'm trying to work with hg38 RPPA data thus:

query_rppa = GDCquery(project = c("TCGA-COAD", "TCGA-READ"),
             data.category = "Proteome Profiling",
             experimental.strategy = "Reverse Phase Protein Array",
             platform = "RPPA",
             data.type = "Protein Expression Quantification")

GDCdownload(query_rppa)

data_rppa = GDCprepare(query_rppa)

I am able to download 37MB of data. However when I use GDCprepare, I get the following error:

![gdcprepare_error](https://user-images.githubusercontent.com/59477309/149515368-864cc18c-7446-44aa-a855-462f53824ca3.png)

Could you help me figure this out please. Thanks!

**Comment by tiagochst** [comment]
The reason the code is breaking is that 17 files have a lower number of proteins (247) vs 487 from all other 478 fiels.
<img width="540" alt="Screen Shot 2022-01-14 at 10 12 01 AM" src="https://user-images.githubusercontent.com/145529/149538576-b0e41e33-add6-404e-9bc4-03e03e062789.png">

I have to investigate if it is a data problem or not. If not, I need to change the code to include NA's for the missing protein levels.

**Comment by tiagochst** [comment]
For a couple of RPPA samples, the set IDs for Set166 is missing 
<img width="293" alt="Screen Shot 2022-01-14 at 10 25 39 AM" src="https://user-images.githubusercontent.com/145529/149540420-02262647-d342-479f-9a01-28fb65450a4e.png">

**Comment by tiagochst** [comment]
@aastha-v I updated the package to deal with that case, I am not sure why those files are different for some samples.

You can update the package from github with the following R command `BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")`

**Comment by aastha-v** [comment]
Thanks a lot! The update is converting missing values to NA's and allowing data access through GDCprepare.
