### ISSUE TITLE
Error in assay (or assays) function

### ISSUE THREAD

**Issue by HeenaSaini** [BioinformaticsFMRP/TCGAbiolinks#489]
Hi I have downloaded isoform level data : it is having error in assay function: I want to extract raw counts and scaled estimates separately:

brca_iso <- GDCprepare(query = query.iso, directory = 'BRCA_iso', summarizedExperiment = TRUE) 

brca_iso_raw <- assay(brca_iso,"raw_count")

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘assay’ for signature ‘"data.frame", "character"’

I have tried this too:

Matrix_iso <- brca_iso[,seq(1,ncol(brca_iso),3)] 

brca_iso_raw <- assay(Matrix_iso,"raw_count")

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘assay’ for signature ‘"data.frame", "character"’

Please reply...

Thanks

Heena

**Comment by tiagochst** [comment]
Hi,

Please could you send the complete code?

I am not sure which files query.iso is pointing to.

Best regards,
Tiago Chedraoui Silva

**Comment by HeenaSaini** [comment]
query.iso <- GDCquery(project = "TCGA-BRCA", 
                      data.category = "Gene expression",
                      data.type = "Isoform expression quantification",
                      experimental.strategy = "RNA-Seq",
                      platform = "Illumina HiSeq",
                      file.type = "results",
                      legacy = TRUE)

**Comment by HeenaSaini** [comment]
If assay function doesn't work on data frames, I have tried converted it into matix too, it is still not working.. 
> brca_iso_raw <- assay(as.matrix(brca_iso),"raw_count")
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘assay’ for signature ‘"matrix", "character"’

**Comment by HeenaSaini** [comment]
Hi Tiago,

Any updates on my query?

**Comment by HeenaSaini** [comment]
Thank you Tiago, 

it was an R function afterwards.. I thought there was some problem with the "assay" function..

Thanks for your time..
