### ISSUE TITLE
Htseq-count, normalization, miRNA analysis

### ISSUE THREAD

**Issue by AswathyPaul** [BioinformaticsFMRP/TCGAbiolinks#49]
I want to know why  htseq-normalization doesn't seems to work. Apart from that
These code was found in the manual. Do you thinks its an error in manual. Is it matrix data which should be normalized ???
>save(data2, geneInfo , file = "CESERNAseqExpression3.rda")
>dataNorm2 <- TCGAanalyze_Normalization(tabDF = data2, geneInfo = geneInfo)

I am able to download the miRNA but I can't further move to comparison study.

**Comment by torongs82** [comment]
Hi @AswathyPaul,
thank you for interest in TCGAbiolinks, I have added one example related to the htseq-normalization in our vignette: 

https://github.com/BioinformaticsFMRP/TCGAbiolinks/blob/master/vignettes/tcgaBiolinks.Rmd#htseq-data-downstream-analysis-brca

 I am adding now also an example working with miRNA's data.
Stay tuned.
Best,

Antonio.

**Comment by torongs82** [comment]
Hi @AswathyPaul,
I am back.
I have added one example dealing with miRNA gene quantification's data as a comparison study between normal (NT) and tumor samples (TP) in our vignette:

https://github.com/BioinformaticsFMRP/TCGAbiolinks/blob/master/vignettes/tcgaBiolinks.Rmd#mirna-expression-data-downstream-analysis-brca

When you have time you can check them.
If you need anything you can write us.
Best,
Antonio.

**Comment by AswathyPaul** [comment]
Thank you so much.

Regards
-------------------------------------------------------
Aswathy Mary Paul
Ph.D. Student
Computational biology and Bioinformatics
Cancer Research Program [CRP-9]
Rajiv Gandhi Center for Biotechnology
Thycaud(P.O), Poojappura
Thiruvananthapuram-695014, Kerala

**Comment by AswathyPaul** [comment]
I have noticed one thing
in the help page of TCGAanalyze_Preprocessing, you have mentioned datatype="row_counts" but actually in the object, we don't have such a column name instead we have row_count. So when we run the command
dataPrep <- TCGAanalyze_Preprocessing(object = dataPrep,   cor.cut = 0.6)  we will get an error 
Error in assay(object, datatype) : 
  'assay(<RangedSummarizedExperiment>, i="character", ...)' invalid subscript 'i'
'i' not in names(assays(<RangedSummarizedExperiment>))

but once you run the command specifying the datatype. It works fine
dataPrep <- TCGAanalyze_Preprocessing(coad.exp, cor.cut =0,filename = NULL,
                                                                         width = 500, height = 500, datatype = "raw_count")

Once again I really thankful for the support you are providing

**Comment by tiagochst** [comment]
This was fixed in version higher than 2.4
