### ISSUE TITLE
Issue with Tidyverse package

### ISSUE THREAD

**Issue by BAREJAA** [BioinformaticsFMRP/TCGAbiolinks#497]
When I run this  -

library(tidyverse)
library(TCGAbiolinks)
library(DESeq2)

query <- GDCquery(
    project = "TCGA-LAML",
    data.category = "Transcriptome Profiling",
    data.type = "Gene Expression Quantification",
    workflow.type = "STAR - Counts"
) # for all options, refer to - https://portal.gdc.cancer.gov/repository

GDCdownload(query, method = "api")
rnaseq <- GDCprepare(query)

I get this error -
`Error in fn():
! Join columns must be present in data.
x Problem with `#gene`.`

But if I don't have Tidyverse loaded, everything works!

**Comment by tiagochst** [comment]
@BAREJAA Which version is the package? I was not able to replicate it on my side with the latest version.

**Comment by BAREJAA** [comment]
tidyverse version - 1.3.1
dplyr version - 1.0.8

I think these are the most recent versions

Thanks for taking a look!

**Comment by tiagochst** [comment]
I have the same versions. Which operational system ?
Your TCGAbiolinks is also 2.23.9 ?

**Comment by BAREJAA** [comment]
I thought it was, but I was using 2.23.8. Updating this package fixed my problem. 

Thanks again!
