### ISSUE TITLE
GDCdownload() does not work with recently updated splice junction data

### ISSUE THREAD

**Issue by ryanhchung** [BioinformaticsFMRP/TCGAbiolinks#501]
**Hi, 

I'm opening this thread to ask you about the error from GDCdownload() function to download splice junction data.

My codes are as follows:**

#Download splicing variants data
stad.junction <- GDCquery(
  project = "TCGA-STAD", 
  legacy = FALSE,
  data.category = "Transcriptome Profiling",
  data.type = "Splice Junction Quantification",
  experimental.strategy = "RNA-Seq",
  workflow.type = "STAR - Counts"
)
GDCdownload(stad.junction)

**and this produces the following error:**

Downloading data for project TCGA-STAD
GDCdownload will download 407 files. A total of 1.328210268 GB
The total size of files is big. We will download files in chunks
Downloading chunk 1 of 2 (306 files, size = 997.698629 MB) as Mon_Apr_11_09_55_16_2022_0.tar.gz
  |========================================================================================================================================================================| 100%
/usr/bin/gtar: This does not look like a tar archive

gzip: stdin: not in gzip format
/usr/bin/gtar: Child returned status 1
/usr/bin/gtar: Error is not recoverable: exiting now
Download completed
At least one of the chunks download was not correct. We will retry
Downloading chunk 1 of 2 (306 files, size = 997.698629 MB) as Mon_Apr_11_09_55_16_2022_0.tar.gz
  |========================================================================================================================================================================| 100%
/usr/bin/gtar: This does not look like a tar archive

gzip: stdin: not in gzip format
/usr/bin/gtar: Child returned status 1
/usr/bin/gtar: Error is not recoverable: exiting now
Download completed
Error in if (ret == 1) break : argument is of length zero

**Can you solve this issue? Thanks!**

**Comment by tiagochst** [comment]
@ryanhchung Those are controlled files. Do you have a token to download it ?

<img width="1119" alt="Screen Shot 2022-04-11 at 10 49 05 AM" src="https://user-images.githubusercontent.com/145529/162765861-26abb2a7-8668-423c-9b9f-b0d4b4fcf4d0.png">

**Comment by ryanhchung** [comment]
@tiagochst Thanks! I will check it out :)
