### ISSUE TITLE
Consider survminer for plotting KM estimates of survival curves

### ISSUE THREAD

**Issue by MarcinKosinski** [BioinformaticsFMRP/TCGAbiolinks#53]
Have you considered using [`survminer` CRAN](https://cran.rstudio.com/web/packages/survminer/index.html) (by @kassambara) package for plotting KM estimates of survival curves? http://www.sthda.com/english/rpkgs/survminer/

![surv_example](https://cloud.githubusercontent.com/assets/6773454/21224216/54c14af6-c2cb-11e6-9187-4f1cb8678528.png)

**Comment by labrazil** [comment]
Thank you, haven't seen this one before. Looks excellent! I suggest we
implement it.

Houtan

Ph: +1 (310) 570-2362

**Comment by MarcinKosinski** [comment]
@tiagochst please see my 3 comments to your commit here
BioinformaticsFMRP/TCGAbiolinks@d08e49b
