### ISSUE TITLE
Error when I run the codes from tutorial

### ISSUE THREAD

**Issue by RunzhiZ** [BioinformaticsFMRP/TCGAbiolinks#535]
Hi,

When I run the codes below in the [tutorial](https://bioconductor.org/packages/release/bioc/vignettes/TCGAbiolinks/inst/doc/query.html#Harmonized_data_options_(legacy_=_FALSE))

```
query <- GDCquery(
  project = "TCGA-ACC", 
  data.category = "Sequencing Reads",
  data.type = "Aligned Reads", 
  data.format = "bam",
  workflow.type = "STAR 2-Pass Transcriptome"
)
```

I got the error:
Error in checkDataTypeInput(legacy = legacy, data.type = data.type) : 
  Please set a data.type argument from the column harmonized.data.type above

Thanks!

**Comment by tiagochst** [comment]
@RunzhiZ Please what version of TCGAbiolinks do you have ?

I tried the latest version and it worked.

<img width="394" alt="Screen Shot 2022-09-01 at 9 31 12 AM" src="https://user-images.githubusercontent.com/145529/187914202-49474065-4b50-4637-b3d6-2ca7280eb4d6.png">

**Comment by RunzhiZ** [comment]
Hi Tiago,

Thanks for you replying. I found that I used the old version. And now I used the recent version and it works.

Best,
Runzhi

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
