### ISSUE TITLE
MAF query/loop issues

### ISSUE THREAD

**Issue by yesitsjess** [BioinformaticsFMRP/TCGAbiolinks#54]
Hello,

I trying to loop through every TCGA project and download the harmonised Simple Nucleotide Variation data available for each. 

I'm currently trying this approach:
`projects <- getGDCprojects()$project_id
for(i in 1:length(projects)){
    if(!toupper("Simple Nucleotide Variation")%in%toupper(TCGAbiolinks:::getProjectSummary(projects[i])$data_categories$data_category)){
        query <- try(GDCquery(project=projects[i]
            ,data.category="Simple Nucleotide Variation"
            ,data.type="Masked Somatic Mutation"
            ,workflow.type="MuSE Variant Aggregation and Masking"
        ))
        try(GDCdownload(query, method="api", directory="maf"))
        maf <- try(GDCprepare(query, directory="maf"))
    }
}`

But I get the following error for many of the projects, causing execution to fail:
`Accessing GDC. This might take a while...
Error in GDCquery(project = projects[i], data.category = "Simple Nucleotide Variation",  : 
  Please set a valid data.type argument from the list below:
  => `

My original approach was based on the following:
`mut <- GDCquery_Maf("ACC", pipelines = "muse")`

But it yields this error:
`Error in GDCquery_Maf("ACC", pipelines = "muse") : 
  unused argument (pipelines = "muse")`

Do you have any advice on how to achieve a project wide query? Or do I have to write 39 separate pieces of identical code? 

Many thanks for any assistance,
Jess

**Comment by tiagochst** [comment]
Your code is right, but the data type "Masked Somatic Mutation" is available only for TCGA, TARGET projects have the data type "Aggregated Somatic Mutation" which is controlled. So, it pass your check for "Simple Nucleotide Variation", but it does not have  data.type="Masked Somatic Mutation" . I will fix the code the message should say the available ones.

For this
`Error in GDCquery_Maf("ACC", pipelines = "muse") : unused argument (pipelines = "muse")`
I believe you have a old version of the package.

This is the code I suggest:
```
# Version 1
projects <- getGDCprojects()$project_id
projects <- grep("TCGA",projects,value = TRUE)
for(proj in projects){ 
        print(proj)
        query <- try(GDCquery(project=proj ,
                              data.category="Simple Nucleotide Variation" ,
                              data.type="Masked Somatic Mutation" ,
                              workflow.type="MuSE Variant Aggregation and Masking" )) 
        try(GDCdownload(query, method="api", directory="maf")) 
        maf <- try(GDCprepare(query, directory="maf")) 
        assign(paste0(proj,".maf"),maf) # save maf to an object
}

# Version 2 (list of maf)
packageVersion("TCGAbiolinks") # ‘2.3.12’
library(dplyr)
TCGAbiolinks:::getGDCprojects()$project_id %>% 
    regexPipes::grep("TCGA",value=T) %>% 
    sort %>% regexPipes::gsub("TCGA-","") %>% 
    plyr::alply(1,function(x) GDCquery_Maf(x,pipelines = "muse"), .progress = "text")
```

**Comment by yesitsjess** [comment]
Very nice! Many thanks - I wish I'd asked for help earlier! :)
