### ISSUE TITLE
Issue with GDCprepare

### ISSUE THREAD

**Issue by Lattesnow** [BioinformaticsFMRP/TCGAbiolinks#548]
This is what I got from GDCprepare

Starting to add information to samples
 => Add clinical information to samples
 => Adding TCGA molecular information from marker papers
 => Information will have prefix 'paper_' 
prad subtype information from:doi:10.1016/j.cell.2015.10.025
Available assays in SummarizedExperiment : 
  => unstranded
  => stranded_first
  => stranded_second
  => tpm_unstrand
  => fpkm_unstrand
  => fpkm_uq_unstrand
=> Saving file: TCGA-PRADTranscriptome_ProfilingWed_Oct_19_23:39:22_2022.RData
Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'TCGA-PRADTranscriptome_ProfilingWed_Oct_19_23:39:22_2022.RData', probable reason 'Invalid argument'

**Comment by manwarA** [comment]
Hi, I am not an expert, but if you are working on Windows, this file name is problematic "CGA-PRADTranscriptome_ProfilingWed_Oct_19_23:39:22_2022.RData", Windows can not create anything with ":" in its name. You can manually assign a file name and then try again. 

=> Saving file: TCGA-PRADTranscriptome_ProfilingWed_Oct_19_23:39:22_2022.RData
Error in gzfile(file, "wb") : cannot open the connection ## cannot save the file with this name
In addition: Warning message:
In gzfile(file, "wb") :
cannot open compressed file 'TCGA-PRADTranscriptome_ProfilingWed_Oct_19_23:39:22_2022.RData', probable reason 'Invalid argument' ## no saving and then no opening


I encountered the same error recently.

**Comment by Lattesnow** [comment]
> Hi, I am not an expert, but if you are working on Windows, this file name is problematic "CGA-PRADTranscriptome_ProfilingWed_Oct_19_23:39:22_2022.RData", Windows can not create anything with ":" in its name. You can manually assign a file name and then try again.
> 
> => Saving file: TCGA-PRADTranscriptome_ProfilingWed_Oct_19_23:39:22_2022.RData Error in gzfile(file, "wb") : cannot open the connection ## cannot save the file with this name In addition: Warning message: In gzfile(file, "wb") : cannot open compressed file 'TCGA-PRADTranscriptome_ProfilingWed_Oct_19_23:39:22_2022.RData', probable reason 'Invalid argument' ## no saving and then no opening
> 
> I encountered the same error recently.

Solved the problem, thank you
