### ISSUE TITLE
Rstudio - Error: could not find function "GDCquery"

### ISSUE THREAD

**Issue by KatGia** [BioinformaticsFMRP/TCGAbiolinks#560]
Hi y'all! I have R version 4.2.2 and I'm trying to use BiocManager 1.30.19 but it dosn't work. It shows ' could not find function "GDCquery" ' and 'could not find function "GDCdownload" '. 
What am I doing wrong?
Thanks in advance.

**Comment by manwarA** [comment]
Hi, did you install the TCGABiolinks? Something like this:

BiocManager::install("TCGAbiolinks")
