### ISSUE TITLE
Error in "matchedMetExp" when legacy=FALSE

### ISSUE THREAD

**Issue by manwarA** [BioinformaticsFMRP/TCGAbiolinks#570]
Hi,
R4.2.1, TCGAbiolinks = 2.25.3

matchedMetExp("TCGA-LUSC") # gives the following error: 

ooo By data.type
Error in GDCquery(project = project, data.category = "Transcriptome Profiling",  : 
  Please set a valid workflow.type argument from the list below:
  => STAR - Counts

while with the legacy =T, it executed normally: 
matchedMetExp("TCGA-LUSC", legacy = TRUE).

So, I think the default should be legacy TRUE (instead of FALSE), as the number of samples returned is correct.  

Plus, the document says that it returns the samples, however, the code specifically refers to the "primary tumor". It should be mentioned in the documents that it returns the primary tumor not the entire samples from the mentioned project.

**Comment by tiagochst** [comment]
Thank you for reporting the bug. I fixed it on my last commit.
