### ISSUE TITLE
A problem to manual 

### ISSUE THREAD

**Issue by cx-333** [BioinformaticsFMRP/TCGAbiolinks#575]
## Dear friends, now I want to learn how use the **TCGAbiolinks** package, but I can not found it in the given website. Could you offer me some relavent data ? Thank you very much !!!

**Comment by cx-333** [comment]
Thank you for your kind help and other resolutions. But I still hope  [the broken website](http://bioconductor.org/packages/release/bioc/manuals/TCGAbiolinks/man/TCGAbiolinks.pdf/?) can be repaired as fast as possible.

**Comment by torongs82** [comment]
Hi @cx-333 , Xin Chen. First thank you in your interest in using or let's say try to understand how to use TCGAbiolinks first, and secondly , eventually to use it. But anyway, I am here to help you. Please can you clarify your message? What are you looking for? Are you referring to our vignette?

**Comment by cx-333** [comment]
Yeah, I want to use **TCGAbiolinks** package to generate BRCA for breast invasive carcinoma PAM50 subtype classification dataset. Due to the need of my research and existing BRCA PAM50 subtype dataset has no corresponding sample ID, cohort, so I have to download BRCA data utilizing TCGABiolinks, process them, label each sample's subtype and other information by myself. Now I am first contact the R package and very eager for the relevant knowledge about it.

**Comment by torongs82** [comment]
`require(TCGAbiolinks)
df_Subt <- as.data.frame(PanCancerAtlas_subtypes())
head(df_Subt)[,1:5]
table(df_Subt$cancer.type)
cancer <- "BRCA"
dataSubt <- df_Subt[df_Subt$cancer.type %in% cancer,]
head(dataSubt)[,1:5]
table(dataSubt$cancer.type)
table(dataSubt$Subtype_mRNA)`

**Comment by torongs82** [comment]
Hi @cx-333 as you have time, can you try the code I wrote for you and let me know, if this helped? thank you.

**Comment by cx-333** [comment]
OK ! I feel free will try it in my computer and tell you the outcome of the code. Thank you very much.

**Comment by cx-333** [comment]
Wow, Thank you, the above code you offer can I run in my computer normally, and I obtain the pan.SamplesID, cancer.subtype as well as sample number information. This will be useful for my research. Maybe you resolve my problem perfectly, but I may meet some unseen  problems in the future. So I just ask for the detailed usage of TCGAbiolinks package.  I would appreciate it if you provide me service manual about it.

**Comment by tiagochst** [comment]
The manual is back in Bioconductor release version at https://bioconductor.org/packages/3.17/bioc/vignettes/TCGAbiolinks/inst/doc/index.html

**Comment by cx-333** [comment]
Thank you  🎉
