### ISSUE TITLE
GDCquery, copy number variation error

### ISSUE THREAD

**Issue by sanazmo** [BioinformaticsFMRP/TCGAbiolinks#576]
Hello
my R version is R 4.3 and my libraries are up to date. I have a problem with GDC query.
I am trying to build  a gdcquery for copy number variation, but it does not work, It seems that my R could not connect to GDC portal while it works for transcription profiling and protem. how can I fix it?

**Comment by tiagochst** [comment]
Could you post the query code please ?

**Comment by sanazmo** [comment]
my codes:

query <- GDCquery(project = "TCGA-LUAD",
                  data.category = "Copy Number Variation",
                  data.type = "Gene Level Copy Number ",sample.type = c("Primary Tumor", "Solid Tissue Normal"),              
                  access="open")

**Comment by tiagochst** [comment]
Could you test the code below?


```
query <- GDCquery(
    project = "TCGA-LUAD",
    data.category = "Copy Number Variation",
    data.type = "Gene Level Copy Number",
    access = "open"
) 
GDCdownload(query,files.per.chunk = 20) 
data <- GDCprepare(query)
```

**Comment by sanazmo** [comment]
thank you, It works
