### ISSUE TITLE
Transcriptome Profiling queries return tumor and normal data without indicating which is which

### ISSUE THREAD

**Issue by pamelarussell** [BioinformaticsFMRP/TCGAbiolinks#58]
Some patients have gene expression quantification for only a tumor sample while others also have a paired normal tissue sample. In the latter case, both files are returned with no indication of which is which. For example, the following query:

```
query <- GDCquery(project = "TCGA-BRCA",
  data.category = "Transcriptome Profiling",
  data.type = "Gene Expression Quantification", 
  workflow.type = "HTSeq - Counts", barcode = c("TCGA-BH-A0BQ"))
GDCdownload(query, directory="~/Desktop/download_test/TCGAbiolinks/")
```

returns two files:

- 8b86fbec-ded3-4910-9a7b-c9e9d1c7a377.htseq.counts.gz (Solid Tissue Normal)
- b98a0c48-8404-47bd-a781-22dfc6c1475a.htseq.counts.gz (Primary Tumor)

The sample type information can be uncovered from the API as in this curl response:

```
      {
        "access": "open", 
        "file_name": "8b86fbec-ded3-4910-9a7b-c9e9d1c7a377.htseq.counts.gz", 
        "cases": [
          {
            "case_id": "b3bb8fd6-ee54-4813-b042-2bbe70115382", 
            "samples": [
              {
                "sample_type": "Solid Tissue Normal"
              }
            ]
          }
        ], 
        "file_id": "8df40ad3-a372-4c6e-96d9-e52a0b99c722", 
        "data_category": "Transcriptome Profiling"
      }, 
      {
        "access": "open", 
        "file_name": "b98a0c48-8404-47bd-a781-22dfc6c1475a.htseq.counts.gz", 
        "cases": [
          {
            "case_id": "b3bb8fd6-ee54-4813-b042-2bbe70115382", 
            "samples": [
              {
                "sample_type": "Primary Tumor"
              }
            ]
          }
        ], 
        "file_id": "a00fd49a-c11c-4db1-8cf0-698d3f23d7ce", 
        "data_category": "Transcriptome Profiling"
      }, 
```

**Comment by tiagochst** [comment]
Hi,
this information already exists in the results table (field: tissue.definition)
You can see the result value with the following commands
`View(query$results[[1]])`

<img width="240" alt="captura de tela 2017-01-15 as 17 07 47" src="https://cloud.githubusercontent.com/assets/145529/21968065/574f6838-db45-11e6-9fac-e21c2381998f.png">

Also, you can use sample.type filter in the GDCquery function to return only Primary Solid Tumor samples.

```
query <- GDCquery(project = "TCGA-BRCA",
                  data.category = "Transcriptome Profiling",
                  data.type = "Gene Expression Quantification", 
                  sample.type = "Primary Solid Tumor",
                  workflow.type = "HTSeq - Counts", barcode = c("TCGA-BH-A0BQ"))
```

Or you can subset your object after GDCprepare (you can access sample information with colData(object)

```
exp <- exp[,exp$definition == "Primary solid Tumor"]
colData(exp)[,1:5]
```

<img width="673" alt="captura de tela 2017-01-15 as 17 13 26" src="https://cloud.githubusercontent.com/assets/145529/21968108/05404aca-db46-11e6-9e23-35953c13f74b.png">
