### ISSUE TITLE
duplicate columns in GDCquery_clinic results

### ISSUE THREAD

**Issue by cstubben** [BioinformaticsFMRP/TCGAbiolinks#60]
I'm using version 2.2.6 and updated_datetime, created_datetime and state columns are duplicated four times (with two state.x and two state.y columns).  I think you could drop  by="submitter_id" from all those merges to fix it?
 
```
clin <- GDCquery_clinic("TCGA-LGG")
table(duplicated(colnames(clin)))   
FALSE  TRUE 
   46     6 
```

**Comment by tiagochst** [comment]
Hi, 

This bug happens because we have 4 sub-tables (exposures, diagnosis, treatments and demographic) and some of them have this duplicated fields. I'll check if they are duplicated for all cases. If so, I'll remove it, otherwise I add a prefix to the fields.

Thanks for the report.

**Comment by tiagochst** [comment]
My code was showing that the values were equal, so I removed the duplicated fields
