### ISSUE TITLE
GDCquery with legacy=TRUE results in unused argument error

### ISSUE THREAD

**Issue by JuliusDeynet** [BioinformaticsFMRP/TCGAbiolinks#600]
The following query
```
query1 <- GDCquery(project = "TCGA-GBM" ,
                   data.category = "Gene expression",
                   data.type = "Gene expression quantification",
                   legacy = TRUE,
                   platform = "AgilentG4502A_07_1")
```
results in 

> Error in GDCquery(project = "TCGA-GBM", data.category = "Gene expression",  : 
>  unused argument (legacy = TRUE)

Because the data category "Gene expression" is only available in the legacy archive, it is needed. The query also rightfully complains about the invalid data category if the option is not used. That's why I don't understand the unused argument error.

Am I doing something wrong or is this a bug?

**Comment by tiagochst** [comment]
Hi, 

They have discontinued the legacy archive, which is why the legacy = TRUE option is no longer available. You can now access gene expression data using the following code:

```
query <- GDCquery(
    project = "TCGA-GBM",
    data.category = "Transcriptome Profiling",
    data.type = "Gene Expression Quantification", 
    workflow.type = "STAR - Counts"
)
```

**Comment by JuliusDeynet** [comment]
Thank you!

**Comment by clersdom** [comment]
Hi, 
Is there a way to access "HTSeq-Counts" for TCGA-COAD? I understand the arguments file.type  = "results" and legacy = TRUE have been disabled which were useful to retrive data below. 

file.type= "results" will select the .rsem.genes.results files
file.type= "normalized_results" will select the .rsem.genes.normalized_results files

Thus, could you please specify the way to get both RSEM data and HTSeq-Counts ?

Thanks in advance!
