### ISSUE TITLE
I couldn't find all the files from the query. Please check if the directory parameter is right or `GDCdownload` downloaded the samples.

### ISSUE THREAD

**Issue by lijiaze0331** [BioinformaticsFMRP/TCGAbiolinks#607]
setwd("H:\\RNAseq\\TCGA_done\\TCGA-PRAD")
query <- GDCquery(project = "TCGA-PRAD", 
                  data.category = "Transcriptome Profiling",
                  data.type = 'Gene Expression Quantification',
                  experimental.strategy = "RNA-Seq",
                  workflow.type = "STAR - Counts")
testdata <- GDCprepare(query = query, directory = 'GDCdata-TCGA-PRAD-COUNTS')
#Error in GDCprepare(query = query, directory = "GDCdata-TCGA-PRAD-CLINICDATA") : 
  I couldn't find all the files from the query. Please check if the directory parameter is right or `GDCdownload` downloaded the samples.

My question:
I have download the 'GDCdownload(query,directory = "GDCdata-TCGA-PRAD-COUNTS")' before, but it doesn't work when I use the code 'testdata <- GDCprepare(query = query, directory = 'GDCdata-TCGA-PRAD-COUNTS')'.
But when I change the folder name 'GDCdata-TCGA-PRAD-COUNTS' to 'GDCdata', the code 'testdata <- GDCprepare(query = query, directory = 'GDCdata')' is able to work.
So what happened?????

**Comment by tiagochst** [comment]
Hi,

Sorry, but I got confused with the code in the issue.

1) It seems the error is pointing to another directory.
testdata <- GDCprepare(query = query, directory = 'GDCdata-TCGA
-PRAD-COUNTS')
#Error in GDCprepare(query = query, directory = "GDCdata-TCGA-PRAD-CLINICDATA")
:

2) If you ran GDCdownload(query,directory = "GDCdata-TCGA-PRAD-COUNTS2")
previously
the code to prepare pointing to another directory (COUNTS2 vs COUNTS) will
not work
testdata <- GDCprepare(query = query, directory = 'GDCdata-TCGA
-PRAD-COUNTS')


This example below is working on my side:

query <- GDCquery(
    project = "TCGA-PRAD",
    data.category = "Transcriptome Profiling",
    data.type = 'Gene Expression Quantification',
    experimental.strategy = "RNA-Seq",
    workflow.type = "STAR - Counts",
    barcode = c(
        "TCGA-J9-A8CL-01A-11R-A352-07",
        "TCGA-EJ-A46B-01A-31R-A250-07",
        "TCGA-EJ-5509-01A-01R-1580-07",
        "TCGA-EJ-7782-01A-11R-2118-07"
    )
)
GDCdownload(query, directory = 'GDCdata-TCGA-PRAD-COUNTS')
testdata <- GDCprepare(query = query, directory =
'GDCdata-TCGA-PRAD-COUNTS')

Best regards,
Tiago
