### ISSUE TITLE
Encountered an error while retrieving TCGA Simple Nucleotide Variation data using GDCprepare

### ISSUE THREAD

**Issue by AlexanderXie98** [BioinformaticsFMRP/TCGAbiolinks#609]
I encountered an issue when using `GDCprepare` from` TCGAbiolinks version 2.30.0` to retrieve Simple Nucleotide Variation data for `TCGA-CESC`. The error message is as follows:
```
dplyr::bind_rows(res, .id = .id)
Error in `dplyr::bind_rows()`: ! Can't combine `..20$Tumor_Seq_Allele2` <character> and `..21$Tumor_Seq_Allele2` <logical>.
```
Upon reviewing the source code, I have identified that this error is triggered by `purrr::map_dfr(...) `under `readSimpleNucleotideVariationMaf(files)`. I am uncertain about how to resolve this issue and would greatly appreciate any help.

Thank you very much!

Best regards,
Alexander

**Comment by sigven** [comment]
I have encountered the same issue with `GDCprepare` (v2.30.0) for the `TCGA-CHOL` cohort:

`Can't combine `..45$Tumor_Seq_Allele2` <character> and `..46$Tumor_Seq_Allele2` <logical>`

**Comment by tiagochst** [comment]
Thank you for the bug report.

Please, could you try updating to the latest version in github please:
BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")

**Comment by sigven** [comment]
Thanks, works now:-)

**Comment by Hawyoo** [comment]
TCGA-BRCA works now, too :-)

**Comment by elsiebrownn** [comment]
> Thank you for the bug report. Please, could you try updating to the latest version in github please: BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")
> […](#)

Hi, I'm having the same issue for BRCA and LAML - using v2.31.2
