### ISSUE TITLE
Error in GDCquery_clinic(project ="TCGA-TGCT")

### ISSUE THREAD

**Issue by ayueme** [BioinformaticsFMRP/TCGAbiolinks#613]
Hello there,
   I'm trying to download the clinical data from GDC TCGA, but when I run the following code:
```
GDCquery_clinic(project = "TCGA-TGCT")
```
it gave me this error:
```
Error in GDCquery_clinic(project = "TCGA-TGCT") : 
  Error: API returned more information
```
I tried other TCGA projects, they were all OK.
Anything wrong with "TCGA-TGCT"?

Thank you.

**Comment by AngelaQChen** [comment]
I am having the same problem, could not pull TGCT clinical data

**Comment by AngelaQChen** [comment]
I was able to fix this by updating to the latest version of TCGAbiolinks

install.packages("../TCGAbiolinks_2.32.0.tar.gz", repos = NULL, type="source")
library(TCGAbiolinks)

clinical <- GDCquery_clinic(project = "TCGA-TGCT", type = "clinical")

**Comment by ayueme** [comment]
> I was able to fix this by updating to the latest version of TCGAbiolinks
> 
> install.packages("../TCGAbiolinks_2.32.0.tar.gz", repos = NULL, type="source") library(TCGAbiolinks)
> 
> clinical <- GDCquery_clinic(project = "TCGA-TGCT", type = "clinical")

Thank you for your kind response.
