### ISSUE TITLE
Problem accessing miRNA data

### ISSUE THREAD

**Issue by rolfhaut** [BioinformaticsFMRP/TCGAbiolinks#62]
Hi,

So I'm currently trying to get my TCGA data analysis to work again since it moved from the TCGA website. So thanks already for all the work you put in to update the package.
But I wanted to access the miRNA data and get an error irrespective if I go for the harmonized data or the legacy. So I just run:

`query.miR <- GDCquery(project = "TCGA-SKCM", 
                      data.category = "Gene expression",
                      data.type = "miRNA gene quantification",
                      file.type = "hg19.mirna",
                      legacy = TRUE)`

And the outcome is:

 
>  GDCquery: Searching in GDC database
> --------------------------------------
> --------------------------------------------
> oo Accessing GDC. This might take a while...
> --------------------------------------------
> ooo Project: TCGA-SKCM
> --------------------
> oo Filtering results
> --------------------
> ooo By data.type
> ooo By file.type
> Error in expandBarcodeInfo(barcodes) : object 'ret' not 
 > found.

I get the same error if I run the example of the vignette.
For mRNA expression data it works. Also for maf. Just the miRNA seem not to work for me.
Session info:
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] TCGAbiolinks_2.3.15

Any idea how the problem can be solved?
Thanks + kind regards
david

**Comment by tiagochst** [comment]
Hi David,

I recently made a change in the code. There was one case with a problem of matching the miRNA files. I will check the other case to see the right solution. 
These are the two filters that are working with this case.
```
query.miR <- GDCquery(project = "TCGA-SKCM", 
                      data.category = "Gene expression", 
                      data.type = "miRNA gene quantification", 
                      file.type = "hg19.mirbase20", legacy = TRUE)
query.miR <- GDCquery(project = "TCGA-SKCM", 
                      data.category = "Gene expression", 
                      data.type = "miRNA gene quantification", 
                      file.type = "mirna", legacy = TRUE)
```

**Comment by rolfhaut** [comment]
Hi Tiago,

Great. Thanks for the fast reply. With these two filters it worked. 
Thanks
David

**Comment by tiagochst** [comment]
I found the case for TCGA-COAD we have 3 file types for each sample:

- TCGA-G4-6588-01A-11H-1773-13.hg19.mirbase20.mirna.quantification.txt
- TCGA-G4-6588-01A-11H-1773-13.hg19.mirna.quantification.txt         
- TCGA-G4-6588-01A-11H-1773-13.mirna.quantification.txt

These will be selected using the following file.types
- hg19.mirbase20
- hg19.mirna
- mirna
 

The case can be checked with the code below:
```
for(f in c("hg19.mirbase20", "hg19.mirna","mirna")) {
    message("Testing: ", f)
    suppressMessages(
        query <- GDCquery(project = "TCGA-COAD", 
                          data.category = "Gene expression",
                          file.type =  f,
                          data.type = "miRNA gene quantification",
                          platform="Illumina HiSeq",
                          legacy = TRUE)
    )
    message(query$results[[1]]$file_name[1])
}
```

I will improve the output of the error so that will be easier to find the problem.

**Comment by behnazhoseyni** [comment]
hello.please help me.
I use this code:
tumorSampleTypes = c(tumorSampleTypes,
                         'Primary Blood Derived Cancer - Peripheral Blood',
                         'Primary Blood Derived Cancer - Bone Marrow')
    normalSampleTypes = c(normalSampleTypes,
                          'Blood Derived Normal',
                          'Bone Marrow Normal')

queryOfGeneExpressionCounts = GDCquery(project = selectedProject,
                                         data.category = 'Transcriptome Profiling',
                                         data.type = 'Gene Expression Quantification',
                                         workflow.type = 'HTSeq - Counts',
                                         sample.type = c(tumorSampleTypes, normalSampleTypes))
but I get this error:
Error in expandBarcodeInfo(barcodes) : object 'ret' not found

**Comment by tiagochst** [comment]
@behnazhoseyni Which version of the package are you using?

**Comment by behnazhoseyni** [comment]
TCGAbiolinks version 2.12.2 
R version 3.6.0

**Comment by tiagochst** [comment]
Can you say which is your `selectedProject`?

**Comment by tiagochst** [comment]
And `sample.type = c(tumorSampleTypes, normalSampleTypes))`

**Comment by behnazhoseyni** [comment]
yes ! now  selectedproject is "CPTAC-3", but I use for loop  and repeat this code for many project_ids in GDCProjects that I get this with GDCProjects = as.data.frame(getGDCprojects()
and:
tumorSampleTypes = c('Primary solid Tumor',
                         'Primary Blood Derived Cancer - Peripheral Blood',
                         'Primary Blood Derived Cancer - Bone Marrow')
    normalSampleTypes = c('Solid Tissue Normal',
                          'Blood Derived Normal',
                          'Bone Marrow Normal')

thank you veryyyyyyyyyyyyyyy much

**Comment by tiagochst** [comment]
We only have support to TCGA and TARGET. I'll try to add support to the other projects this week.
I was not aware that more projects were added. I'll send you a message back when it is done.

**Comment by behnazhoseyni** [comment]
thank you very much.
Good luck

**Comment by tiagochst** [comment]
It might take a while to give support. It seems there are some inconsistencies with the data in GDC. One file with mapped to two samples, files without sample ID.
I am waiting an answer from GDC. But the way the data is returning from the API. It will be quite impossible to add the same logic as TCGA and TARGET.

**Comment by behnazhoseyni** [comment]
thank you.this code work for TCGA and TARGET.but for CPTAC-3 doesn't work. I'm also exploring
thank you very much
