### ISSUE TITLE
Error GDC download

### ISSUE THREAD

**Issue by TilmanVoss** [BioinformaticsFMRP/TCGAbiolinks#67]
I have tried to download isoform expression data using the following script based on 
https://bioconductor.org/packages/release/bioc/vignettes/TCGAbiolinks/inst/doc/tcgaBiolinks.html#gdcdownload-downloading-gdc-data
 We have version 2.0.6
 
query.exp.hg38 <- GDCquery(project = "TCGA-GBM", 
                           data.category = "Transcriptome Profiling", 
                           data.type = "Isoform Expression Quantification", 
                           barcode =  c("TCGA-14-0736-02A-01R-2005-01", "TCGA-06-0211-02A-02R-2005-01"))
 
however, I got the following error message
 
Accessing GDC. This might take a while...
Error in GDCquery(project = "TCGA-GBM", data.category = "Transcriptome Profiling",  : 
  Please set a valid data.type argument from the list below:
  => Gene Expression Quantification
> 
 
Is this a bug or an error in the  description?

**Comment by tiagochst** [comment]
The code is right except those barcode does not match any of the barcodes available.
The barcodes available are below:
```
query.exp.hg38 <- GDCquery(project = "TCGA-GBM", 
                           data.category = "Transcriptome Profiling", 
                           data.type = "Isoform Expression Quantification")
knitr::kable(getResults(query.exp.hg38)$cases)
```

|                             |
|:----------------------------|
|TCGA-06-0680-11A-32R-A36C-13 |
|TCGA-06-0681-11A-41R-A36C-13 |
|TCGA-06-0678-11A-32R-A36C-13 |
|TCGA-06-AABW-11A-31R-A36C-13 |
|TCGA-06-0675-11A-32R-A36C-13 |


Also you can verify there are only 5 files in GDC 
<img width="963" alt="captura de tela 2017-02-19 as 20 41 56" src="https://cloud.githubusercontent.com/assets/145529/23107969/6b3c7fb0-f6e4-11e6-9d22-23c90a6bb7b8.png">
