### ISSUE TITLE
GDCprepare Hide Progress Bar

### ISSUE THREAD

**Issue by DarioS** [BioinformaticsFMRP/TCGAbiolinks#68]
The `GDCprepare` function shows a progress bar and there's no parameter to turn it off. This creates a mess when rendering R Markdown reports. Can a parameter be added to allow users to turn it off? Please add this to both release and development versions.

**Comment by tiagochst** [comment]
You can hide the progress bar in the vignette.
For example in this [vignette](http://bioinformaticsfmrp.github.io/TCGAbiolinks/download_prepare.html) we are executing GDCdownload but we are hiding the progress bar with:
```
```{r results = 'hide', message=FALSE, warning=FALSE}
```

The code is [here](https://raw.githubusercontent.com/BioinformaticsFMRP/TCGAbiolinks/master/vignettes/download_prepare.Rmd).

Would this solve your problem ? I will loose some time to add this feature, and I feel this is not really necessary.

**Comment by DarioS** [comment]
It's an adequate alternative.
