### ISSUE TITLE
maybe a problem to download

### ISSUE THREAD

**Issue by hibarikyouya** [BioinformaticsFMRP/TCGAbiolinks#7]
Hi all !

Hope everybody is ok, thanks for the guys who are active here :)
There might a problem with the TCGAdownload function at the moment.
Code that used to work before don't work anymore on my machine.
For example :

`query <- TCGAquery(tumor="BRCA", level=3, platform="MDA_RPPA_Core")`
`TCGAdownload(query, path="rppa")`

or :

`TCGAdownload(query, path="rppa", samples=c("TCGA-E2-A14V-01A-21-A13E-20"))`

gives me :

`
-=-=-=-=-=-=
| Downloading:5 folders
| Path:rppa
-=-=-=-=-=-=
  |                                                                      |   0%
Downloading:mdanderson.org_BRCA.MDA_RPPA_Core.Level_3.1.3.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   240  100   240    0     0     40      0  0:00:06  0:00:05  0:00:01    54
100  2060  100  2060    0     0    343      0  0:00:06  0:00:05  0:00:01   343
Error in fread(paste0(root, data[i, "deployLocation"], ".md5"), header = F,  :
  Expected sep (',') but new line or EOF ends field 1 on line 33 when reading data: -->
De plus : Warning messages:
1: In fread(paste0(root, data[i, "deployLocation"], ".md5"), header = F,  :
  Unable to find 5 lines with expected number of columns (+ middle)
2: In fread(paste0(root, data[i, "deployLocation"], ".md5"), header = F,  :
  Unable to find 5 lines with expected number of columns (+   last)
`

Can somebody try to see if I'm dumb or it's not me.
Thanks :)

**Comment by labrazil** [comment]
Hi, it's due to a maintenance issue over at TCGA.

https://tcga-data.nci.nih.gov/maintenance_deploying.html

Houtan

---
\hn
cell (USA): +1-310-570-2362
cell (BRA): +55-16-99779-2362

**Comment by tiagochst** [comment]
Our team updated TCGAbiolinks to work with the new GDC portal. We had to rewrite almost all the code again, but we hope this will help improve our tool which we are dedicated to improving.
Unfortunately, the changes are not in the Bioconductor repository, but we anticipate the codes will be updated within the coming weeks. For the moment, if you require the new package, you can install it from our GitHub repository with the following command:

`devtools::install_github(repo = "BioinformaticsFMRP/TCGAbiolinks")
`

The protein expression data is only available in the legacy database, this code will work for you:

The only problem is that GDC is downloading for all cases the same mage file (it is 25MB). This problem happens even if you download using the browser. 
I reported the problem to the github channel. I hope they fix this problem soon.

```
query <- GDCquery(project = "TCGA-BRCA", 
                  data.category = "Protein expression",
                  platform = "MDA_RPPA_Core", legacy = TRUE) 
GDCDownload(query)
data <- GDCPrepare(query)
```
