### ISSUE TITLE
Intersection of Differentially Expressed mRNA-miRNA data for TCGA-BRCA

### ISSUE THREAD

**Issue by paridhichoudhary** [BioinformaticsFMRP/TCGAbiolinks#73]
Hi,

I am using TCGABiolinks to extract mRNA and miRNA data for TCGA-BRCA for further correlation calculations between the RNA and miRNA gene expression data. 

I will demonstrate the process that I have used for extracting and processing this data:
rnaquery <- GDCquery(project = "TCGA-BRCA", 
                data.category = "Gene expression",
                data.type = "Gene expression quantification",
                experimental.strategy = "RNA-Seq",
                platform = "Illumina HiSeq",
                file.type = "results",
                legacy = TRUE)

mirnaquery <- GDCquery(project = "TCGA-BRCA",
                  data.category = "Gene expression",
                  data.type = "miRNA gene quantification", 
                  file.type = "hg19.mirna",
                  legacy = TRUE)

GDCdownload(rnaquery) # Running the download query to check if its working fine
GDCdownload(mirnaquery) # Running the download query to check if its working fine

BRCARnaseq_assay_rna <- GDCprepare(rnaquery)
BRCARnaseq_assay_mirna <- GDCprepare(mirnaquery)

But when I check the samples which come in RNA and the ones that come up in MIRNA, there is no intersection. 

I would like to understand is this a data problem or I am extracting the data wrong?

**Comment by tiagochst** [comment]
there should be 1184 intersections:

```
rnaquery <- GDCquery(project = "TCGA-BRCA",
                     data.category = "Gene expression",
                     data.type = "Gene expression quantification",
                     experimental.strategy = "RNA-Seq",
                     platform = "Illumina HiSeq",
                     file.type = "results",
                     legacy = TRUE)

mirnaquery <- GDCquery(project = "TCGA-BRCA",
                       data.category = "Gene expression",
                       data.type = "miRNA gene quantification",
                       file.type = "mirna",
                       legacy = TRUE)

table(substr(getResults(rnaquery)$cases,1,15) %in% substr(getResults(mirnaquery)$cases,1,15))
```
<img width="597" alt="screen shot 2017-03-15 at 5 13 09 pm" src="https://cloud.githubusercontent.com/assets/145529/23976113/b2e9fb50-09a2-11e7-8d90-966b1f29bfe6.png">
