### ISSUE TITLE
GDCquery 'clinical' for legacy fails

### ISSUE THREAD

**Issue by mattiasaine** [BioinformaticsFMRP/TCGAbiolinks#75]
Hi, was trying your tool to get the clin-data for TCGA-LAML. 

Running the query below with legacy=FALSE works fine and generates the full catalog tree and all downstream functions seem to work as well. 

However running it with the legacy=TRUE setting generates a warning.
`query <- GDCquery(project = "TCGA-LAML",data.category = "Clinical",legacy = TRUE) `
>Warning: There are more than one file for the same case. Please verify query results. You can use the command View(query$results[[1]]) in rstudio

Running `GDCdownload(query)` after this results in the following download failure.
> Downloading data for project TCGA-LAML
> GDCdownload will download 206 files. A total of 11.024551 MB
> Downloading as: Wed_Mar_29_09_35_55_2017.tar.gz
> Downloading: 7.7 kB     
> ....Lots of this...
> Downloading: 1 MB     
> Downloading: 1 MB     Download failed. We will retry with smaller chuncks
> Downloading chunk 0 of 0 (206 files, size = 11.024551 MB) as Wed_Mar_29_09_35_55_2017_0.tar.gz
>  |   0% =======| 100% /usr/bin/tar: This does not look like a tar archive
>  gzip:
>  stdin: not in gzip format
> /usr/bin/tar: Child returned status 1
> /usr/bin/tar: Exiting with failure status due to previous errors
> Download completed

Running `GDCdownload(query,method = "client")` fails to build a catalog tree and the function just pukes out all the downloaded files in ".".

How should I parse the `query`-object to get rid of the offending duplicates or whatever is causing this behaviour?

**Comment by mattiasaine** [comment]
Bit hasty there maybe..

Seems the legacy pull retrieves more than just the "Clinical Supplement"-files and this causes the error.

Removing the extra files seems to fix it also for downstream functions.
`filter<-clin.query$results[[1]][1]=="Clinical Supplement"`
`clin.query$results[[1]]<-clin.query$results[[1]][filter,]`

**Comment by tiagochst** [comment]
GDC fixed the index to some clinical data (biotab for example), this broke the package.
We will need to fix it.

**Comment by tiagochst** [comment]
I updated the package and the information to work with legacy clinical data.
http://bioinformaticsfmrp.github.io/TCGAbiolinks/clinical.html#get_legacy_clinical_data
