### ISSUE TITLE
Have problem to get all clinical indexed data

### ISSUE THREAD

**Issue by JRLi** [BioinformaticsFMRP/TCGAbiolinks#76]
Hi, I am trying to get all clinical data from GDC with TCGAbiolinks, however,
I have an issue such as follow:
> library(TCGAbiolinks)
> library(dplyr)
> library(DT)
> library("regexPipes", lib.loc="~/R/win-library/3.3")
> library(data.table)
> clinical <- TCGAbiolinks:::getGDCprojects()$project_id %>% 
>   regexPipes::grep("TCGA",value=T) %>% 
>   sort %>% 
>   plyr::alply(1,GDCquery_clinic, .progress = "text") %>% 
>   rbindlist
 |=======================================================================================| 100%
> readr::write_csv(clinical,path = paste0("all_clin_indexed.csv"))
Error in stream_delim_(df, path, ...) : 
  Don't know how to handle vector of type list.

I tried to solve the problem, still unresolved.
May you help me for this issue? Thanks!!

**Comment by tiagochst** [comment]
There was a change in the API, one of the fields is a list (treatments). I'll update the code to unlist and add a prefix. For the moment you can do:

```
library(TCGAbiolinks)
library(dplyr)
library(DT)
library("regexPipes")
library(data.table)
clinical <- TCGAbiolinks:::getGDCprojects()$project_id %>%
  regexPipes::grep("TCGA",value=T) %>%
  sort %>%
  plyr::alply(1,GDCquery_clinic, .progress = "text") %>%
  rbindlist
clinical$treatments <- NULL
readr::write_csv(clinical,path = "all_clin_indexed.csv")

```
