### ISSUE TITLE
GDCprepare Error . "Error in gene.location$ensembl_gene_id :    $ operator is invalid for atomic vectors"

### ISSUE THREAD

**Issue by g7kevin** [BioinformaticsFMRP/TCGAbiolinks#77]
Hi, I am new to TCGAbiolinks.
When I try the following code in the TCGAbiolinks help documents,  the GDCprepare  always gives me the error message (Error in gene.location$ensembl_gene_id :  $ operator is invalid for atomic vectors). I have no idea what is wrong.  Would you please give me some advice. Thank you very much.

CancerProject <- "TCGA-BRCA"
DataDirectory <- paste0("../GDC/",gsub("-","_",CancerProject))
FileNameData <- paste0(DataDirectory, "_","HTSeq_Counts",".rda")

query <- GDCquery(project = CancerProject,
                  data.category = "Transcriptome Profiling",
                  data.type = "Gene Expression Quantification", 
                  workflow.type = "HTSeq - Counts")

samplesDown <- getResults(query,cols=c("cases"))

dataSmTP <- TCGAquery_SampleTypes(barcode = samplesDown,
                                  typesample = "TP")

dataSmNT <- TCGAquery_SampleTypes(barcode = samplesDown,
                                  typesample = "NT")
dataSmTP_short <- dataSmTP[1:10]
dataSmNT_short <- dataSmNT[1:10]

queryDown <- GDCquery(project = CancerProject, 
                      data.category = "Transcriptome Profiling",
                      data.type = "Gene Expression Quantification", 
                      workflow.type = "HTSeq - Counts", 
                      barcode = c(dataSmTP_short, dataSmNT_short))
                    
GDCdownload(query = queryDown,
            directory = DataDirectory)

dataPrep <- GDCprepare(query = queryDown, 
                       save = TRUE, 
                       directory =  DataDirectory,
                       save.filename = FileNameData)

**Comment by tiagochst** [comment]
Does this code works for you?
```
library(biomaRt)
ensembl <- useMart(biomart = "ENSEMBL_MART_ENSEMBL",
                   host = "feb2014.archive.ensembl.org",
                   path = "/biomart/martservice" ,
                   dataset = "hsapiens_gene_ensembl")
attributes <- c("chromosome_name",
                "start_position",
                "end_position", "strand",
                "ensembl_gene_id", "entrezgene",
                "external_gene_id")
chrom <- c(1:22, "X", "Y")
gene.location <- getBM(attributes = attributes,
                       filters = c("chromosome_name"),
                       values = list(chrom), mart = ensembl)
head(gene.location$ensembl_gene_id)
```

**Comment by g7kevin** [comment]
Great!   It works now.  Thank you very much.

**Comment by lhhaoliu** [comment]
Looks like there is still issue with this program:

> dataPrep1 <- GDCprepare(query = queryDown, 
+                         save = TRUE, 
+                         save.filename = "TCGA_LAML_HTSeq_Countds.rda")
|===============================================================================================| 100%    1 MB
  |====================================================================================================| 100%
Starting to add information to samples
 => Add clinical information to samples
Add FFPE information. More information at: 
=> https://cancergenome.nih.gov/cancersselected/biospeccriteria 
=> http://gdac.broadinstitute.org/runs/sampleReports/latest/FPPP_FFPE_Cases.html
 => Adding subtype information to samples
Downloading genome information (try:0) Using: 
Error: $ operator is invalid for atomic vectors
