### ISSUE TITLE
GDCdownload error

### ISSUE THREAD

**Issue by mbk0asis** [BioinformaticsFMRP/TCGAbiolinks#80]
Hi.

'GDCdownload' is giving me this error. What could be the problem?

```
> GDCdownload(query)
GDCdownload will download 5201 files. A total of 110.697216048 GB
Downloading as: Tue_Apr_11_09_28_55_2017.tar.gz
  |========================================================================================================| 100%
/bin/tar: This does not look like a tar archive

gzip: stdin: not in gzip format
/bin/tar: Child returned status 1
/bin/tar: Error is not recoverable: exiting now
Download completed
```

**Comment by mbk0asis** [comment]
After several trial, it worked.

I just entered the same code several times, and it suddenly worked.

**Comment by tiagochst** [comment]
The problem is that is tries to download all files in one tar.gz. It would be better to use `chunks.per.download` argument `GDCdownload(query,chunks.per.download = 50)`. I'll take a look on the code again.  This should be set automatically for this case.
