### ISSUE TITLE
error

### ISSUE THREAD

**Issue by olgabogi** [BioinformaticsFMRP/TCGAbiolinks#82]
I got the same error: 
Error in value[[3L]](cond) : 
  GDC server down, try to use this package later

and when I tried to load new verstion, as you suggested, got another error:. 

BioC_mirror: https://bioconductor.org
Using Bioconductor 3.4 (BiocInstaller 1.24.0), R 3.3.2 (2016-10-31).
Installing github package(s) ‘Bioconductor/GenomicDataCommons’
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Couldn't connect to server

can it be because of proxy connection_? 
and if yes, how can I fix it? 
thanks

**Comment by tiagochst** [comment]
Please, could you send your sessionInfo()?

Maybe this problem might be the same as the one here. Please, could you check if it solves your problem?
https://github.com/Bioconductor/GenomicDataCommons#troubleshooting

**Comment by tiagochst** [comment]
The same problem can be found in #71.
