### ISSUE TITLE
Prepare.R, Clinical.R, Analyze.R : fixed bugs

### ISSUE THREAD

**Issue by simomounir** [BioinformaticsFMRP/TCGAbiolinks#87]
-I have been trying to run GDCprepare function using TARGET cases but it run into some dataframe related error and found out it was due to duplicates that caused an error in SummarizedExperiment function. More specifically in makeSEfromTranscriptomeProfiling() under Prepare.R 
I took care of that but testing the working version would be much more than welcome.

-In Clinical.R, parsing of the barcode threw an error since TARGET barcodes are a bit different. Added a parsing case for TARGET data under TCGAquery_SampleTypes.

-In Analyze.R, parsing tissue type for TARGET data is now supported as well under TCGAanalyze_Preprocessing function. 

There is an attached R code for Differential Expression Analysis of TARGET data, try the pipeline and it would be good to have feedback if it works

Thanks
[TARGET_DEA_Pipeline.txt](https://github.com/BioinformaticsFMRP/TCGAbiolinks/files/993596/TARGET_DEA_Pipeline.txt)

**Comment by tiagochst** [comment]
I'll recheck the pipeline for TARGET, but  the first one I solved two days ago. I'll check the others.
