### ISSUE TITLE
strange message when using GDCprepare 

### ISSUE THREAD

**Issue by hongenxu** [BioinformaticsFMRP/TCGAbiolinks#88]
Hi, 

When I use GDCprepare, I got some strange message 

"Downloading genome information. Using: C.intestinalis genes (KH)", 

for sometime, I got 

Downloading genome information. Using: Turkey genes (Turkey_2.01).

Best,
Hongen

**Comment by tiagochst** [comment]
This problem was solved some weeks ago. Please, could you update it the package. It is only the print message which is wrong the reference was downloaded correctly.
