### ISSUE TITLE
Duplicate records in colData raises an error in v2.4.0 but not in v2.3.23

### ISSUE THREAD

**Issue by wenching** [BioinformaticsFMRP/TCGAbiolinks#89]
Hi there,

Here is the way to get the error message from v2.4.0, but a SE result from v2.3.23

many thanks

> df.query <- TCGAbiolinks::GDCquery(project = "TARGET-AML", 
                                   data.category = "Transcriptome Profiling", 
                                   data.type = "Gene Expression Quantification", 
                                   workflow.type = "HTSeq - Counts", barcode = c("TARGET-20-PAEIKD-04A-01R", "TARGET-20-PAEIKD-09A-01R"))

> TCGAbiolinks::GDCprepare(query = df.query,
                         directory = "GDCdata",
                         summarizedExperiment = T)

v2.4.0 (installation via BiocInstaller)

Starting to add information to samples
Adding description to TARGET samples
 => Add clinical information to samples
Downloading genome information (try:0) Using: Human genes (GRCh38.p10)
Loading from disk
From the 60488 genes we couldn't map 3453
Error in validObject(.Object) : 
  invalid class “SummarizedExperiment” object: 
  nb of cols in 'assay' (2) must equal nb of rows in 'colData' (4)        

> sessionInfo()
other attached packages:
 [1] SummarizedExperiment_1.6.1 DelayedArray_0.2.2         matrixStats_0.52.2         Biobase_2.36.2             GenomicRanges_1.28.1       GenomeInfoDb_1.12.0       
 [7] IRanges_2.10.0             S4Vectors_0.14.0           BiocGenerics_0.22.0        **TCGAbiolinks_2.4.0**             

v2.3.23 (source from GitHub, BioinformaticsFMRP/TCGAbiolinks)

Starting to add information to samples
Adding description to TARGET samples
 => Add clinical information to samples
Downloading genome information (try:0) Using: Human genes (GRCh38.p10)
Loading from disk
From the 60488 genes we couldn't map 3453
class: RangedSummarizedExperiment 
dim: 57035 2 
metadata(0):
assays(1): HTSeq - Counts
rownames(57035): ENSG00000000003 ENSG00000000005 ... ENSG00000281912 ENSG00000281920
rowData names(3): ensembl_gene_id external_gene_name original_ensembl_gene_id
colnames(2): TARGET-20-PAEIKD-04A-01R TARGET-20-PAEIKD-09A-01R
colData names(36): patient nucleic.acid.code ... project_id name

> sessionInfo()
other attached packages:
 [1] SummarizedExperiment_1.6.1 DelayedArray_0.2.2         matrixStats_0.52.2         Biobase_2.36.2             GenomicRanges_1.28.1       GenomeInfoDb_1.12.0       
 [7] IRanges_2.10.0             S4Vectors_0.14.0           BiocGenerics_0.22.0        **TCGAbiolinks_2.3.23**

**Comment by tiagochst** [comment]
v2.3.23 was supposed higher than v2.4.0. I just fixed the numbers in the github. 
I fixed that problem two days ago but it is not in Bioconductor yet.
