### ISSUE TITLE
Update TCGAbiolinks to GDC

### ISSUE THREAD

**Issue by tiagochst** [BioinformaticsFMRP/TCGAbiolinks#9]
TCGA data is now in the GDC portal.
As the old API will no more be supoorted, GDC API should be used.

**Comment by WaltWu** [comment]
@tiagochst 
I am glad to know that your group is now updating TCGAbiolinks because it is really helpful to me.
I am looking forward to the completion of the update :)

Walt

**Comment by hibarikyouya** [comment]
just thank you
