### ISSUE TITLE
Multiple follow-up versions not handled well by GDCprepare_clinic()

### ISSUE THREAD

**Issue by EdMroz** [BioinformaticsFMRP/TCGAbiolinks#93]
The code for parsing "follow_up" information in `GDCprepare_clinic()` (in TCGAbiolinks_2.0.13) seems to have a problem if a set of xml files includes more than one follow_up version. It includes the following code to check for multiple follow_up versions:

    if (tolower(clinical.info) == "follow_up") {
        xmlfile <- files[1]
        xml <- read_xml(xmlfile)
        follow_up_version <- names(xml_ns(xml))[grepl("follow_up", 
            names(xml_ns(xml)))]
        if (length(follow_up_version) > 1) {
            n <- readline(prompt = paste0("There is more than one follow up version, please select one", 
                paste0(seq(1:length(follow_up_version)), follow_up_version)))
            follow_up_version <- follow_up_version[n]
        }

It thus checks the first of a list of xmlfiles for having more than 1 follow_up version in its xml namespace and provides a choice if more than one follow_up version is in the namespace.

At least with the TCGA-HNSC clinical data, however, the xml namespace for each individual clinical xml file only seems to include the particular follow_up version used in that file (v1.0 or v4.8). So if a list of xml files contains different follow_up versions but the first file only contains one version, there is no choice presented to select a desired follow_up version; only the follow_up version in `files[1]` is reported. 

With data obtained the following way on 22 May:

    > query <- GDCquery(project="TCGA-HNSC",data.category="Clinical")
    > GDCdownload(query)

the command:

    > clinical.fu <- GDCprepare_clinic(query,"follow_up")

only provided data for follow_up_v4.8, omitting data for cases with follow_up_v1.0

With the old `TCGAquery_clinic()` function, it was possible to select a particular desired follow_up version. That seems not to be possible with `GDGprepare_clinic()`.

**Comment by tiagochst** [comment]
@EdMroz Thanks for the bug report.

I made a change in the code. It will parse all versions and add the version number to the table.
Then the user can select the versions he wants.

<img width="938" alt="screen shot 2017-05-23 at 12 26 02 pm" src="https://cloud.githubusercontent.com/assets/145529/26372516/1a3deb04-3fb3-11e7-928a-e7f5c93f9159.png">

<img width="801" alt="screen shot 2017-05-23 at 12 28 49 pm" src="https://cloud.githubusercontent.com/assets/145529/26372635/702a2f6e-3fb3-11e7-969a-cc3c38fef1bf.png">

As you said there are cases in version 1 and not in version 4 for example.

**Comment by EdMroz** [comment]
Thanks.

-Ed
