### ISSUE TITLE
Question: TCGAvisualize_EAbarplot Function Issue

### ISSUE THREAD

**Issue by xiatingp** [BioinformaticsFMRP/TCGAbiolinks#95]
Hi,

I am trying to run the TCGAvisualize_EAbarplot function, but instead of producing the expected charts it produced nothing, specifically it runs the function, then after the last step says null device. Any ideas why it didn't run and just produced the null device message? thank you!

This is the exact message it produces:
```
TCGAvisualize_EAbarplot(tf = rownames(ansEA$ResBP),

+                         GOBPTab = ansEA$ResBP,
+                         GOCCTab = ansEA$ResCC,
+                         GOMFTab = ansEA$ResMF,
+                         PathTab = ansEA$ResPat,
+                         nRGTab = rownames(dataDEGs),
+                         nBar = 20)
null device 
         1
```

**Comment by xiatingp** [comment]
According to the func's docs the default is for the output to be written to : TCGAvisualize_EAbarplot_Output.pdf. Check  working directory for this file.

**Comment by besli** [comment]
> TCGAvisualize_EAbarplot(tf = rownames(ansEA$ResBP), 
+                         GOBPTab = ansEA$ResBP,
+                         GOCCTab = ansEA$ResCC,
+                         GOMFTab = ansEA$ResMF,
+                         PathTab = ansEA$ResPat,
+                         nRGTab = Genelist, 
+                         nBar = 10,
+                         filename="a.pdf") 
null device 
          1 

I have the same problem to output the plots. Would you help me out?

I added that script " while (!(is.null(dev.list()["RStudioGD"]))){dev.off()} " but it didn't work.
